arena_info = {'Forest': '(ELD) 266', 'Swamp': '(ELD) 258', 'Mountain': '(ELD) 262', 'Plains': '(ELD) 250',
               'Island': '(ELD) 254',
    'Aven Sentry': '(DAR) 3', 'Charge': '(DAR) 10', "D'Avenant Trapper": '(DAR) 11',
              'Pegasus Courser': '(DAR) 29', 'Academy Journeymage': '(DAR) 41', 'Arcane Flight': '(DAR) 43',
              'Befuddle': '(DAR) 45', 'Relic Runner': '(DAR) 62', 'Drudge Sentinel': '(DAR) 89',
              'Fire Elemental': '(DAR) 120', 'Keldon Raider': '(DAR) 135', 'Rampaging Cyclops': '(DAR) 139',
              'Aesthir Glider': '(DAR) 209', 'Juggernaut': '(DAR) 222', 'Excavation Elephant': '(DAR) 17',
              'Sergeant-at-Arms': '(DAR) 32', 'Serra Disciple': '(DAR) 34', 'Academy Drake': '(DAR) 40',
              'Cloudreader Sphinx': '(DAR) 47', 'Cold-Water Snapper': '(DAR) 48', 'Divination': '(DAR) 52',
              'Tolarian Scholar': '(DAR) 71', 'Fiery Intervention': '(DAR) 118', 'Arbor Armament': '(DAR) 155',
              "Gaea's Protector": '(DAR) 162', 'Pierce the Sky': '(DAR) 176', 'Bloodtallow Candle': '(DAR) 212',
              'Guardians of Koilos': '(DAR) 216', 'Sparring Construct': '(DAR) 232', 'Mesa Unicorn': '(DAR) 27',
              'Sanctum Spirit': '(DAR) 30', 'Tragic Poet': '(DAR) 37', 'Rescue': '(DAR) 63',
              'Cabal Paladin': '(DAR) 79', 'Stronghold Confessor': '(DAR) 105', 'Bloodstone Goblin': '(DAR) 115',
              'Keldon Warcaller': '(DAR) 136', 'Skizzik': '(DAR) 145', 'Adventurous Impulse': '(DAR) 153',
              'Baloth Gorger': '(DAR) 156', 'Corrosive Ooze': '(DAR) 158', 'Llanowar Envoy': '(DAR) 169',
              'Howling Golem': '(DAR) 218', "Navigator's Compass": '(DAR) 225', 'Pardic Wanderer': '(DAR) 226',
              'Short Sword': '(DAR) 229', 'Blessed Light': '(DAR) 7', 'Homarid Explorer': '(DAR) 53',
              'Sage of Lat-Nam': '(DAR) 64', 'Sentinel of the Pearl Trident': '(DAR) 65', 'Cabal Evangel': '(DAR) 78',
              'Lingering Phantom': '(DAR) 99', 'Windgrace Acolyte': '(DAR) 112', 'Goblin Barrage': '(DAR) 128',
              'Shivan Fire': '(DAR) 142', 'Saproling Migration': '(DAR) 178', 'Jousting Lance': '(DAR) 221',
              'Pyromantic Pilgrim': '(DAR) 278', "Gideon's Reproach": '(DAR) 19', 'Knight of New Benalia': '(DAR) 24',
              'Deep Freeze': '(DAR) 50', 'Diligent Excavator': '(DAR) 51', 'Syncopate': '(DAR) 67',
              'Vodalian Arcanist': '(DAR) 73', 'Weight of Memory': '(DAR) 74', 'Caligo Skin-Witch': '(DAR) 80',
              'Dark Bargain': '(DAR) 83', 'Deathbloom Thallid': '(DAR) 84', 'Fungal Infection': '(DAR) 94',
              'Thallid Omnivore': '(DAR) 106', 'Yargle, Glutton of Urborg': '(DAR) 113', 'Firefist Adept': '(DAR) 121',
              'Frenzied Rage': '(DAR) 124', "Nature's Spiral": '(DAR) 175', "Mishra's Self-Replicator": '(DAR) 223',
              'Voltaic Servant': '(DAR) 236', 'Timber Gorge': '(DAR) 279', 'Call the Cavalry': '(DAR) 9',
              'Dub': '(DAR) 15', 'Serra Angel': '(DAR) 33', 'Triumph of Gerrard': '(DAR) 38',
              'Fervent Strike': '(DAR) 117', 'Ghitu Journeymage': '(DAR) 126', 'Haphazard Bombardment': '(DAR) 131',
              'Keldon Overseer': '(DAR) 134', 'Radiating Lightning': '(DAR) 138', 'Warcry Phoenix': '(DAR) 150',
              'Krosan Druid': '(DAR) 167', 'Wild Onslaught': '(DAR) 188', 'Shield of the Realm': '(DAR) 228',
              "Urza's Tome": '(DAR) 235', 'Memorial to Glory': '(DAR) 244', "Teferi's Sentinel": '(DAR) 273',
              'Meandering River': '(DAR) 274', 'Daring Archaeologist': '(DAR) 13', 'Healing Grace': '(DAR) 20',
              'Time of Ice': '(DAR) 70', 'Divest': '(DAR) 87', 'Eviscerate': '(DAR) 91',
              'Vicious Offering': '(DAR) 110', 'Orcish Vandal': '(DAR) 137', 'Seismic Shift': '(DAR) 141',
              'Grunn, the Lonely King': '(DAR) 165', 'Thorn Elemental': '(DAR) 185', "Sorcerer's Wand": '(DAR) 231',
              'Benalish Honor Guard': '(DAR) 5', 'Thallid Soothsayer': '(DAR) 107', 'Elfhame Druid': '(DAR) 159',
              "Gaea's Blessing": '(DAR) 161', 'Gift of Growth': '(DAR) 163', 'Verdant Force': '(DAR) 187',
              'Yavimaya Sapherd': '(DAR) 189', 'Rona, Disciple of Gix': '(DAR) 203',
              "Tiana, Ship's Caretaker": '(DAR) 208', 'Icy Manipulator': '(DAR) 219', 'Powerstone Shard': '(DAR) 227',
              'Memorial to Unity': '(DAR) 245', 'Memorial to War': '(DAR) 246', 'Temporal Machinations': '(DAR) 271',
              'Kwende, Pride of Femeref': '(DAR) 25', "Curator's Ward": '(DAR) 49', 'Blessing of Belzenlok': '(DAR) 77',
              "Chainer's Torment": '(DAR) 82', 'Champion of the Flame': '(DAR) 116', 'The First Eruption': '(DAR) 122',
              'Ghitu Chronicler': '(DAR) 125', 'Run Amok': '(DAR) 140', 'Untamed Kavu': '(DAR) 186',
              "Shanna, Sisay's Legacy": '(DAR) 204', 'Adamant Will': '(DAR) 2', 'Board the Weatherlight': '(DAR) 8',
              'Evra, Halcyon Witness': '(DAR) 16', "On Serra's Wings": '(DAR) 28', "In Bolas's Clutches": '(DAR) 54',
              'Demonic Vigor': '(DAR) 85', 'Fight with Fire': '(DAR) 119', 'Skirk Prospector': '(DAR) 144',
              'Two-Headed Giant': '(DAR) 147', 'Ancient Animus': '(DAR) 154', 'Llanowar Elves': '(DAR) 168',
              'Hallar, the Firefletcher': '(DAR) 196', 'Karplusan Hound': '(DAR) 277', 'Settle the Score': '(DAR) 103',
              'Ghitu Lavarunner': '(DAR) 127', 'Grow from the Ashes': '(DAR) 164', 'Spore Swarm': '(DAR) 180',
              'Zhalfirin Void': '(DAR) 249', 'Baird, Steward of Argive': '(DAR) 4', "Artificer's Assistant": '(DAR) 44',
              'Blink of an Eye': '(DAR) 46', 'Unwind': '(DAR) 72', 'Knight of Malice': '(DAR) 97',
              'Garna, the Bloodflame': '(DAR) 194', 'Amaranthine Wall': '(DAR) 210', 'Skittering Surveyor': '(DAR) 230',
              'Memorial to Folly': '(DAR) 242', 'Memorial to Genius': '(DAR) 243',
              'Slinn Voda, the Rising Deep': '(DAR) 66', 'Final Parting': '(DAR) 93',
              'Urgoros, the Empty One': '(DAR) 109', 'Whisper, Blood Liturgist': '(DAR) 111',
              'Valduk, Keeper of the Flame': '(DAR) 148', 'Llanowar Scout': '(DAR) 170',
              'Sporecrown Thallid': '(DAR) 181', "Raff Capashen, Ship's Mage": '(DAR) 202',
              'Slimefoot, the Stowaway': '(DAR) 205', 'Knight of Grace': '(DAR) 23',
              'Zahid, Djinn of the Lamp': '(DAR) 76', "Jhoira's Familiar": '(DAR) 220',
              'Niambi, Faithful Healer': '(DAR) 272', 'Dauntless Bodyguard': '(DAR) 14',
              'Fall of the Thran': '(DAR) 18', 'Precognition Field': '(DAR) 61', "Warlord's Fury": '(DAR) 151',
              'Fungal Plots': '(DAR) 160', 'Kazarov, Sengir Pureblood': '(DAR) 96', "Kamahl's Druidic Vow": '(DAR) 166',
              'Adeliz, the Cinder Wind': '(DAR) 190', 'Arvad the Cursed': '(DAR) 191',
              'Naban, Dean of Iteration': '(DAR) 58', "Lich's Mastery": '(DAR) 98', 'Rite of Belzenlok': '(DAR) 102',
              'Torgaar, Famine Incarnate': '(DAR) 108', 'Goblin Warchief': '(DAR) 130',
              'Territorial Allosaurus': '(DAR) 184', 'Tatyova, Benthic Druid': '(DAR) 206',
              "Chandra's Outburst": '(DAR) 276', 'Seal Away': '(DAR) 31', 'The Mirari Conjecture': '(DAR) 57',
              'Cast Down': '(DAR) 81', 'Broken Bond': '(DAR) 157', 'Grand Warlord Radha': '(DAR) 195',
              'Danitha Capashen, Paragon': '(DAR) 12', 'Dread Shade': '(DAR) 88',
              "Jaya's Immolating Inferno": '(DAR) 133', "Wizard's Lightning": '(DAR) 152',
              'Jodah, Archmage Eternal': '(DAR) 198', "Forebear's Blade": '(DAR) 214',
              "Teshar, Ancestor's Apostle": '(DAR) 36', 'Tetsuko Umezawa, Fugitive': '(DAR) 69',
              "Yawgmoth's Vile Offering": '(DAR) 114', 'The Flame of Keld': '(DAR) 123',
              'Aryel, Knight of Windgrace': '(DAR) 192', "Primevals' Glorious Rebirth": '(DAR) 201',
              'Rat Colony': '(DAR) 101', 'Squee, the Immortal': '(DAR) 146', 'Traxos, Scourge of Kroog': '(DAR) 234',
              'The Antiquities War': '(DAR) 42', 'Song of Freyalise': '(DAR) 179', 'Benalish Marshal': '(DAR) 6',
              "Karn's Temporal Sundering": '(DAR) 55', 'The Eldest Reborn': '(DAR) 90',
              'Marwyn, the Nurturer': '(DAR) 172', 'Josu Vess, Lich Knight': '(DAR) 95', "Wizard's Retort": '(DAR) 75',
              'Sylvan Awakening': '(DAR) 183', "Urza's Ruinous Blast": '(DAR) 39',
              'Thran Temporal Gateway': '(DAR) 233', 'Siege-Gang Commander': '(DAR) 143',
              'Blackblade Reforged': '(DAR) 211', 'Oath of Teferi': '(DAR) 200', 'Goblin Chainwhirler': '(DAR) 129',
              'Naru Meha, Master Wizard': '(DAR) 59', 'Darigaaz Reincarnated': '(DAR) 193', 'Tempest Djinn': '(DAR) 68',
              'Weatherlight': '(DAR) 237', 'Merfolk Trickster': '(DAR) 56', 'Demonlord Belzenlok': '(DAR) 86',
              'Cabal Stronghold': '(DAR) 238', 'Verix Bladewing': '(DAR) 149', 'Steel Leaf Champion': '(DAR) 182',
              'Phyrexian Scriptures': '(DAR) 100', 'Jaya Ballard': '(DAR) 132',
              'Jhoira, Weatherlight Captain': '(DAR) 197', 'Damping Sphere': '(DAR) 213',
              "Multani, Yavimaya's Avatar": '(DAR) 174', 'Shalai, Voice of Plenty': '(DAR) 35',
              'Gilded Lotus': '(DAR) 215', 'Woodland Cemetery': '(DAR) 248', 'History of Benalia': '(DAR) 21',
              'Sulfur Falls': '(DAR) 247', 'Clifftop Retreat': '(DAR) 239', 'Isolated Chapel': '(DAR) 241',
              'Teferi, Timebender': '(DAR) 270', 'Muldrotha, the Gravetide': '(DAR) 199',
              'Helm of the Host': '(DAR) 217', 'Chandra, Bold Pyromancer': '(DAR) 275',
              'Hinterland Harbor': '(DAR) 240', 'Lyra Dawnbringer': '(DAR) 26', 'Karn, Scion of Urza': '(DAR) 1',
              'Mox Amber': '(DAR) 224', 'Teferi, Hero of (DAR)': '(DAR) 207', 'The Mending of (DAR)': '(DAR) 173',
              'Firesong and Sunspeaker': '(DAR) 280', 'Acclaimed Contender': '(ELD) 1', 'All That Glitters': '(ELD) 2',
              'Archon of Absolution': '(ELD) 3', 'Ardenvale Paladin': '(ELD) 4', 'Ardenvale Tactician': '(ELD) 5',
              'Dizzying Swoop': '(ELD) 5', 'Bartered Cow': '(ELD) 6', 'Beloved Princess': '(ELD) 7',
              'Charming Prince': '(ELD) 8', 'The Circle of Loyalty': '(ELD) 9', 'Deafening Silence': '(ELD) 10',
              'Faerie Guidemother': '(ELD) 11', 'Gift of the Fae': '(ELD) 11', 'Flutterfox': '(ELD) 12',
              'Fortifying Provisions': '(ELD) 13', 'Giant Killer': '(ELD) 14', 'Chop Down': '(ELD) 14',
              'Glass Casket': '(ELD) 15', 'Happily Ever After': '(ELD) 16', 'Harmonious Archon': '(ELD) 17',
              'Hushbringer': '(ELD) 18', 'Knight of the Keep': '(ELD) 19', 'Linden, the Steadfast Queen': '(ELD) 20',
              'Lonesome Unicorn': '(ELD) 21', 'Rider in Need': '(ELD) 21', 'Mysterious Pathlighter': '(ELD) 22',
              'Outflank': '(ELD) 23', 'Prized Griffin': '(ELD) 24', 'Rally for the Throne': '(ELD) 25',
              'Realm-Cloaked Giant': '(ELD) 26', 'Cast Off': '(ELD) 26', 'Righteousness': '(ELD) 27',
              'Shepherd of the Flock': '(ELD) 28', 'Usher to Safety': '(ELD) 28', 'Shining Armor': '(ELD) 29',
              'Silverflame Ritual': '(ELD) 30', 'Silverflame Squire': '(ELD) 31', 'On Alert': '(ELD) 31',
              "Syr Alin, the Lion's Claw": '(ELD) 32', 'Trapped in the Tower': '(ELD) 33',
              "True Love's Kiss": '(ELD) 34', 'Venerable Knight': '(ELD) 35', 'Worthy Knight': '(ELD) 36',
              'Youthful Knight': '(ELD) 37', 'Animating Faerie': '(ELD) 38', 'Bring to Life': '(ELD) 38',
              'Brazen Borrower': '(ELD) 39', 'Petty Theft': '(ELD) 39', 'Charmed Sleep': '(ELD) 40',
              'Corridor Monitor': '(ELD) 41', "Didn't Say Please": '(ELD) 42', 'Emry, Lurker of the Loch': '(ELD) 43',
              'Fae of Wishes': '(ELD) 44', 'Granted': '(ELD) 44', 'Faerie Vandal': '(ELD) 45',
              'Folio of Fancies': '(ELD) 46', 'Frogify': '(ELD) 47', 'Gadwick, the Wizened': '(ELD) 48',
              'Hypnotic Sprite': '(ELD) 49', 'Mesmeric Glare': '(ELD) 49', 'Into the Story': '(ELD) 50',
              'The Magic Mirror': '(ELD) 51', 'Mantle of Tides': '(ELD) 52', 'Merfolk Secretkeeper': '(ELD) 53',
              'Venture Deeper': '(ELD) 53', 'Midnight Clock': '(ELD) 54', 'Mirrormade': '(ELD) 55',
              'Mistford River Turtle': '(ELD) 56', 'Moonlit Scavengers': '(ELD) 57', 'Mystical Dispute': '(ELD) 58',
              'Opt': '(ELD) 59', 'Overwhelmed Apprentice': '(ELD) 60', 'Queen of Ice': '(ELD) 61',
              'Rage of Winter': '(ELD) 61', 'Run Away Together': '(ELD) 62', 'Sage of the Falls': '(ELD) 63',
              'So Tiny': '(ELD) 64', 'Steelgaze Griffin': '(ELD) 65', 'Stolen by the Fae': '(ELD) 66',
              'Syr Elenora, the Discerning': '(ELD) 67', 'Tome Raider': '(ELD) 68', 'Turn into a Pumpkin': '(ELD) 69',
              'Unexplained Vision': '(ELD) 70', 'Vantress Gargoyle': '(ELD) 71', 'Vantress Paladin': '(ELD) 72',
              'Wishful Merfolk': '(ELD) 73', 'Witching Well': '(ELD) 74', 'Ayara, First of Locthwain': '(ELD) 75',
              'Bake into a Pie': '(ELD) 76', 'Barrow Witches': '(ELD) 77', 'Belle of the Brawl': '(ELD) 78',
              'Blacklance Paragon': '(ELD) 79', 'Bog Naughty': '(ELD) 80', 'Cauldron Familiar': '(ELD) 81',
              'The Cauldron of Eternity': '(ELD) 82', "Cauldron's Gift": '(ELD) 83', 'Clackbridge Troll': '(ELD) 84',
              'Epic Downfall': '(ELD) 85', 'Eye Collector': '(ELD) 86', 'Festive Funeral': '(ELD) 87',
              'Foreboding Fruit': '(ELD) 88', 'Forever Young': '(ELD) 89', 'Foulmire Knight': '(ELD) 90',
              'Profane Insight': '(ELD) 90', "Giant's Skewer": '(ELD) 91', 'Lash of Thorns': '(ELD) 92',
              'Locthwain Paladin': '(ELD) 93', 'Lost Legion': '(ELD) 94', 'Malevolent Noble': '(ELD) 95',
              'Memory Theft': '(ELD) 96', 'Murderous Rider': '(ELD) 97', 'Swift End': '(ELD) 97',
              'Oathsworn Knight': '(ELD) 98', 'Order of Midnight': '(ELD) 99', 'Alter Fate': '(ELD) 99',
              'Piper of the Swarm': '(ELD) 100', 'Rankle, Master of Pranks': '(ELD) 101',
              'Reaper of Night': '(ELD) 102', 'Harvest Fear': '(ELD) 102', 'Reave Soul': '(ELD) 103',
              'Revenge of Ravens': '(ELD) 104', 'Smitten Swordmaster': '(ELD) 105', 'Curry Favor': '(ELD) 105',
              "Specter's Shriek": '(ELD) 106', 'Syr Konrad, the Grim': '(ELD) 107', 'Tempting Witch': '(ELD) 108',
              'Wicked Guardian': '(ELD) 109', 'Wishclaw Talisman': '(ELD) 110', "Witch's Vengeance": '(ELD) 111',
              'Barge In': '(ELD) 112', 'Bloodhaze Wolverine': '(ELD) 113', 'Blow Your House Down': '(ELD) 114',
              'Bonecrusher Giant': '(ELD) 115', 'Stomp': '(ELD) 115', 'Brimstone Trebuchet': '(ELD) 116',
              'Burning-Yard Trainer': '(ELD) 117', 'Claim the Firstborn': '(ELD) 118', 'Crystal Slipper': '(ELD) 119',
              'Embercleave': '(ELD) 120', 'Embereth Paladin': '(ELD) 121', 'Embereth Shieldbreaker': '(ELD) 122',
              'Battle Display': '(ELD) 122', 'Ferocity of the Wilds': '(ELD) 123', 'Fervent Champion': '(ELD) 124',
              'Fires of Invention': '(ELD) 125', 'Fling': '(ELD) 126', 'Irencrag Feat': '(ELD) 127',
              'Irencrag Pyromancer': '(ELD) 128', 'Joust': '(ELD) 129', 'Mad Ratter': '(ELD) 130',
              'Merchant of the Vale': '(ELD) 131', 'Haggle': '(ELD) 131', 'Ogre Errant': '(ELD) 132',
              'Opportunistic Dragon': '(ELD) 133', 'Raging Redcap': '(ELD) 134', 'Redcap Melee': '(ELD) 135',
              'Redcap Raiders': '(ELD) 136', 'Rimrock Knight': '(ELD) 137', 'Boulder Rush': '(ELD) 137',
              'Robber of the Rich': '(ELD) 138', 'Scorching Dragonfire': '(ELD) 139', 'Searing Barrage': '(ELD) 140',
              'Seven Dwarves': '(ELD) 141', 'Skullknocker Ogre': '(ELD) 142', 'Slaying Fire': '(ELD) 143',
              'Sundering Stroke': '(ELD) 144', 'Syr Carah, the Bold': '(ELD) 145', 'Thrill of Possibility': '(ELD) 146',
              'Torbran, Thane of Red Fell': '(ELD) 147', 'Weaselback Redcap': '(ELD) 148',
              'Beanstalk Giant': '(ELD) 149', 'Fertile Footsteps': '(ELD) 149', 'Curious Pair': '(ELD) 150',
              'Treats to Share': '(ELD) 150', 'Edgewall Innkeeper': '(ELD) 151', 'Feasting Troll King': '(ELD) 152',
              'Fell the Pheasant': '(ELD) 153', 'Fierce Witchstalker': '(ELD) 154', 'Flaxen Intruder': '(ELD) 155',
              'Welcome Home': '(ELD) 155', 'Garenbrig Carver': '(ELD) 156', "Shield's Might": '(ELD) 156',
              'Garenbrig Paladin': '(ELD) 157', 'Garenbrig Squire': '(ELD) 158', 'Giant Opportunity': '(ELD) 159',
              'Gilded Goose': '(ELD) 160', 'The Great Henge': '(ELD) 161', 'Insatiable Appetite': '(ELD) 162',
              'Keeper of Fables': '(ELD) 163', "Kenrith's Transformation": '(ELD) 164', 'Lovestruck Beast': '(ELD) 165',
              "Heart's Desire": '(ELD) 165', 'Maraleaf Rider': '(ELD) 166', 'Oakhame Adversary': '(ELD) 167',
              'Once and Future': '(ELD) 168', 'Once Upon a Time': '(ELD) 169', 'Outmuscle': '(ELD) 170',
              'Questing Beast': '(ELD) 171', 'Return of the Wildspeaker': '(ELD) 172', 'Return to Nature': '(ELD) 173',
              'Rosethorn Acolyte': '(ELD) 174', 'Seasonal Ritual': '(ELD) 174', 'Rosethorn Halberd': '(ELD) 175',
              'Sporecap Spider': '(ELD) 176', 'Syr Faren, the Hengehammer': '(ELD) 177',
              'Tall as a Beanstalk': '(ELD) 178', 'Trail of Crumbs': '(ELD) 179', 'Tuinvale Treefolk': '(ELD) 180',
              'Oaken Boon': '(ELD) 180', 'Wicked Wolf': '(ELD) 181', 'Wildborn Preserver': '(ELD) 182',
              'Wildwood Tracker': '(ELD) 183', "Wolf's Quarry": '(ELD) 184', 'Yorvo, Lord of Garenbrig': '(ELD) 185',
              'Dance of the Manse': '(ELD) 186', 'Doom Foretold': '(ELD) 187', 'Drown in the Loch': '(ELD) 188',
              'Escape to the Wilds': '(ELD) 189', 'Faeburrow Elder': '(ELD) 190',
              'Garruk, Cursed Huntsman': '(ELD) 191', 'Grumgully, the Generous': '(ELD) 192',
              'Improbable Alliance': '(ELD) 193', 'Inspiring Veteran': '(ELD) 194', 'Lochmere Serpent': '(ELD) 195',
              'Maraleaf Pixie': '(ELD) 196', 'Oko, Thief of Crowns': '(ELD) 197', "Outlaws' Merriment": '(ELD) 198',
              'The Royal Scions': '(ELD) 199', 'Savvy Hunter': '(ELD) 200', 'Shinechaser': '(ELD) 201',
              'Steelclaw Lance': '(ELD) 202', 'Stormfist Crusader': '(ELD) 203', 'Wandermare': '(ELD) 204',
              'Wintermoor Commander': '(ELD) 205', "Arcanist's Owl": '(ELD) 206', 'Covetous Urge': '(ELD) 207',
              'Deathless Knight': '(ELD) 208', 'Elite Headhunter': '(ELD) 209', 'Fireborn Knight': '(ELD) 210',
              'Loch Dragon': '(ELD) 211', 'Oakhame Ranger': '(ELD) 212', 'Bring Back': '(ELD) 212',
              'Rampart Smasher': '(ELD) 213', 'Resolute Rider': '(ELD) 214', 'Thunderous Snapper': '(ELD) 215',
              'Clockwork Servant': '(ELD) 216', 'Crashing Drawbridge': '(ELD) 217', 'Enchanted Carriage': '(ELD) 218',
              'Gingerbrute': '(ELD) 219', 'Golden Egg': '(ELD) 220', 'Henge Walker': '(ELD) 221',
              'Heraldic Banner': '(ELD) 222', 'Inquisitive Puppet': '(ELD) 223', 'Jousting Dummy': '(ELD) 224',
              'Locthwain Gargoyle': '(ELD) 225', 'Lucky Clover': '(ELD) 226', 'Prophet of the Peak': '(ELD) 227',
              'Roving Keep': '(ELD) 228', 'Scalding Cauldron': '(ELD) 229', 'Shambling Suit': '(ELD) 230',
              'Signpost Scarecrow': '(ELD) 231', "Sorcerer's Broom": '(ELD) 232', 'Sorcerous Spyglass': '(ELD) 233',
              'Spinning Wheel': '(ELD) 234', 'Stonecoil Serpent': '(ELD) 235', 'Weapon Rack': '(ELD) 236',
              "Witch's Oven": '(ELD) 237', 'Castle Ardenvale': '(ELD) 238', 'Castle Embereth': '(ELD) 239',
              'Castle Garenbrig': '(ELD) 240', 'Castle Locthwain': '(ELD) 241', 'Castle Vantress': '(ELD) 242',
              'Dwarven Mine': '(ELD) 243', 'Fabled Passage': '(ELD) 244', 'Gingerbread Cabin': '(ELD) 245',
              'Idyllic Grange': '(ELD) 246', 'Mystic Sanctuary': '(ELD) 247', 'Tournament Grounds': '(ELD) 248',
              "Witch's Cottage": '(ELD) 249', 'Kenrith, the Returned King': '(ELD) 303',
              'Rowan, Fearless Sparkmage': '(ELD) 304', 'Garrison Griffin': '(ELD) 305',
              "Rowan's Battleguard": '(ELD) 306', "Rowan's Stalwarts": '(ELD) 307', 'Oko, the Trickster': '(ELD) 309',
              "Oko's Accomplices": '(ELD) 310', 'Bramblefort Fink': '(ELD) 311', "Oko's Hospitality": '(ELD) 312',
              'Mace of the Valiant': '(ELD) 314', 'Silverwing Squadron': '(ELD) 315', 'Faerie Formation': '(ELD) 316',
              'Shimmer Dragon': '(ELD) 317', 'Workshop Elders': '(ELD) 318', 'Chittering Witch': '(ELD) 319',
              'Taste of Death': '(ELD) 320', 'Embereth Skyblazer': '(ELD) 321', 'Steelbane Hydra': '(ELD) 322',
              'Thorn Mammoth': '(ELD) 323', 'Alela, Artful Provocateur': '(ELD) 324', 'Banish into Fable': '(ELD) 325',
              'Chulane, Teller of Tales': '(ELD) 326', 'Gluttonous Troll': '(ELD) 327', "Knights' Charge": '(ELD) 328',
              'Korvold, Fae-Cursed King': '(ELD) 329', 'Syr Gwyn, Hero of Ashvale': '(ELD) 330',
              'Arcane Signet': '(ELD) 331', 'Tome of Legends': '(ELD) 332', 'Command Tower': '(ELD) 333',
              'Collar the Culprit': '(GRN) 5', 'Intrusive Packbeast': '(GRN) 17', 'Dazzling Lights': '(GRN) 34',
              'Wishcoin Crab': '(GRN) 60', 'Rubblebelt Boar': '(GRN) 114', 'Sure Strike': '(GRN) 118',
              'Devkarin Dissident': '(GRN) 127', 'Prey Upon': '(GRN) 143', 'Wild Ceratok': '(GRN) 150',
              'Garrison Sergeant': '(GRN) 172', 'Fresh-Faced Recruit': '(GRN) 216', 'Piston-Fist Cyclops': '(GRN) 217',
              'Blade Instructor': '(GRN) 1', 'Parhelion Patrol': '(GRN) 22', 'Roc Charger': '(GRN) 24',
              'Skyline Scout': '(GRN) 25', 'Child of Night': '(GRN) 65', 'Douser of Lights': '(GRN) 70',
              'Never Happened': '(GRN) 80', 'Barging Sergeant': '(GRN) 92', "Pack's Favor": '(GRN) 139',
              'Wary Okapi': '(GRN) 149', 'Hammer Dropper': '(GRN) 176', 'Rosemane Centaur': '(GRN) 197',
              'Sumala Woodshaper': '(GRN) 200', 'Inspiring Unicorn': '(GRN) 16', 'Ledev Guardian': '(GRN) 18',
              'Luminous Bonds': '(GRN) 21', 'Tenth District Guard': '(GRN) 29', 'Leapfrog': '(GRN) 42',
              'Vedalken Mesmerist': '(GRN) 57', 'Wall of Mist': '(GRN) 58', 'Watcher in the Mist': '(GRN) 59',
              'Spinal Centipede': '(GRN) 86', 'Command the Storm': '(GRN) 94', 'Goblin Locksmith': '(GRN) 104',
              'Ornery Goblin': '(GRN) 112', 'Wojek Bodyguard': '(GRN) 120', 'Portcullis Vine': '(GRN) 142',
              'Siege Wurm': '(GRN) 144', 'Vigorspore Wurm': '(GRN) 147', 'Centaur Peacemaker': '(GRN) 158',
              'Vernadi Shieldmate': '(GRN) 219', 'Flight of Equenauts': '(GRN) 11', 'Loxodon Restorer': '(GRN) 20',
              'Righteous Blow': '(GRN) 23', 'Capture Sphere': '(GRN) 31', 'Selective Snare': '(GRN) 53',
              'Deadly Visit': '(GRN) 68', 'Undercity Necrolisk': '(GRN) 87', 'Whispering Snitch': '(GRN) 90',
              'Cosmotronic Wave': '(GRN) 95', 'Fearless Halberdier': '(GRN) 100', 'Hellkite Whelp': '(GRN) 106',
              'Ironshell Beetle': '(GRN) 134', 'Artful Takedown': '(GRN) 151', 'Undercity Uprising': '(GRN) 210',
              'Pitiless Gorgon': '(GRN) 218', 'Rampaging Monument': '(GRN) 239', 'Gateway Plaza': '(GRN) 247',
              'Golgari Guildgate': '(GRN) 249', 'Candlelight Vigil': '(GRN) 3', 'Hunted Witness': '(GRN) 15',
              'Dimir Informant': '(GRN) 36', 'Disdainful Stroke': '(GRN) 37', 'Bartizan Bats': '(GRN) 62',
              'Severed Strands': '(GRN) 85', 'Fire Urchin': '(GRN) 101', 'Gravitic Punch': '(GRN) 105',
              'Torch Courier': '(GRN) 119', 'Hitchclaw Recluse': '(GRN) 133', 'Join Shields': '(GRN) 181',
              'Skyknight Legionnaire': '(GRN) 198', 'Wee Dragonauts': '(GRN) 214', 'Worldsoul Colossus': '(GRN) 215',
              'Invert': '(GRN) 228', 'Invent': '(GRN) 228', 'Selesnya Locket': '(GRN) 240',
              'Boros Guildgate': '(GRN) 243', 'Dimir Guildgate': '(GRN) 245', 'Selesnya Guildgate': '(GRN) 255',
              'Sunhome Stalwart': '(GRN) 26', 'Muse Drake': '(GRN) 46', 'Passwall Adept': '(GRN) 50',
              'Radical Idea': '(GRN) 52', 'Unexplained Disappearance': '(GRN) 56', 'Kraul Swarm': '(GRN) 73',
              'Veiled Shade': '(GRN) 88', 'Vicious Rumors': '(GRN) 89', 'Direct Current': '(GRN) 96',
              'Maximize Velocity': '(GRN) 111', 'Arboretum Elemental': '(GRN) 122', 'Pause for Reflection': '(GRN) 140',
              'Sprouting Renewal': '(GRN) 145', 'Beacon Bolt': '(GRN) 154', 'Conclave Cavalier': '(GRN) 161',
              'Conclave Guildmage': '(GRN) 162', 'Darkblade Agent': '(GRN) 164', 'Erstwhile Trooper': '(GRN) 169',
              'Goblin Electromancer': '(GRN) 174', 'Hypothesizzle': '(GRN) 178', 'Nightveil Predator': '(GRN) 191',
              'Swarm Guildmage': '(GRN) 201', 'Gatekeeper Gargoyle': '(GRN) 235', 'Izzet Guildgate': '(GRN) 251',
              'Sworn Companions': '(GRN) 27', 'Take Heart': '(GRN) 28', 'Citywatch Sphinx': '(GRN) 33',
              'Maximize Altitude': '(GRN) 43', 'Hired Poisoner': '(GRN) 72', 'Book Devourer': '(GRN) 93',
              'Inescapable Blaze': '(GRN) 107', 'Smelt-Ward Minotaur': '(GRN) 116', 'Affectionate Indrik': '(GRN) 121',
              'Generous Stray': '(GRN) 129', 'Golgari Raiders': '(GRN) 130', 'Kraul Foragers': '(GRN) 135',
              'Kraul Harpooner': '(GRN) 136', 'House Guildmage': '(GRN) 177', 'Whisper Agent': '(GRN) 220',
              'Dimir Locket': '(GRN) 234', 'Glaive of the Guildpact': '(GRN) 236', 'Golgari Locket': '(GRN) 237',
              'Demotion': '(GRN) 9', "Healer's Hawk": '(GRN) 14', 'Barrier of Bones': '(GRN) 61',
              'Burglar Rat': '(GRN) 64', 'Dead Weight': '(GRN) 67', 'Mephitic Vapors': '(GRN) 76',
              'Moodmark Painter': '(GRN) 78', 'Goblin Banneret': '(GRN) 102', 'Bounty of Might': '(GRN) 124',
              'District Guide': '(GRN) 128', 'Beamsplitter Mage': '(GRN) 155', 'League Guildmage': '(GRN) 185',
              'Ledev Champion': '(GRN) 186', 'Legion Guildmage': '(GRN) 187', 'Ochran Assassin': '(GRN) 194',
              'Sonic Assault': '(GRN) 199', 'Izzet Locket': '(GRN) 238', 'Gird for Battle': '(GRN) 12',
              'Enhanced Surveillance': '(GRN) 40', 'Nightveil Sprite': '(GRN) 48', 'Vivid Revival': '(GRN) 148',
              'Molderhulk': '(GRN) 190', 'Boros Locket': '(GRN) 231', 'Chamber Sentry': '(GRN) 232',
              'Silent Dart': '(GRN) 241', 'Haazda Marshal': '(GRN) 13', 'Devious Cover-Up': '(GRN) 35',
              'Street Riot': '(GRN) 117', 'Hatchery Spider': '(GRN) 132', 'Camaraderie': '(GRN) 157',
              'Dimir Spybug': '(GRN) 166', 'Rhizome Lurcher': '(GRN) 196', 'Swathcutter Giant': '(GRN) 202',
              'Flower // Flourish': '(GRN) 226', 'Flourish': '(GRN) 226', 'Wand of Vertebrae': '(GRN) 242',
              'Blood Operative': '(GRN) 63', 'Lotleth Giant': '(GRN) 74', 'Glowspore Shaman': '(GRN) 173',
              'Truefire Captain': '(GRN) 209', 'Integrity // Intervention': '(GRN) 227', 'Intervention': '(GRN) 227',
              'Crush Contraband': '(GRN) 7', 'Murmuring Mystic': '(GRN) 45', 'Omnispell Adept': '(GRN) 49',
              'Thoughtbound Phantasm': '(GRN) 55', 'Necrotic Wound': '(GRN) 79', 'Pilfering Imp': '(GRN) 81',
              'Erratic Cyclops': '(GRN) 98', 'Grappling Sundew': '(GRN) 131', 'Urban Utopia': '(GRN) 146',
              'Boros Challenger': '(GRN) 156', 'Golgari Findbroker': '(GRN) 175', 'Light of the Legion': '(GRN) 19',
              'Price of Fame': '(GRN) 83', 'Crackling Drake': '(GRN) 163', 'Notion Rain': '(GRN) 193',
              'Bounty Agent': '(GRN) 2', 'Conclave Tribunal': '(GRN) 6', 'Disinformation Campaign': '(GRN) 167',
              'Justice Strike': '(GRN) 182', 'Electrostatic Field': '(GRN) 97', 'Status': '(GRN) 230',
              'Status // Statue': '(GRN) 230', "Firemind's Research": '(GRN) 171', 'Assure': '(GRN) 221',
              'Assure // Assemble': '(GRN) 221', 'Citywide Bust': '(GRN) 4', 'Guild Summit': '(GRN) 41',
              'Charnel Troll': '(GRN) 160', 'Gruesome Menagerie': '(GRN) 71', 'Response': '(GRN) 229',
              'Response // Resurgence': '(GRN) 229', "Chemister's Insight": '(GRN) 32',
              'Goblin Cratermaker': '(GRN) 103', 'Connive': '(GRN) 222', 'Connive // Concoct': '(GRN) 222',
              "Guildmages' Forum": '(GRN) 250', 'Find': '(GRN) 225', 'Find // Finality': '(GRN) 225',
              'Drowned Secrets': '(GRN) 39', 'Plaguecrafter': '(GRN) 82', 'Creeping Chill': '(GRN) 66',
              'Etrata, the Silencer': '(GRN) 170', 'Circuitous Route': '(GRN) 125',
              'Emmara, Soul of the Accord': '(GRN) 168', 'Narcomoeba': '(GRN) 47', 'Sinister Sabotage': '(GRN) 54',
              'Quasiduplicate': '(GRN) 51', 'Lava Coil': '(GRN) 108', 'Izoni, Thousand-Eyed': '(GRN) 180',
              'Swiftblade Vindicator': '(GRN) 203', 'Mausoleum Secrets': '(GRN) 75', 'Thought Erasure': '(GRN) 206',
              'Discovery': '(GRN) 223', 'Discovery // Dispersal': '(GRN) 223', "Tajic, Legion's Edge": '(GRN) 204',
              'Venerated Loxodon': '(GRN) 30', 'Dawn of Hope': '(GRN) 8', 'Mnemonic Betrayal': '(GRN) 189',
              'Ritual of Soot': '(GRN) 84', 'Runaway Steam-Kin': '(GRN) 115', 'Ionize': '(GRN) 179',
              'Chance for Glory': '(GRN) 159', 'Deafening Clarion': '(GRN) 165', 'Unmoored Ego': '(GRN) 212',
              'Mission Briefing': '(GRN) 44', 'Dream Eater': '(GRN) 38', 'Niv-Mizzet, Parun': '(GRN) 192',
              'Experimental Frenzy': '(GRN) 99', 'Pelt Collector': '(GRN) 141', 'Lazav, the Multifarious': '(GRN) 184',
              'Expansion': '(GRN) 224', 'Expansion // Explosion': '(GRN) 224', 'Trostani Discordant': '(GRN) 208',
              'Underrealm Lich': '(GRN) 211', 'Midnight Reaper': '(GRN) 77', 'Beast Whisperer': '(GRN) 123',
              'Nullhide Ferox': '(GRN) 138', 'Thousand-Year Storm': '(GRN) 207', 'Risk Factor': '(GRN) 113',
              'Thief of Sanity': '(GRN) 205', 'March of the Multitudes': '(GRN) 188', 'Ral, Izzet Viceroy': '(GRN) 195',
              'Aurelia, Exemplar of Justice': '(GRN) 153', 'Knight of Autumn': '(GRN) 183',
              'Legion Warboss': '(GRN) 109', 'Chromatic Lantern': '(GRN) 233', 'Doom Whisperer': '(GRN) 69',
              'Divine Visitation': '(GRN) 10', 'Vraska, Golgari Queen': '(GRN) 213', 'Overgrown Tomb': '(GRN) 253',
              'Temple Garden': '(GRN) 258', 'Sacred Foundry': '(GRN) 254', 'Arclight Phoenix': '(GRN) 91',
              'Steam Vents': '(GRN) 257', 'Watery Grave': '(GRN) 259', "Assassin's Trophy": '(GRN) 152',
              'Ral, Caller of Storms': '(GRN) 265', "Ral's Dispersal": '(GRN) 266', 'Precision Bolt': '(GRN) 267',
              "Ral's Staticaster": '(GRN) 268', 'Vraska, Regal Gorgon': '(GRN) 269', 'Kraul Raider': '(GRN) 270',
              'Attendant of Vraska': '(GRN) 271', "Vraska's Stoneglare": '(GRN) 272',
              'Impervious Greatwurm': '(GRN) 273', 'Loxodon Line Breaker': '(M19) 24', 'Star-Crowned Stag': '(M19) 38',
              'Bone to Ash': '(M19) 47', 'Dwindle': '(M19) 53', 'Uncomfortable Chill': '(M19) 82',
              'Mind Rot': '(M19) 109', 'Boggart Brute': '(M19) 131', 'Hostile Minotaur': '(M19) 147',
              'Lava Axe': '(M19) 150', 'Tectonic Rift': '(M19) 162', 'Daggerback Basilisk': '(M19) 174',
              'Oakenform': '(M19) 191', 'Herald of Faith': '(M19) 13', 'Knightly Valor': '(M19) 20',
              'Trusty Packbeast': '(M19) 41', 'Gearsmith Prodigy': '(M19) 57', 'Scholar of Stars': '(M19) 71',
              'Bogstomper': '(M19) 87', 'Gravedigger': '(M19) 98', 'Hired Blade': '(M19) 100',
              "Lich's Caress": '(M19) 105', 'Bristling Boar': '(M19) 170', 'Declare Dominance': '(M19) 175',
              'Ghirapur Guide': '(M19) 182', 'Giant Spider': '(M19) 183', 'Plummet': '(M19) 193',
              'Wall of Vines': '(M19) 210', 'Psychic Symbiont': '(M19) 221', 'Gallant Cavalry': '(M19) 12',
              'Invoke the Divine': '(M19) 16', 'Knight of the Tusk': '(M19) 18', 'Cancel': '(M19) 48',
              'Skilled Animator': '(M19) 73', 'Snapping Drake': '(M19) 75', 'Switcheroo': '(M19) 78',
              'Infernal Scarring': '(M19) 103', 'Skymarch Bloodletter': '(M19) 119', 'Two-Headed Zombie': '(M19) 123',
              'Walking Corpse': '(M19) 126', 'Onakke Ogre': '(M19) 153', 'Siegebreaker Giant': '(M19) 157',
              'Trumpet Blast': '(M19) 165', 'Rhox Oracle': '(M19) 198', 'Aerial Engineer': '(M19) 211',
              'Explosive Apparatus': '(M19) 233', 'Gargoyle Sentinel': '(M19) 236', 'Gearsmith Guardian': '(M19) 237',
              'Angel of the Dawn': '(M19) 7', 'Cavalry Drillmaster': '(M19) 8', "Knight's Pledge": '(M19) 19',
              'Mighty Leap': '(M19) 28', 'Oreskos Swiftclaw': '(M19) 31', 'Revitalize': '(M19) 35',
              'Mystic Archaeologist': '(M19) 63', 'Sift': '(M19) 72', 'Plague Mare': '(M19) 114',
              'Rise from the Grave': '(M19) 117', 'Strangling Spores': '(M19) 122', 'Electrify': '(M19) 139',
              'Fiery Finish': '(M19) 140', 'Havoc Devils': '(M19) 146', 'Inferno Hellion': '(M19) 148',
              'Sparktongue Dragon': '(M19) 159', 'Highland Game': '(M19) 188', 'Naturalize': '(M19) 190',
              'Recollect': '(M19) 197', 'Thornhide Wolves': '(M19) 204', 'Skyrider Patrol': '(M19) 224',
              'Dwarven Priest': '(M19) 11', 'Rustwing Falcon': '(M19) 36', 'Aviation Pioneer': '(M19) 46',
              'Horizon Scholar': '(M19) 59', 'Omenspeaker': '(M19) 64', 'Doomed Dissenter': '(M19) 93',
              'Ravenous Harpy': '(M19) 115', 'Skeleton Archer': '(M19) 118', "Sovereign's Bite": '(M19) 120',
              'Dragon Egg': '(M19) 138', 'Druid of Horns': '(M19) 176', 'Titanic Growth': '(M19) 205',
              'Brawl-Bash Ogre': '(M19) 213', 'Manalith': '(M19) 239', 'Isolate': '(M19) 17',
              'Take Vengeance': '(M19) 40', 'Ghostform': '(M19) 58', 'Infectious Horror': '(M19) 101',
              'Vampire Sovereign': '(M19) 125', 'Lightning Mare': '(M19) 151', 'Smelt': '(M19) 158',
              'Viashino Pyromancer': '(M19) 166', 'Volcanic Dragon': '(M19) 167', 'Blanchwood Armor': '(M19) 169',
              'Vigilant Baloth': '(M19) 206', 'Arcane Encyclopedia': '(M19) 227', 'Field Creeper': '(M19) 234',
              'Millstone': '(M19) 242', 'Foul Orchard': '(M19) 251', 'Tranquil Expanse': '(M19) 259',
              'Shield Mare': '(M19) 37', 'Abnormal Endurance': '(M19) 85', 'Catalyst Elemental': '(M19) 132',
              'Goblin Motivator': '(M19) 143', 'Gift of Paradise': '(M19) 184', 'Prodigious Growth': '(M19) 194',
              'Rupture Spire': '(M19) 255', 'Gravewaker': '(M19) 293', 'Novice Knight': '(M19) 30',
              'Aven Wind Mage': '(M19) 45', 'Disperse': '(M19) 50', 'Essence Scatter': '(M19) 54',
              'Salvager of Secrets': '(M19) 70', 'Blood Divination': '(M19) 86', 'Vampire Neonate': '(M19) 124',
              'Druid of the Cowl': '(M19) 177', 'Ghastbark Twins': '(M19) 181', "Vivien's Invocation": '(M19) 209',
              'Meteor Golem': '(M19) 241', 'Suspicious Bookcase': '(M19) 246', 'Submerged Boneyard': '(M19) 257',
              'Aethershield Artificer': '(M19) 2', "Ajani's Last Stand": '(M19) 4', "Hieromancer's Cage": '(M19) 14',
              'Make a Stand': '(M19) 26', 'Aether Tunnel': '(M19) 43', 'Diregraf Ghoul': '(M19) 92',
              'Macabre Waltz': '(M19) 108', 'Crash Through': '(M19) 133', 'Dryad Greenseeker': '(M19) 178',
              'Elvish Rejuvenator': '(M19) 180', 'Talons of Wildwood': '(M19) 202', 'Regal Bloodlord': '(M19) 222',
              'Djinn of Wishes': '(M19) 52', 'Volley Veteran': '(M19) 168', 'Draconic Disciple': '(M19) 215',
              "Rogue's Gloves": '(M19) 243', 'Skyscanner': '(M19) 245', 'Transmogrifying Wand': '(M19) 247',
              'Departed Deckhand': '(M19) 49', 'Surge Mare': '(M19) 77', 'Fell Specter': '(M19) 96',
              "Nightmare's Thirst": '(M19) 111', 'Reassembling Skeleton': '(M19) 116', 'Colossal Majesty': '(M19) 173',
              'Pelakka Wurm': '(M19) 192', 'Diamond Mare': '(M19) 231', 'Pendulum of Patterns': '(M19) 288',
              'Ursine Champion': '(M19) 304', 'Goblin Instigator': '(M19) 142', 'Heroic Reinforcements': '(M19) 217',
              'Suncleanser': '(M19) 39', 'Windreader Sphinx': '(M19) 84', 'Dismissive Pyromancer': '(M19) 136',
              'Tormenting Voice': '(M19) 164', 'Lena, Selfless Champion': '(M19) 21', 'Leonin Vanguard': '(M19) 22',
              'Doublecast': '(M19) 137', 'Vine Mare': '(M19) 207', 'Enigma Drake': '(M19) 216',
              "Vivien's Jaguar": '(M19) 305', 'Mirror Image': '(M19) 61', 'Sleep': '(M19) 74',
              'Fraying Omnipotence': '(M19) 97', 'Guttersnipe': '(M19) 145', 'Thud': '(M19) 163',
              'Amulet of Safekeeping': '(M19) 226', 'Aegis of the Heavens': '(M19) 1', 'Phylactery Lich': '(M19) 113',
              'Militia Bugler': '(M19) 29', 'One with the Machine': '(M19) 66', 'Exclusion Mage': '(M19) 55',
              'Metamorphic Alteration': '(M19) 60', 'Satyr Enchanter': '(M19) 223', 'Silverbeak Griffin': '(M19) 285',
              'Arisen Gorgon': '(M19) 292', 'Shivan Dragon': '(M19) 300', 'Mistcaller': '(M19) 62',
              'Infernal Reckoning': '(M19) 102', 'Court Cleric': '(M19) 283', 'Riddlemaster Sphinx': '(M19) 287',
              "Tezzeret's Strider": '(M19) 290', "Liliana's Contract": '(M19) 107', 'Poison-Tip Archer': '(M19) 220',
              'Spit Flame': '(M19) 160', "Magistrate's Scepter": '(M19) 238', 'Sigiled Sword of Valeron': '(M19) 244',
              'Patient Rebuilding': '(M19) 67', 'Demon of Catastrophes': '(M19) 91', "Serra's Guardian": '(M19) 284',
              'Chaos Wand': '(M19) 228', 'Desecrated Tomb': '(M19) 230', "Liliana's Spoils": '(M19) 294',
              'Reclamation Sage': '(M19) 196', "Sarkhan's Dragonfire": '(M19) 298', 'Valiant Knight': '(M19) 42',
              'Dark-Dweller Oracle': '(M19) 134', 'Isareth the Awakener': '(M19) 104', 'Demanding Dragon': '(M19) 135',
              "Sarkhan's Whelp": '(M19) 299', 'Mentor of the Meek': '(M19) 27', 'Graveyard Marshal': '(M19) 99',
              'Kargan Dragonrider': '(M19) 297', 'Tattered Mummy': '(M19) 295', "Sarkhan's Unsealing": '(M19) 155',
              "Ajani's Influence": '(M19) 282', 'Open the Graves': '(M19) 112', 'Thorn Lieutenant': '(M19) 203',
              "Tezzeret's Gatebreaker": '(M19) 289', 'Skalla Wolf': '(M19) 303', 'Hungering Hydra': '(M19) 189',
              'Aggressive Mammoth': '(M19) 302', 'Remorseful Cleric': '(M19) 33', 'Apex of Power': '(M19) 129',
              'Fountain of Renewal': '(M19) 235', 'Detection Tower': '(M19) 249', 'Bone Dragon': '(M19) 88',
              'Runic Armasaur': '(M19) 200', 'Gigantosaurus': '(M19) 185', "Dragon's Hoard": '(M19) 232',
              'Psychic Corrosion': '(M19) 68', 'Goblin Trashmaster': '(M19) 144',
              'Palladia-Mors, the Ruiner': '(M19) 219', 'Banefire': '(M19) 130', 'Chromium, the Mutable': '(M19) 214',
              'Goreclaw, Terror of Qal Sisma': '(M19) 186', "Ajani's Welcome": '(M19) 6',
              'Vaevictis Asmadi, the Dire': '(M19) 225', 'Lathliss, Dragon Queen': '(M19) 149',
              'Supreme Phantom': '(M19) 76', 'Cleansing Nova': '(M19) 9', 'Leonin Warleader': '(M19) 23',
              'Reliquary Tower': '(M19) 254', 'Alpine Moon': '(M19) 128', "Stitcher's Supplier": '(M19) 121',
              'Elvish Clancaller': '(M19) 179', 'Sai, Master Thopterist': '(M19) 69', 'Death Baron': '(M19) 90',
              'Tezzeret, Cruel Machinist': '(M19) 286', 'Ajani, Adversary of Tyrants': '(M19) 3',
              'Liliana, Untouched by Death': '(M19) 106', 'Vivien Reid': '(M19) 208', 'Sarkhan, Fireblood': '(M19) 154',
              'Arcades, the Strategist': '(M19) 212', 'Tezzeret, Artifice Master': '(M19) 79',
              'Omniscience': '(M19) 65', 'Liliana, the Necromancer': '(M19) 291', 'Ajani, Wise Counselor': '(M19) 281',
              'Vivien of the Arkbow': '(M19) 301', 'Resplendent Angel': '(M19) 34', 'Sarkhan, Dragonsoul': '(M19) 296',
              'Nicol Bolas, the Ravager': '(M19) 218', 'Nicol Bolas, the Arisen': '(M19) 218',
              'Scapeshift': '(M19) 201', 'Crucible of Worlds': '(M19) 229', 'Nexus of Fate': '(M19) 306',
              'Angelic Gift': '(M20) 5', 'Daybreak Chaplain': '(M20) 12', 'Glaring Aegis': '(M20) 18',
              'Inspired Charge': '(M20) 24', 'Boreal Elemental': '(M20) 49', 'Fortress Crab': '(M20) 60',
              'Frilled Sea Serpent': '(M20) 61', 'Sleep Paralysis': '(M20) 75', "Yarok's Wavecrasher": '(M20) 81',
              'Thought Distortion': '(M20) 117', 'Maniacal Rage': '(M20) 149', 'Centaur Courser': '(M20) 168',
              'Greenwood Sentinel': '(M20) 174', 'Wolfkin Bond': '(M20) 203', "Diviner's Lockbox": '(M20) 225',
              "Marauder's Axe": '(M20) 231', 'Retributive Wand': '(M20) 236', 'Stone Golem': '(M20) 240',
              'Master Splicer': '(M20) 29', 'Moorland Inquisitor': '(M20) 31', 'Air Elemental': '(M20) 44',
              'Frost Lynx': '(M20) 62', 'Metropolis Sprite': '(M20) 66', 'Agonizing Syphon': '(M20) 83',
              'Feral Abomination': '(M20) 101', 'Undead Servant': '(M20) 118', 'Uncaged Fury': '(M20) 163',
              'Feral Invocation': '(M20) 170', 'Growth Cycle': '(M20) 175', 'Netcaster Spider': '(M20) 184',
              'Vorstclaw': '(M20) 201', 'Ogre Siegebreaker': '(M20) 215', 'Pattern Matcher': '(M20) 234',
              'Eternal Isolation': '(M20) 15', 'Griffin Sentinel': '(M20) 21', 'Moment of Heroism': '(M20) 30',
              'Soulmender': '(M20) 37', 'Captivating Gyre': '(M20) 51', 'Hard Cover': '(M20) 63',
              'Moat Piranhas': '(M20) 67', 'Audacious Thief': '(M20) 84', 'Boneclad Necromancer': '(M20) 93',
              'Vengeful Warchief': '(M20) 121', "Chandra's Outrage": '(M20) 130', 'Goblin Smuggler': '(M20) 144',
              'Infuriate': '(M20) 145', 'Pack Mastiff': '(M20) 152', 'Reduce to Ashes': '(M20) 155',
              'Unchained Berserker': '(M20) 164', 'Natural End': '(M20) 183', 'Rabid Bite': '(M20) 190',
              'Sedge Scorpion': '(M20) 192', 'Ironroot Warlord': '(M20) 209', 'Diamond Knight': '(M20) 224',
              'Swiftwater Cliffs': '(M20) 252', 'Aerial Assault': '(M20) 1', 'Squad Captain': '(M20) 38',
              'Steadfast Sentry': '(M20) 40', 'Convolute': '(M20) 55', 'Portal of Sanctuary': '(M20) 71',
              'Warden of Evos Isle': '(M20) 79', 'Barony Vampire': '(M20) 85', 'Bladebrand': '(M20) 86',
              'Blood Burglar': '(M20) 88', 'Bone Splinters': '(M20) 92', 'Gorging Vulture': '(M20) 102',
              'Soul Salvage': '(M20) 116', "Chandra's Embercat": '(M20) 129', 'Destructive Digger': '(M20) 134',
              'Reckless Air Strike': '(M20) 154', 'Scorch Spitter': '(M20) 159', 'Brightwood Tracker': '(M20) 166',
              'Heart-Piercer Bow': '(M20) 228', 'Vial of Dragonfire': '(M20) 241', 'Bloodfell Caves': '(M20) 242',
              'Fencing Ace': '(M20) 16', 'Gauntlets of Light': '(M20) 17', 'Octoprophet': '(M20) 70',
              'Zephyr Charge': '(M20) 82', 'Bloodsoaked Altar': '(M20) 90', 'Duress': '(M20) 97',
              'Epicure of Blood': '(M20) 99', 'Gruesome Scourger': '(M20) 104', 'Sanitarium Skeleton': '(M20) 112',
              'Daggersail Aeronaut': '(M20) 133', 'Dragon Mage': '(M20) 135', 'Goblin Bird-Grabber': '(M20) 142',
              'Rapacious Dragon': '(M20) 153', 'Ferocious Pup': '(M20) 171', 'Healer of the Glade': '(M20) 176',
              'Thicket Crasher': '(M20) 196', 'Salvager of Ruin': '(M20) 237', 'Blossoming Sands': '(M20) 243',
              'Wind-Scarred Crag': '(M20) 260', 'Ancestral Blade': '(M20) 3', 'Battalion Foot Soldier': '(M20) 7',
              'Griffin Protector': '(M20) 20', 'Inspiring Captain': '(M20) 25', 'Loyal Pegasus': '(M20) 28',
              'Pacifism': '(M20) 32', 'Yoked Ox': '(M20) 41', 'Anticipate': '(M20) 45', 'Cloudkin Seer': '(M20) 54',
              'Renowned Weaponsmith': '(M20) 72', "Sage's Row Denizen": '(M20) 73', 'Winged Words': '(M20) 80',
              'Blightbeetle': '(M20) 87', 'Disfigure': '(M20) 95', 'Sorcerer of the Fang': '(M20) 114',
              'Unholy Indenture': '(M20) 119', 'Ember Hauler': '(M20) 137', 'Lavakin Brawler': '(M20) 147',
              'Howling Giant': '(M20) 177', 'Might of the Masses': '(M20) 182', 'Overcome': '(M20) 186',
              'Anvilwrought Raptor': '(M20) 221', 'Jungle Hollow': '(M20) 248', 'Rugged Highlands': '(M20) 250',
              'Thornwood Falls': '(M20) 258', 'Tranquil Cove': '(M20) 259', 'Apostle of Purifying Light': '(M20) 6',
              'Dawning Angel': '(M20) 11', 'Disenchant': '(M20) 14', 'Herald of the Sun': '(M20) 23',
              'Raise the Alarm': '(M20) 34', 'Rule of Law': '(M20) 35', 'Scholar of the Ages': '(M20) 74',
              'Unsummon': '(M20) 78', 'Murder': '(M20) 109', 'Mask of Immolation': '(M20) 151', 'Shock': '(M20) 160',
              'Leafkin Druid': '(M20) 178', 'Silverback Shaman': '(M20) 195', "Wolfrider's Saddle": '(M20) 204',
              'Dismal Backwater': '(M20) 245', 'Faerie Miscreant': '(M20) 58', 'Overgrowth Elemental': '(M20) 187',
              'Pulse of Murasa': '(M20) 189', 'Woodland Champion': '(M20) 205', 'Scuttlemutt': '(M20) 238',
              'Scoured Barrens': '(M20) 251', 'Negate': '(M20) 69', "Chandra's Spitfire": '(M20) 132',
              'Scampering Scorcher': '(M20) 158', 'Loaming Shaman': '(M20) 180', 'Moldervine Reclamation': '(M20) 214',
              'Gods Willing': '(M20) 19', 'Aether Gust': '(M20) 42', 'Bloodthirsty Aerialist': '(M20) 91',
              "Yarok's Fenlurker": '(M20) 123', 'Flame Sweep': '(M20) 139', 'Ripscale Predator': '(M20) 157',
              'Barkhide Troll': '(M20) 165', 'Thrashing Brontodon': '(M20) 197', 'Creeping Trailblazer': '(M20) 207',
              'Skyknight Vanguard': '(M20) 218', 'Devout Decree': '(M20) 13', 'Loxodon Lifechanter': '(M20) 27',
              'Cerulean Drake': '(M20) 53', 'Dungeon Geists': '(M20) 57', 'Wakeroot Elemental': '(M20) 202',
              'Angel of Vitality': '(M20) 4', 'Atemsis, All-Seeing': '(M20) 46', 'Season of Growth': '(M20) 191',
              'Lightning Stormkin': '(M20) 213', 'Tomebound Lich': '(M20) 219', 'Blood for Bones': '(M20) 89',
              'Noxious Grasp': '(M20) 110', 'Corpse Knight': '(M20) 206', 'Masterful Replication': '(M20) 65',
              'Brineborn Cutthroat': '(M20) 50', 'Chandra, Novice Pyromancer': '(M20) 128',
              'Goblin Ringleader': '(M20) 143', 'Empyrean Eagle': '(M20) 208', 'Colossus Hammer': '(M20) 223',
              'Manifold Key': '(M20) 230', 'Vampire of the Dire Moon': '(M20) 120',
              'Repeated Reverberation': '(M20) 156', 'Planar Cleansing': '(M20) 33',
              'Glint-Horn Buccaneer': '(M20) 141', 'Cryptic Caves': '(M20) 244', "Chandra's Regulator": '(M20) 131',
              'Bag of Holding': '(M20) 222', 'Hanged Executioner': '(M20) 22', 'Shared Summons': '(M20) 193',
              'Starfield Mystic': '(M20) 39', 'Gargos, Vicious Watcher': '(M20) 172', 'Fry': '(M20) 140',
              'Leyline of Combustion': '(M20) 148', 'Bishop of Wings': '(M20) 8', 'Spectral Sailor': '(M20) 76',
              'Embodiment of Agonies': '(M20) 98', 'Flood of Tears': '(M20) 59', "Tale's End": '(M20) 77',
              'Drakuseth, Maw of Flames': '(M20) 136', 'Agent of Treachery': '(M20) 43',
              'Drawn from Dreams': '(M20) 56', 'Risen Reef': '(M20) 217', 'Marauding Raptor': '(M20) 150',
              'Brought Back': '(M20) 9', 'Golos, Tireless Pilgrim': '(M20) 226', "Legion's End": '(M20) 106',
              'Dread Presence': '(M20) 96', 'Leyline of Abundance': '(M20) 179', 'Thunderkin Awakener': '(M20) 162',
              'Voracious Hydra': '(M20) 200', "Sephara, Sky's Blade": '(M20) 36', 'Icon of Ancestry': '(M20) 229',
              'Temple of Triumph': '(M20) 257', "Grafdigger's Cage": '(M20) 227', 'Steel Overseer': '(M20) 239',
              'Temple of Silence': '(M20) 256', 'Temple of Malady': '(M20) 254', 'Temple of Epiphany': '(M20) 253',
              'Kaalia, Zenith Seeker': '(M20) 210', 'Temple of Mystery': '(M20) 255', 'Cavalier of Dawn': '(M20) 10',
              'Scheming Symmetry': '(M20) 113', 'Cavalier of Flame': '(M20) 125', 'Elvish Reclaimer': '(M20) 169',
              'Kethis, the Hidden Hand': '(M20) 211', 'Cavalier of Gales': '(M20) 52',
              'Vilis, Broker of Blood': '(M20) 122', 'Rotting Regisaur': '(M20) 111', "Kykar, Wind's Fury": '(M20) 212',
              'Field of the Dead': '(M20) 247', 'Shifting Ceratops': '(M20) 194', 'Veil of Summer': '(M20) 198',
              'Vivien, Arkbow Ranger': '(M20) 199', 'Mystic Forge': '(M20) 233', 'Nightpack Ambusher': '(M20) 185',
              'Leyline of Anticipation': '(M20) 64', 'Leyline of Sanctity': '(M20) 26', 'Cavalier of Night': '(M20) 94',
              'Ajani, Strength of the Pride': '(M20) 2', 'Knight of the Ebon Legion': '(M20) 105',
              'Lotus Field': '(M20) 249', 'Chandra, Acolyte of Flame': '(M20) 126', 'Cavalier of Thorns': '(M20) 167',
              'Mu Yanling, Sky Dancer': '(M20) 68', 'Leyline of the Void': '(M20) 107',
              'Yarok, the Desecrated': '(M20) 220', 'Omnath, Locus of the Roil': '(M20) 216',
              'Sorin, Imperious Bloodlord': '(M20) 115', 'Chandra, Awakened Inferno': '(M20) 127',
              'Rienne, Angel of Rebirth': '(M20) 281', 'Ajani, Inspiring Leader': '(M20) 282',
              'Goldmane Griffin': '(M20) 283', 'Savannah Sage': '(M20) 284', 'Twinblade Paladin': '(M20) 285',
              'Mu Yanling, Celestial Wind': '(M20) 286', 'Celestial Messenger': '(M20) 287',
              'Waterkin Shaman': '(M20) 288', "Yanling's Harbinger": '(M20) 289', 'Sorin, Vampire Lord': '(M20) 290',
              'Savage Gorger': '(M20) 291', "Sorin's Guide": '(M20) 292', 'Thirsting Bloodlord': '(M20) 293',
              "Chandra, Flame's Fury": '(M20) 294', "Chandra's Flame Wave": '(M20) 295',
              'Pyroclastic Elemental': '(M20) 296', 'Wildfire Elemental': '(M20) 297',
              "Vivien, Nature's Avenger": '(M20) 298', 'Ethereal Elk': '(M20) 299', 'Gnarlback Rhino': '(M20) 300',
              "Vivien's Crocodile": '(M20) 301', 'Angelic Guardian': '(M20) 302', 'Bastion Enforcer': '(M20) 303',
              'Imperial Outrider': '(M20) 307', 'Show of Valor': '(M20) 311', 'Siege Mastodon': '(M20) 312',
              'Coral Merfolk': '(M20) 315', 'Phantom Warrior': '(M20) 316', 'Dark Remedy': '(M20) 321',
              'Disentomb': '(M20) 322', 'Engulfing Eruption': '(M20) 328', 'Immortal Phoenix': '(M20) 332',
              'Nimble Birdsticker': '(M20) 333', 'Canopy Spider': '(M20) 339', 'Frilled Sandwalla': '(M20) 340',
              'Prized Unicorn': '(M20) 342', 'Woodland Mystic': '(M20) 344', 'Exultant Skymarcher': '(RIX) 7',
              'Sanguine Glorifier': '(RIX) 20', 'Snubhorn Sentry': '(RIX) 23', 'Kitesail Corsair': '(RIX) 41',
              'River Darter': '(RIX) 47', 'Shatter': '(RIX) 114', 'Pride of Conquerors': '(RIX) 17',
              "Squire's Devotion": '(RIX) 25', 'Sun Sentinel': '(RIX) 26', 'Sun-Crested Pterodon': '(RIX) 27',
              'Sworn Guardian': '(RIX) 58', 'Canal Monitor': '(RIX) 63', 'Dark Inquiry': '(RIX) 65',
              'Mausoleum Harpy': '(RIX) 78', 'Bombard': '(RIX) 93', 'Orazca Frillback': '(RIX) 140',
              'Cleansing Ray': '(RIX) 4', 'Soul of the Rapids': '(RIX) 56', 'Fathom Fleet Boarder': '(RIX) 71',
              'Grasping Scoundrel': '(RIX) 74', 'Reaver Ambush': '(RIX) 83', 'Recover': '(RIX) 84',
              'Vampire Revenant': '(RIX) 89', 'Voracious Vampire': '(RIX) 91', 'Goblin Trailblazer': '(RIX) 105',
              'Orazca Raptor': '(RIX) 108', 'Sun-Collared Raptor': '(RIX) 118', 'Swaggering Corsair': '(RIX) 119',
              'Hunt the Weak': '(RIX) 133', 'Jungle Creeper': '(RIX) 161', 'Divine Verdict': '(RIX) 5',
              'Crashing Tide': '(RIX) 34', 'Sailor of Means': '(RIX) 49', 'Spire Winder': '(RIX) 57',
              'Waterknot': '(RIX) 61', 'Dinosaur Hunter': '(RIX) 67', 'Dusk Charger': '(RIX) 69',
              "Buccaneer's Bravado": '(RIX) 96', 'Stampeding Horncrest': '(RIX) 116', 'Jadecraft Artisan': '(RIX) 135',
              'Overgrown Armasaur': '(RIX) 141', 'Blazing Hope': '(RIX) 3', 'Martyr of Dusk': '(RIX) 14',
              'Deadeye Rig-Hauler': '(RIX) 36', 'Siren Reaver': '(RIX) 54', 'Gruesome Fate': '(RIX) 75',
              'Impale': '(RIX) 76', 'Brazen Freebooter': '(RIX) 95', 'See Red': '(RIX) 112',
              'Giltgrove Stalker': '(RIX) 131', 'Hardy Veteran': '(RIX) 132', 'Strider Harness': '(RIX) 183',
              'Highland Lake': '(RIX) 189', 'Baffling End': '(RIX) 1', 'Oathsworn Vampire': '(RIX) 80',
              'Mutiny': '(RIX) 106', 'Aggressive Urge': '(RIX) 122', 'Strength of the Pack': '(RIX) 145',
              'Resplendent Griffin': '(RIX) 170', "Captain's Hook": '(RIX) 177', 'Orazca Relic': '(RIX) 181',
              "Traveler's Amulet": '(RIX) 184', 'Evolving Wilds': '(RIX) 186', 'Everdawn Champion': '(RIX) 6',
              'Moment of Triumph': '(RIX) 15', 'Hornswoggle': '(RIX) 39', 'Secrets of the Golden City': '(RIX) 52',
              'Slippery Scoundrel': '(RIX) 55', 'Storm Fleet Swashbuckler': '(RIX) 117',
              "Tilonalli's Crown": '(RIX) 120', 'Cacophodon': '(RIX) 123', 'Cherished Hatchling': '(RIX) 124',
              'Jade Bearer': '(RIX) 134', 'Gleaming Barrier': '(RIX) 178', 'Forsaken Sanctuary': '(RIX) 187',
              'Stone Quarry': '(RIX) 190', 'Vampire Champion': '(RIX) 198', 'Swab Goblin': '(RIX) 203',
              'Imperial Ceratops': '(RIX) 10', 'Aquatic Incursion': '(RIX) 32', 'Expel from Orazca': '(RIX) 37',
              'Moment of Craving': '(RIX) 79', 'Frilled Deathspitter': '(RIX) 104', "Pirate's Pillage": '(RIX) 109',
              'Shake the Foundations': '(RIX) 113', 'Forerunner of the Heralds': '(RIX) 129',
              'Woodland Stream': '(RIX) 191', 'Cinder Barrens': '(RIX) 205', 'Riverwise Augur': '(RIX) 48',
              'Dusk Legion Zealot': '(RIX) 70', 'Forerunner of the Coalition': '(RIX) 72', 'Tomb Robber': '(RIX) 87',
              'Daring Buccaneer': '(RIX) 98', 'Fanatical Firebrand': '(RIX) 101', 'Form of the Dinosaur': '(RIX) 103',
              'Jungleborn Pioneer': '(RIX) 137', 'Relentless Raptor': '(RIX) 169', 'Bishop of Binding': '(RIX) 2',
              'Induced Amnesia': '(RIX) 40', 'Sea Legs': '(RIX) 50', 'Sadistic Skymarcher': '(RIX) 85',
              'Crested Herdcaller': '(RIX) 126', 'Knight of the Stampede': '(RIX) 138',
              'Storm Fleet Sprinter': '(RIX) 172', "Vraska's Scorn": '(RIX) 200', "Angrath's Ambusher": '(RIX) 202',
              'Famished Paladin': '(RIX) 8', 'Majestic Heliopterus': '(RIX) 13', 'Arterial Flow': '(RIX) 62',
              'Deadeye Brawler': '(RIX) 155', 'Dire Fleet Neckbreaker': '(RIX) 156',
              'Forerunner of the Legion': '(RIX) 9', "Sphinx's Decree": '(RIX) 24', 'Swift Warden': '(RIX) 146',
              'Flood of Recollection': '(RIX) 38', "Dead Man's Chest": '(RIX) 66', 'Charging Tuskodon': '(RIX) 97',
              'Enter the Unknown': '(RIX) 128', 'Raging Regisaur': '(RIX) 168', 'Golden Demise': '(RIX) 73',
              'Protean Raider': '(RIX) 167', 'Paladin of Atonement': '(RIX) 16', 'Crafty Cutpurse': '(RIX) 33',
              'Mist-Cloaked Herald': '(RIX) 43', 'Needletooth Raptor': '(RIX) 107', 'Atzocan Seer': '(RIX) 153',
              'Awakened Amalgam': '(RIX) 175', 'Forerunner of the Empire': '(RIX) 102', "Angrath's Fury": '(RIX) 204',
              'Skymarcher Aspirant': '(RIX) 21', "Vraska's Conquistador": '(RIX) 199',
              'Thunderherd Migration': '(RIX) 149', "Brass's Bounty": '(RIX) 94', 'Silvergill Adept': '(RIX) 53',
              "Tilonalli's Summoner": '(RIX) 121', 'Temple Altisaur': '(RIX) 28', "Admiral's Order": '(RIX) 31',
              'Pitiless Plunderer': '(RIX) 81', 'Release to the Wind': '(RIX) 46', "Kumena's Awakening": '(RIX) 42',
              'Seafloor Oracle': '(RIX) 51', 'Reckless Rage': '(RIX) 110', 'Tetzimoc, Primal Death': '(RIX) 86',
              'Silverclad Ferocidons': '(RIX) 115', 'Golden Guardian': '(RIX) 179', 'Gold-Forge Garrison': '(RIX) 179',
              'Warkite Marauder': '(RIX) 60', "Vona's Hunger": '(RIX) 90', 'Path of Mettle': '(RIX) 165',
              'Metzali, Tower of Triumph': '(RIX) 165', 'Silent Gravestone': '(RIX) 182',
              'Dire Fleet Poisoner': '(RIX) 68', 'Siegehorn Ceratops': '(RIX) 171', 'Champion of Dusk': '(RIX) 64',
              'Ravenous Chupacabra': '(RIX) 82', 'Slaughter the Strong': '(RIX) 22', 'Merfolk Mistbinder': '(RIX) 164',
              'Deeproot Elite': '(RIX) 127', 'Profane Procession': '(RIX) 166', 'Tomb of the Dusk Rose': '(RIX) 166',
              'Radiant Destiny': '(RIX) 18', 'Legion Lieutenant': '(RIX) 163', "Mastermind's Acquisition": '(RIX) 77',
              'Zetalpa, Primal Dawn': '(RIX) 30', 'Arch of Orazca': '(RIX) 185', 'Storm the Vault': '(RIX) 173',
              'Vault of Catlacan': '(RIX) 173', 'Blood Sun': '(RIX) 92', 'Jadelight Ranger': '(RIX) 136',
              'Nezahal, Primal Tide': '(RIX) 45', 'Curious Obsession': '(RIX) 35', 'World Shaper': '(RIX) 151',
              'Trapjaw Tyrant': '(RIX) 29', 'Dire Fleet Daredevil': '(RIX) 99', "Hadana's Climb": '(RIX) 158',
              'Winged Temple of Orazca': '(RIX) 158', 'Timestream Navigator': '(RIX) 59',
              'Path of Discovery': '(RIX) 142', 'Azor, the Lawbringer': '(RIX) 154', "Azor's Gateway": '(RIX) 176',
              'Sanctum of the Sun': '(RIX) 176', 'Rekindling Phoenix': '(RIX) 111',
              'Ghalta, Primal Hunger': '(RIX) 130', 'Angrath, the Flame-Chained': '(RIX) 152',
              'Journey to Eternity': '(RIX) 160', 'Atzal, Cave of Eternity': '(RIX) 160',
              'Tendershoot Dryad': '(RIX) 147', 'Angrath, Minotaur Pirate': '(RIX) 201',
              'Kumena, Tyrant of Orazca': '(RIX) 162', 'Huatli, Radiant Champion': '(RIX) 159',
              'Etali, Primal Storm': '(RIX) 100', 'Wayward Swordtooth': '(RIX) 150', 'Polyraptor': '(RIX) 144',
              'Vraska, Scheming Gorgon': '(RIX) 197', 'Elenda, the Dusk Rose': '(RIX) 157',
              'Twilight Prophet': '(RIX) 88', 'Zacama, Primal Calamity': '(RIX) 174', 'The Immortal Sun': '(RIX) 180',
              'Civic Stalwart': '(RNA) 6', 'Haazda Officer': '(RNA) 10', 'Prowling Caracal': '(RNA) 17',
              'Syndicate Messenger': '(RNA) 25', 'Senate Courier': '(RNA) 50', 'Slimebind': '(RNA) 54',
              'Consign to the Pit': '(RNA) 69', 'Noxious Groodion': '(RNA) 78', 'Plague Wight': '(RNA) 82',
              'Undercity Scavenger': '(RNA) 88', 'Act of Treason': '(RNA) 91', 'Burning-Tree Vandal': '(RNA) 94',
              'Scorchmark': '(RNA) 113', 'Territorial Boar': '(RNA) 145', 'Azorius Knight-Arbiter': '(RNA) 154',
              'Rakdos Firewheeler': '(RNA) 197', 'Rakdos Roustabout': '(RNA) 198', 'Vizkopa Vampire': '(RNA) 220',
              'Bring to Trial': '(RNA) 5', 'Expose to Daylight': '(RNA) 8', 'Summary Judgment': '(RNA) 24',
              'Tenth District Veteran': '(RNA) 26', 'Watchful Giant': '(RNA) 30', 'Skitter Eel': '(RNA) 53',
              'Catacomb Crocodile': '(RNA) 67', 'Dead Revels': '(RNA) 71', 'Grotesque Demise': '(RNA) 75',
              'Rakdos Trumpeter': '(RNA) 84', 'Thirsting Shade': '(RNA) 87', "Undercity's Embrace": '(RNA) 89',
              'Burn Bright': '(RNA) 93', 'Feral Maaka': '(RNA) 100', 'Flames of the Raze-Boar': '(RNA) 101',
              'Ghor-Clan Wrecker': '(RNA) 103', 'Rubblebelt Recluse': '(RNA) 111', 'Rumbling Ruin': '(RNA) 112',
              'Storm Strike': '(RNA) 119', 'Mammoth Spider': '(RNA) 132', "Sagittars' Volley": '(RNA) 138',
              'Sauroform Hybrid': '(RNA) 140', 'Aeromunculus': '(RNA) 152', 'Applied Biomancy': '(RNA) 153',
              'Final Payment': '(RNA) 171', 'Frenzied Arynx': '(RNA) 173', "Sphinx's Insight": '(RNA) 209',
              'Senate Griffin': '(RNA) 219', 'Concordia Pegasus': '(RNA) 7', 'Forbidding Spirit': '(RNA) 9',
              'Sky Tether': '(RNA) 21', 'Twilight Panther': '(RNA) 28', "Debtors' Transport": '(RNA) 72',
              'Gravel-Hide Goblin': '(RNA) 105', 'Spikewheel Acrobat': '(RNA) 118', 'Axebane Beast': '(RNA) 121',
              'Rampaging Rendhorn': '(RNA) 135', 'Steeple Creeper': '(RNA) 142', 'Sylvan Brushstrider': '(RNA) 144',
              'Get the Point': '(RNA) 176', 'Rubblebelt Runner': '(RNA) 202', 'Sphinx of New Prahv': '(RNA) 208',
              'Rubble Slinger': '(RNA) 217', 'Screaming Shield': '(RNA) 239', 'Simic Locket': '(RNA) 240',
              'Simic Guildgate': '(RNA) 258', 'Knight of Sorrows': '(RNA) 14', "Arrester's Admonition": '(RNA) 31',
              'Chillbringer': '(RNA) 33', 'Clear the Mind': '(RNA) 34', 'Code of Constraint': '(RNA) 35',
              'Gateway Sneak': '(RNA) 40', "Sage's Row Savant": '(RNA) 49', 'Blade Juggler': '(RNA) 63',
              'Spire Mangler': '(RNA) 86', 'Amplifire': '(RNA) 92', 'Dagger Caster': '(RNA) 97', 'Deface': '(RNA) 98',
              'Gift of Strength': '(RNA) 127', 'Root Snare': '(RNA) 137', 'Wrecking Beast': '(RNA) 150',
              'Bolrac-Clan Crusher': '(RNA) 159', "Dovin's Acuity": '(RNA) 168', 'Grasping Thrull': '(RNA) 177',
              'Hackrobat': '(RNA) 181', 'Imperious Oligarch': '(RNA) 184', 'Rafter Demon': '(RNA) 196',
              'Gruul Locket': '(RNA) 234', 'Azorius Guildgate': '(RNA) 244', 'Orzhov Guildgate': '(RNA) 253',
              'Ministrant of Obligation': '(RNA) 16', 'Rally to Battle': '(RNA) 18', 'Humongulus': '(RNA) 41',
              'Clamor Shaman': '(RNA) 96', 'Rubble Reading': '(RNA) 110', 'Savage Smash': '(RNA) 203',
              'Footlight Fiend': '(RNA) 216', 'Scuttlegator': '(RNA) 218', 'Gruul Guildgate': '(RNA) 250',
              'Rakdos Guildgate': '(RNA) 255', "Arrester's Zeal": '(RNA) 4', 'Impassioned Orator': '(RNA) 12',
              "Sentinel's Mark": '(RNA) 20', 'Coral Commando': '(RNA) 36', 'Eyes Everywhere': '(RNA) 38',
              'Shimmer of Possibility': '(RNA) 51', 'Bankrupt in Blood': '(RNA) 62', 'Carrion Imp': '(RNA) 66',
              'Clear the Stage': '(RNA) 68', 'Ill-Gotten Inheritance': '(RNA) 77', 'Goblin Gathering': '(RNA) 104',
              'Enraged Ceratok': '(RNA) 125', 'Regenesis': '(RNA) 136', 'Titanic Brawl': '(RNA) 146',
              'Trollbred Guardian': '(RNA) 148', 'Azorius Skyguard': '(RNA) 155', 'Galloping Lizrog': '(RNA) 175',
              "Lawmage's Binding": '(RNA) 190', 'Syndicate Guildmage': '(RNA) 211', 'Scrabbling Claws': '(RNA) 238',
              'Sphinx of the Guildpact': '(RNA) 241', 'Faerie Duelist': '(RNA) 39', 'Smelt-Ward Ignus': '(RNA) 116',
              'Spear Spewer': '(RNA) 117', 'Saruli Caretaker': '(RNA) 139', 'Silhana Wayfinder': '(RNA) 141',
              'Stony Strength': '(RNA) 143', 'Senate Guildmage': '(RNA) 204', 'Consecrate': '(RNA) 224',
              'Consecrate // Consume': '(RNA) 224', 'Depose': '(RNA) 225', 'Depose // Deploy': '(RNA) 225',
              'Azorius Locket': '(RNA) 231', 'Gate Colossus': '(RNA) 232', 'Junktroller': '(RNA) 235',
              'Orzhov Locket': '(RNA) 236', 'Angelic Exaltation': '(RNA) 2', 'Archway Angel': '(RNA) 3',
              "Justiciar's Portal": '(RNA) 13', 'Spirit of the Spires': '(RNA) 23', 'Prying Eyes': '(RNA) 46',
              'Swirling Torrent': '(RNA) 56', 'Orzhov Racketeers': '(RNA) 80', 'Tin Street Dodger': '(RNA) 120',
              'Biogenic Upgrade': '(RNA) 123', 'Open the Gates': '(RNA) 133', 'Cult Guildmage': '(RNA) 164',
              'Knight of the Last Breath': '(RNA) 188', 'Macabre Mockery': '(RNA) 191', 'Sunder Shaman': '(RNA) 210',
              'Quench': '(RNA) 48', 'Thought Collapse': '(RNA) 57', 'Wall of Lost Thoughts': '(RNA) 59',
              'Vindictive Vampire': '(RNA) 90', 'Gruul Beastmaster': '(RNA) 129', 'Rampage of the Clans': '(RNA) 134',
              'Tower Defense': '(RNA) 147', 'Clan Guildmage': '(RNA) 162', 'Zhur-Taa Goblin': '(RNA) 215',
              'Carnival': '(RNA) 222', 'Carnival // Carnage': '(RNA) 222', 'Rakdos Locket': '(RNA) 237',
              'Awaken the Erstwhile': '(RNA) 61', 'Bloodmist Infiltrator': '(RNA) 65', 'Fireblade Artist': '(RNA) 172',
              'Gyre Engineer': '(RNA) 180', 'Pitiless Pontiff': '(RNA) 194', 'Sharktocrab': '(RNA) 206',
              'Resolute Watchdog': '(RNA) 19', 'Orzhov Enforcer': '(RNA) 79', 'Cavalcade of Calamity': '(RNA) 95',
              'Gatebreaker Ram': '(RNA) 126', 'Basilica Bell-Haunt': '(RNA) 156', 'Nikya of the Old Ways': '(RNA) 193',
              'Combine Guildmage': '(RNA) 163', 'Skatewing Spy': '(RNA) 52', 'Cry of the Carnarium': '(RNA) 70',
              'Drill Bit': '(RNA) 73', 'Gates Ablaze': '(RNA) 102', 'Immolation Shaman': '(RNA) 106',
              'Windstorm Drake': '(RNA) 60', 'Mirror March': '(RNA) 108', 'Warrant': '(RNA) 230',
              'Warrant // Warden': '(RNA) 230', 'Glass of the Guildpact': '(RNA) 233', 'Growth Spiral': '(RNA) 178',
              'Mortify': '(RNA) 192', 'Tome of the Guildpact': '(RNA) 242', 'Lumbering Battlement': '(RNA) 15',
              'Essence Capture': '(RNA) 37', 'Precognitive Perception': '(RNA) 45', 'Bedeck': '(RNA) 221',
              'Bedeck // Bedazzle': '(RNA) 221', 'Collision // Colossus': '(RNA) 223', 'Colossus': '(RNA) 223',
              'Verity Circle': '(RNA) 58', 'High Alert': '(RNA) 182', 'Thrash': '(RNA) 229',
              'Thrash // Threat': '(RNA) 229', 'Font of Agonies': '(RNA) 74', 'Frilled Mystic': '(RNA) 174',
              'Zegana, Utopian Speaker': '(RNA) 214', 'End-Raze Forerunners': '(RNA) 124',
              'Ethereal Absolution': '(RNA) 170', 'Persistent Petitioners': '(RNA) 44', 'Pestilent Spirit': '(RNA) 81',
              'Skewer the Critics': '(RNA) 115', 'Sphinx of Foresight': '(RNA) 55', 'Repudiate': '(RNA) 227',
              'Repudiate // Replicate': '(RNA) 227', 'Simic Ascendancy': '(RNA) 207',
              "Biomancer's Familiar": '(RNA) 158', 'Benthic Biomancer': '(RNA) 32', 'Theater of Horrors': '(RNA) 213',
              'Lavinia, Azorius Renegade': '(RNA) 189', 'Revival': '(RNA) 228', 'Revival // Revenge': '(RNA) 228',
              'Rix Maadi Reveler': '(RNA) 109', 'Emergency Powers': '(RNA) 169', 'Mesmerizing Benthid': '(RNA) 43',
              'Plaza of Harmony': '(RNA) 254', 'Mass Manipulation': '(RNA) 42', 'Teysa Karlov': '(RNA) 212',
              'Unbreakable Formation': '(RNA) 29', 'Ravager Wurm': '(RNA) 200', 'Rakdos, the Showstopper': '(RNA) 199',
              'Rhythm of the Wild': '(RNA) 201', 'Absorb': '(RNA) 151', 'Wilderness Reclamation': '(RNA) 149',
              'Captive Audience': '(RNA) 160', 'Pteramander': '(RNA) 47', 'Hero of Precinct One': '(RNA) 11',
              'Gutterbones': '(RNA) 76', 'Tithe Taker': '(RNA) 27', 'Cindervines': '(RNA) 161',
              'Growth-Chamber Guardian': '(RNA) 128', 'Judith, the Scourge Diva': '(RNA) 185',
              'Angel of Grace': '(RNA) 1', 'Guardian Project': '(RNA) 130', 'Electrodominance': '(RNA) 99',
              'Gruul Spellbreaker': '(RNA) 179', "Kaya's Wrath": '(RNA) 187', 'Priest of Forgotten Gods': '(RNA) 83',
              'Dovin, Grand Arbiter': '(RNA) 167', 'Light Up the Stage': '(RNA) 107',
              'Domri, Chaos Bringer': '(RNA) 166', 'Skarrgan Hellkite': '(RNA) 114', 'Incubation Druid': '(RNA) 131',
              'Incubation': '(RNA) 226', 'Incubation // Incongruity': '(RNA) 226', 'Bedevil': '(RNA) 157',
              'Biogenic Ooze': '(RNA) 122', 'Prime Speaker Vannifar': '(RNA) 195', 'Spawn of Mayhem': '(RNA) 85',
              'Seraph of the Scales': '(RNA) 205', 'Deputy of Detention': '(RNA) 165', 'Smothering Tithe': '(RNA) 22',
              'Kaya, Orzhov Usurper': '(RNA) 186', 'Hallowed Fountain': '(RNA) 251', 'Godless Shrine': '(RNA) 248',
              'Stomping Ground': '(RNA) 259', 'Blood Crypt': '(RNA) 245', 'Breeding Pool': '(RNA) 246',
              'Hydroid Krasis': '(RNA) 183', 'Dovin, Architect of Law': '(RNA) 265', 'Elite Arrester': '(RNA) 266',
              "Dovin's Dismissal": '(RNA) 267', "Dovin's Automaton": '(RNA) 268', 'Domri, City Smasher': '(RNA) 269',
              'Ragefire': '(RNA) 270', 'Charging War Boar': '(RNA) 271', "Domri's Nodorog": '(RNA) 272',
              'The Haunt of Hightower': '(RNA) 273', 'Thunder Drake': '(WAR) 73', 'Charity Extractor': '(WAR) 81',
              'Lazotep Behemoth': '(WAR) 95', 'Chainwhip Cyclops': '(WAR) 118', 'Honor the God-Pharaoh': '(WAR) 132',
              'Invading Manticore': '(WAR) 134', 'Turret Ogre': '(WAR) 148', 'Kraul Stinger': '(WAR) 165',
              'Primordial Wurm': '(WAR) 174', 'Thundering Ceratok': '(WAR) 179', 'Wardscale Crocodile': '(WAR) 183',
              'Charmed Stray': '(WAR) 8', 'Law-Rune Enforcer': '(WAR) 20', 'Trusted Pegasus': '(WAR) 36',
              'War Screecher': '(WAR) 39', 'Relentless Advance': '(WAR) 64', 'Spellkeeper Weird': '(WAR) 69',
              'Dreadmalkin': '(WAR) 87', 'Duskmantle Operative': '(WAR) 88', "Vraska's Finisher": '(WAR) 112',
              'Ahn-Crop Invader': '(WAR) 113', 'Goblin Assailant': '(WAR) 128', 'Goblin Assault Team': '(WAR) 129',
              "Nahiri's Stoneblades": '(WAR) 139', "Sarkhan's Catharsis": '(WAR) 144', 'Snarespinner': '(WAR) 176',
              "Saheeli's Silverwing": '(WAR) 243', 'Battlefield Promotion': '(WAR) 5', 'Bulwark Giant': '(WAR) 7',
              "Gideon's Triumph": '(WAR) 15', "Teyo's Lightshield": '(WAR) 33', "Ashiok's Skulker": '(WAR) 40',
              'Callous Dismissal': '(WAR) 44', 'Crush Dissent': '(WAR) 47', 'Erratic Visionary': '(WAR) 48',
              'Sky Theater Strix': '(WAR) 67', 'Stealth Mission': '(WAR) 70', "Davriel's Shadowfugue": '(WAR) 84',
              "Sorin's Thirst": '(WAR) 104', 'Spark Reaper': '(WAR) 106', 'Toll of the Invasion': '(WAR) 108',
              'Forced Landing': '(WAR) 161', 'Prismite': '(WAR) 242', 'Divine Arrow': '(WAR) 10',
              'Ironclad Krovod': '(WAR) 19', "Kiora's Dambreaker": '(WAR) 58', 'Naga Eternal': '(WAR) 60',
              'No Escape': '(WAR) 63', 'Totally Lost': '(WAR) 74', 'Aid the Fallen': '(WAR) 76',
              'Bleeding Edge': '(WAR) 78', 'Blindblast': '(WAR) 114', 'Bond of Passion': '(WAR) 116',
              "Chandra's Pyrohelix": '(WAR) 120', 'Raging Kronch': '(WAR) 141', "Arlinn's Wolf": '(WAR) 151',
              'Kronch Wrangler': '(WAR) 166', "Ugin's Conjurant": '(WAR) 3', 'Enforcer Griffin': '(WAR) 11',
              'Loxodon Sergeant': '(WAR) 21', 'Makeshift Battalion': '(WAR) 22', 'Rising Populace': '(WAR) 29',
              'Topple the Statue': '(WAR) 35', 'Aven Eternal': '(WAR) 42', 'Banehound': '(WAR) 77',
              'Eternal Taskmaster': '(WAR) 90', 'Herald of the Dreadhorde': '(WAR) 93',
              'Vampire Opportunist': '(WAR) 110', 'Devouring Hellion': '(WAR) 124', 'Grim Initiate': '(WAR) 130',
              'Heartfire': '(WAR) 131', 'Centaur Nurturer': '(WAR) 156', 'Mowu, Loyal Companion': '(WAR) 167',
              'Pollenbright Druid': '(WAR) 173', 'Steady Aim': '(WAR) 177', 'Heartwarming Redemption': '(WAR) 199',
              'Invade the City': '(WAR) 201', 'Kaya, Bane of the Dead': '(WAR) 231', 'Guild Globe': '(WAR) 239',
              "Ajani's Pridemate": '(WAR) 4', 'Bond of Discipline': '(WAR) 6', 'Defiant Strike': '(WAR) 9',
              "Gideon's Sacrifice": '(WAR) 14', 'Pouncing Lynx': '(WAR) 25', 'Sunblade Angel': '(WAR) 31',
              "Kasmina's Transmutation": '(WAR) 57', 'Shriekdiver': '(WAR) 103', 'Spark Harvest': '(WAR) 105',
              'Vizier of the Scorpion': '(WAR) 111', 'Burning Prophet': '(WAR) 117',
              'Cyclops Electromancer': '(WAR) 122', "Tibalt's Rager": '(WAR) 147', 'Arboreal Grazer': '(WAR) 149',
              'Bond of Flourishing': '(WAR) 155', 'Storm the Citadel': '(WAR) 178', "Vivien's Grizzly": '(WAR) 182',
              "Huatli's Raptor": '(WAR) 200', "Ral's Outburst": '(WAR) 212', 'Iron Bully': '(WAR) 240',
              'Grateful Apparition': '(WAR) 17', 'Martyr for the Cause': '(WAR) 23', 'Rally of Wings': '(WAR) 27',
              "Jace's Triumph": '(WAR) 55', 'Rescuer Sphinx': '(WAR) 65', "Teferi's Time Twist": '(WAR) 72',
              'Wall of Runes': '(WAR) 75', "Chandra's Triumph": '(WAR) 121', 'Dreadhorde Twins': '(WAR) 126',
              "Samut's Sprint": '(WAR) 142', 'Arlinn, Voice of the Pack': '(WAR) 150', 'Giant Growth': '(WAR) 162',
              'Merfolk Skydiver': '(WAR) 205', 'Pledge of Unity': '(WAR) 210', 'Rubblebelt Rioters': '(WAR) 215',
              'Nahiri, Storm of Stone': '(WAR) 233', 'Bond of Revival': '(WAR) 80', 'Lazotep Reaver': '(WAR) 96',
              'Ob Nixilis, the Hate-Twisted': '(WAR) 100', 'Bolt Bend': '(WAR) 115', 'Spellgorger Weird': '(WAR) 145',
              'Band Together': '(WAR) 153', 'Courage in Crisis': '(WAR) 158', "Huatli, the Sun's Heart": '(WAR) 230',
              'Prison Realm': '(WAR) 26', 'Bond of Insight': '(WAR) 43', 'Contentious Plan': '(WAR) 46',
              'Eternal Skylord': '(WAR) 49', 'Lazotep Plating': '(WAR) 59', 'Silent Submersible': '(WAR) 66',
              'Tithebearer Giant': '(WAR) 107', 'Bloom Hulk': '(WAR) 154', "Domri's Ambush": '(WAR) 192',
              'Mayhem Devil': '(WAR) 204', 'Angrath, Captain of Chaos': '(WAR) 227',
              'Samut, Tyrant Smasher': '(WAR) 235', 'Ignite the Beacon': '(WAR) 18', 'Ravnica at War': '(WAR) 28',
              "Wanderer's Strike": '(WAR) 38', 'Unlikely Aid': '(WAR) 109', 'Jaya, Venerated Firemage': '(WAR) 135',
              "Jaya's Greeting": '(WAR) 136', 'Challenger Troll': '(WAR) 157', "Nissa's Triumph": '(WAR) 170',
              'Bioessence Hydra': '(WAR) 186', 'Gleaming Overseer': '(WAR) 198',
              'Tenth District Legionnaire': '(WAR) 222', 'Deliver Unto Evil': '(WAR) 85',
              "Ob Nixilis's Cruelty": '(WAR) 101', 'Price of Betrayal': '(WAR) 102', 'Elite Guardmage': '(WAR) 195',
              "God-Pharaoh's Statue": '(WAR) 238', 'Augur of Bolas': '(WAR) 41', "Tamiyo's Epiphany": '(WAR) 71',
              'Mizzium Tank': '(WAR) 138', 'Jiang Yanggu, Wildcrafter': '(WAR) 164',
              'Dovin, Hand of Control': '(WAR) 229', "Vraska, Swarm's Eminence": '(WAR) 236',
              'Firemind Vessel': '(WAR) 237', 'Mana Geode': '(WAR) 241', 'Teyo, the Shieldmage': '(WAR) 32',
              'The Wanderer': '(WAR) 37', 'Flux Channeler': '(WAR) 52', 'Cruel Celebrant': '(WAR) 188',
              'Leyline Prowler': '(WAR) 202', 'Role Reversal': '(WAR) 214', 'Soul Diviner': '(WAR) 218',
              'Kiora, Behemoth Beckoner': '(WAR) 232', 'Interplanar Beacon': '(WAR) 247', 'Single Combat': '(WAR) 30',
              'Kasmina, Enigmatic Mentor': '(WAR) 56', 'Tibalt, Rakish Instigator': '(WAR) 146',
              'Deathsprout': '(WAR) 189', 'Awakening of Vitu-Ghazi': '(WAR) 152', 'Planewide Celebration': '(WAR) 172',
              'Parhelion II': '(WAR) 24', 'Paradise Druid': '(WAR) 171', "Angrath's Rampage": '(WAR) 185',
              'Solar Blaze': '(WAR) 216', "Tyrant's Scorn": '(WAR) 225', 'Davriel, Rogue Shadowmage': '(WAR) 83',
              'Tolsimir, Friend to Wolves': '(WAR) 224', 'Living Twister': '(WAR) 203',
              'Widespread Brutality': '(WAR) 226', 'Emergence Zone': '(WAR) 245', "Kaya's Ghostform": '(WAR) 94',
              'Neoform': '(WAR) 206', 'Commence the Endgame': '(WAR) 45', 'Storrev, Devkarin Lich': '(WAR) 219',
              'Mobilized District': '(WAR) 249', 'Neheb, Dreadhorde Champion': '(WAR) 140',
              'Evolution Sage': '(WAR) 159', 'Despark': '(WAR) 190', "Liliana's Triumph": '(WAR) 98',
              "Vivien's Arkbow": '(WAR) 181', 'Tomik, Distinguished Advokist': '(WAR) 34',
              'Casualties of War': '(WAR) 187', 'Time Wipe': '(WAR) 223', 'Fblthp, the Lost': '(WAR) 50',
              'Oath of Kaya': '(WAR) 209', 'Massacre Girl': '(WAR) 99', 'Command the Dreadhorde': '(WAR) 82',
              "Dovin's Veto": '(WAR) 193', 'Ajani, the Greathearted': '(WAR) 184', 'Dreadhorde Butcher': '(WAR) 194',
              'Saheeli, Sublime Artificer': '(WAR) 234', 'Enter the God-Eternals': '(WAR) 196',
              'Spark Double': '(WAR) 68', "Bolas's Citadel": '(WAR) 79', "Narset's Reversal": '(WAR) 62',
              'Krenko, Tin Street Kingpin': '(WAR) 137', 'Ashiok, Dream Render': '(WAR) 228',
              'Domri, Anarch of Bolas': '(WAR) 191', 'Sarkhan the Masterless': '(WAR) 143',
              'Ral, Storm Conduit': '(WAR) 211', "Karn's Bastion": '(WAR) 248', 'Dreadhorde Invasion': '(WAR) 86',
              'Finale of Eternity': '(WAR) 91', 'Finale of Revelation': '(WAR) 51',
              'Jace, Wielder of Mysteries': '(WAR) 54', 'The Elderspell': '(WAR) 89',
              'Tamiyo, Collector of Tales': '(WAR) 220', 'Feather, the Redeemed': '(WAR) 197',
              'Finale of Glory': '(WAR) 12', 'Chandra, Fire Artisan': '(WAR) 119', 'Roalesk, Apex Hybrid': '(WAR) 213',
              'Sorin, Vengeful Bloodlord': '(WAR) 217', 'Vivien, Champion of the Wilds': '(WAR) 180',
              'Niv-Mizzet Reborn': '(WAR) 208', 'God-Eternal Bontu': '(WAR) 92', 'God-Eternal Rhonas': '(WAR) 163',
              'Narset, Parter of Veils': '(WAR) 61', 'Nissa, Who Shakes the World': '(WAR) 169',
              'Ugin, the Ineffable': '(WAR) 2', 'Ilharg, the Raze-Boar': '(WAR) 133', 'God-Eternal Oketra': '(WAR) 16',
              'Blast Zone': '(WAR) 244', 'Finale of Promise': '(WAR) 127', 'God-Eternal Kefnet': '(WAR) 53',
              'Gideon Blackblade': '(WAR) 13', 'Dreadhorde Arcanist': '(WAR) 125', 'Finale of Devastation': '(WAR) 160',
              'Nicol Bolas, Dragon-God': '(WAR) 207', 'Karn, the Great Creator': '(WAR) 1',
              'Liliana, Dreadhorde General': '(WAR) 97', 'Teferi, Time Raveler': '(WAR) 221',
              'Gideon, the Oathsworn': '(WAR) 265', 'Desperate Lunge': '(WAR) 266', "Gideon's Battle Cry": '(WAR) 267',
              "Gideon's Company": '(WAR) 268', 'Jace, Arcane Strategist': '(WAR) 270',
              'Guildpact Informant': '(WAR) 271', "Jace's Projection": '(WAR) 272', "Jace's Ruse": '(WAR) 273',
              'Tezzeret, Master of the Bridge': '(WAR) 275', 'Ritual of Rejuvenation': '(XLN) 32',
              'Shining Aerosaur': '(XLN) 36', 'Skyblade of the Legion': '(XLN) 37', 'Headwater Sentries': '(XLN) 58',
              'Storm Sculptor': '(XLN) 85', "Queen's Agent": '(XLN) 114', "Queen's Bay Soldier": '(XLN) 115',
              'Storm Fleet Pyromancer': '(XLN) 163', 'Crash the Ramparts': '(XLN) 182', 'Crushing Canopy': '(XLN) 183',
              "Ixalli's Diviner": '(XLN) 192', "Ixalli's Keeper": '(XLN) 193', "Bishop's Soldier": '(XLN) 6',
              'Encampment Keeper': '(XLN) 11', 'Pious Interdiction': '(XLN) 26', 'Shipwreck Looter': '(XLN) 76',
              'Desperate Castaways': '(XLN) 101', 'Fathom Fleet Cutthroat': '(XLN) 107',
              'Mark of the Vampire': '(XLN) 113', 'Fathom Fleet Firebrand': '(XLN) 142', 'Nest Robber': '(XLN) 152',
              "Tilonalli's Knight": '(XLN) 169', 'Unfriendly Fire': '(XLN) 172', 'Colossal Dreadmaw': '(XLN) 180',
              'Jungle Delver': '(XLN) 195', 'Raptor Companion': '(XLN) 31', 'Sunrise Seeker': '(XLN) 40',
              'One With the Wind': '(XLN) 64', 'Run Aground': '(XLN) 72', 'Shore Keeper': '(XLN) 77',
              'Siren Lookout': '(XLN) 78', 'Anointed Deacon': '(XLN) 89', 'Dire Fleet Interloper': '(XLN) 103',
              'Skulduggery': '(XLN) 123', 'Brazen Buccaneers': '(XLN) 134', 'Demolish': '(XLN) 139',
              'Headstrong Brute': '(XLN) 147', 'Blossom Dryad': '(XLN) 178', 'Deeproot Warrior': '(XLN) 186',
              'Emergent Growth': '(XLN) 188', 'Grazing Whiptail': '(XLN) 190', 'Pounce': '(XLN) 200',
              'Spike-Tailed Ceratops': '(XLN) 209', 'Belligerent Brontodon': '(XLN) 218',
              'Marauding Looter': '(XLN) 225', 'Elaborate Firecannon': '(XLN) 237', 'Unknown Shores': '(XLN) 259',
              'Legion Conquistador': '(XLN) 20', 'Pterodon Knight': '(XLN) 28', 'Slash of Talons': '(XLN) 38',
              'Depths of Desire': '(XLN) 52', 'Watertrap Weaver': '(XLN) 87', 'Contract Killing': '(XLN) 95',
              'Dark Nourishment': '(XLN) 97', 'Heartless Pillage': '(XLN) 109', 'Spreading Rot': '(XLN) 125',
              'Vanquish the Weak': '(XLN) 127', 'Dual Shot': '(XLN) 141', 'Frenzied Raptor': '(XLN) 146',
              'Rummaging Goblin': '(XLN) 160', 'Jade Guardian': '(XLN) 194', 'Ravenous Daggertooth': '(XLN) 202',
              'Gilded Sentinel': '(XLN) 239', "Pirate's Cutlass": '(XLN) 242', 'Bright Reprisal': '(XLN) 7',
              'Demystify': '(XLN) 8', 'Emissary of Sunrise': '(XLN) 10', 'Imperial Lancer': '(XLN) 15',
              "Queen's Commission": '(XLN) 29', 'Rallying Roar': '(XLN) 30', "Navigator's Ruin": '(XLN) 63',
              'Perilous Voyage': '(XLN) 67', "Pirate's Prize": '(XLN) 68', 'Storm Fleet Spy': '(XLN) 84',
              'Blight Keeper': '(XLN) 92', 'Deadeye Tormentor': '(XLN) 98', 'Fire Shrine Keeper': '(XLN) 144',
              'Firecannon Blast': '(XLN) 145', 'Swashbuckling': '(XLN) 167', 'New Horizons': '(XLN) 198',
              'Verdant Rebirth': '(XLN) 212', 'Cobbled Wings': '(XLN) 233', 'Inspiring Cleric': '(XLN) 16',
              "Legion's Judgment": '(XLN) 21', 'Paladin of the Bloodstained': '(XLN) 25',
              'Storm Fleet Aerialist': '(XLN) 83', 'Tempest Caller': '(XLN) 86', 'Dire Fleet Hoarder': '(XLN) 102',
              'Hijack': '(XLN) 148', 'Repeating Barrage': '(XLN) 156', 'Trove of Temptation': '(XLN) 171',
              'Atzocan Archer': '(XLN) 176', 'Blinding Fog': '(XLN) 177', 'Slice in Twain': '(XLN) 207',
              "Vampire's Zeal": '(XLN) 43', 'Prosperous Pirates': '(XLN) 69', 'River Sneak': '(XLN) 70',
              'Bishop of the Bloodstained': '(XLN) 91', 'Ruthless Knave': '(XLN) 119', 'Wanted Scoundrels': '(XLN) 131',
              'Lightning Strike': '(XLN) 149', 'Commune with Dinosaurs': '(XLN) 181',
              "Tishana's Wayfinder": '(XLN) 211', 'Waker of the Wilds': '(XLN) 215',
              "Hierophant's Chalice": '(XLN) 240', 'Prying Blade': '(XLN) 244', "Huatli's Spurring": '(XLN) 287',
              'Duskborne Skymarcher': '(XLN) 9', 'Looming Altisaur': '(XLN) 23', 'Steadfast Armasaur': '(XLN) 39',
              'Shaper Apprentice': '(XLN) 75', 'Deathless Ancient': '(XLN) 100', 'March of the Drowned': '(XLN) 112',
              "Seekers' Squire": '(XLN) 121', 'Skittering Heartstopper': '(XLN) 122', 'Bonded Horncrest': '(XLN) 133',
              'Makeshift Munitions': '(XLN) 151', 'Sun-Crowned Hunters': '(XLN) 164',
              "River Heralds' Boon": '(XLN) 204', 'Deadeye Plunderers': '(XLN) 220', "Huatli's Snubhorn": '(XLN) 286',
              'Glorifier of Dusk': '(XLN) 12', 'Wind Strider': '(XLN) 88', 'Costly Plunder': '(XLN) 96',
              'Lurking Chupacabra': '(XLN) 111', 'Walk the Plank': '(XLN) 130', 'Thundering Spineback': '(XLN) 210',
              'Shapers of Nature': '(XLN) 228', 'Dusk Legion Dreadnought': '(XLN) 236', 'Shadowed Caravel': '(XLN) 246',
              "Kinjalli's Caller": '(XLN) 18', 'Daring Saboteur': '(XLN) 49', 'Deadeye Quartermaster': '(XLN) 50',
              'Dreamcaller Siren': '(XLN) 54', "Siren's Ruse": '(XLN) 80', 'Dinosaur Stampede': '(XLN) 140',
              'Lightning-Rig Crew': '(XLN) 150', 'Storm Fleet Arsonist': '(XLN) 162', "Kumena's Speaker": '(XLN) 196',
              'Old-Growth Dryads': '(XLN) 199', 'Savage Stomp': '(XLN) 205', 'Sentinel Totem': '(XLN) 245',
              'Favorable Winds': '(XLN) 56', "Grim Captain's Call": '(XLN) 108', 'Charging Monstrosaur': '(XLN) 138',
              'Rigging Runner': '(XLN) 157', 'Thrash of Raptors': '(XLN) 168', "Tilonalli's Skinshifter": '(XLN) 170',
              'Wily Goblin': '(XLN) 174', 'Ancient Brontodon': '(XLN) 175', 'Vineshaper Mystic': '(XLN) 214',
              'Dire Fleet Captain': '(XLN) 221', 'Bellowing Aegisaur': '(XLN) 4', 'Sanguine Sacrament': '(XLN) 33',
              "Emperor's Vanguard": '(XLN) 189', 'Sleek Schooner': '(XLN) 247', 'Goring Ceratops': '(XLN) 13',
              'Priest of the Wakening Sun': '(XLN) 27', 'Deeproot Waters': '(XLN) 51', 'Spell Pierce': '(XLN) 81',
              'Pillar of Origins': '(XLN) 241', "Castaway's Despair": '(XLN) 281', "Jace's Sentinel": '(XLN) 283',
              'Territorial Hammerskull': '(XLN) 41', 'Dive Down': '(XLN) 53', "Angrath's Marauders": '(XLN) 132',
              "Burning Sun's Avatar": '(XLN) 135', 'Raptor Hatchling': '(XLN) 155', 'Snapping Sailback': '(XLN) 208',
              'Grasping Current': '(XLN) 282', 'Imperial Aerosaur': '(XLN) 14', 'Fleet Swallower': '(XLN) 57',
              'Captivating Crew': '(XLN) 137', 'Deeproot Champion': '(XLN) 185', 'Raging Swordtooth': '(XLN) 226',
              'Sky Terror': '(XLN) 229', "Lookout's Dispersal": '(XLN) 62', "Raiders' Wake": '(XLN) 116',
              'Vicious Conquistador': '(XLN) 128', 'Fiery Cannonade': '(XLN) 143', 'Sword-Point Diplomacy': '(XLN) 126',
              'Call to the Feast': '(XLN) 219', 'Fell Flagship': '(XLN) 238', 'Deadeye Tracker': '(XLN) 99',
              'Ruin Raider': '(XLN) 118', 'Sheltering Light': '(XLN) 35', 'Drover of the Mighty': '(XLN) 187',
              'Wildgrowth Walker': '(XLN) 216', 'Ashes of the Abhorrent': '(XLN) 2', 'Kitesail Freebooter': '(XLN) 110',
              'Captain Lannery Storm': '(XLN) 136', 'Ranging Raptors': '(XLN) 201', 'Adanto Vanguard': '(XLN) 1',
              'Fathom Fleet Captain': '(XLN) 106', 'Merfolk Branchwalker': '(XLN) 197', "(XLN)'s Binding": '(XLN) 17',
              "Arguel's Blood Fast": '(XLN) 90', 'Temple of Aclazotz': '(XLN) 90', 'Deathgorge Scavenger': '(XLN) 184',
              "Conqueror's Galleon": '(XLN) 234', "Conqueror's Foothold": '(XLN) 234', 'Bishop of Rebirth': '(XLN) 5',
              'Entrancing Melody': '(XLN) 55', 'Otepec Huntmaster': '(XLN) 153', 'Rowdy Crew': '(XLN) 159',
              'Kopala, Warden of Waves': '(XLN) 61', 'Rile': '(XLN) 158', 'Bloodcrazed Paladin': '(XLN) 93',
              "Vance's Blasting Cannons": '(XLN) 173', 'Spitfire Bastion': '(XLN) 173', 'Boneyard Parley': '(XLN) 94',
              "Verdant Sun's Avatar": '(XLN) 213', 'Tocatli Honor Guard': '(XLN) 42', 'Chart a Course': '(XLN) 48',
              'Overflowing Insight': '(XLN) 66', 'Arcane Adaptation': '(XLN) 46', "River's Rebuke": '(XLN) 71',
              'Axis of Mortality': '(XLN) 3', 'Sun-Blessed Mount': '(XLN) 288', "Kinjalli's Sunwing": '(XLN) 19',
              'Spell Swindle': '(XLN) 82', 'Herald of Secret Streams': '(XLN) 59', 'Dowsing Dagger': '(XLN) 235',
              'Lost Vale': '(XLN) 235', "Sunbird's Invocation": '(XLN) 165', 'Admiral Beckett Brass': '(XLN) 217',
              'Dire Fleet Ravager': '(XLN) 104', 'Mavren Fein, Dusk Apostle': '(XLN) 24',
              'Revel in Riches': '(XLN) 117', 'Regisaur Alpha': '(XLN) 227', "Shapers' Sanctuary": '(XLN) 206',
              'Rampaging Ferocidon': '(XLN) 154', 'Sanctum Seeker': '(XLN) 120',
              'Tishana, Voice of Thunder': '(XLN) 230', "Wakening Sun's Avatar": '(XLN) 44',
              "Vraska's Contempt": '(XLN) 129', 'Siren Stormtamer': '(XLN) 79', 'Ripjaw Raptor': '(XLN) 203',
              'Settle the Wreckage': '(XLN) 34', 'Vraska, Relic Seeker': '(XLN) 232',
              'Jace, Cunning Castaway': '(XLN) 60', 'Thaumatic Compass': '(XLN) 249', 'Spires of Orazca': '(XLN) 249',
              "Legion's Landing": '(XLN) 22', 'Adanto, the First Fort': '(XLN) 22', 'Star of Extinction': '(XLN) 161',
              'Unclaimed Territory': '(XLN) 258', 'Treasure Map': '(XLN) 250', 'Treasure Cove': '(XLN) 250',
              'Huatli, Warrior Poet': '(XLN) 224', 'Hostage Taker': '(XLN) 223', "Gishath, Sun's Avatar": '(XLN) 222',
              'Vona, Butcher of Magan': '(XLN) 231', 'Sunpetal Grove': '(XLN) 257', 'Dragonskull Summit': '(XLN) 252',
              'Primal Amulet': '(XLN) 243', 'Primal Wellspring': '(XLN) 243', 'Rootbound Crag': '(XLN) 256',
              "Vanquisher's Banner": '(XLN) 251', 'Field of Ruin': '(XLN) 254', 'Glacial Fortress': '(XLN) 255',
              'Jace, Ingenious Mind-Mage': '(XLN) 280', 'Huatli, Dinosaur Knight': '(XLN) 285',
              'Drowned Catacomb': '(XLN) 253', 'Growing Rites of Itlimoc': '(XLN) 191',
              'Itlimoc, Cradle of the Sun': '(XLN) 191', 'Carnage Tyrant': '(XLN) 179',
              'Search for Azcanta': '(XLN) 74', 'Azcanta, the Sunken Ruin': '(XLN) 74'}
