rarity = {'Forest': "Basic Land",
          'Swamp': "Basic Land",
          'Mountain': "Basic Land",
          'Plains': "Basic Land",
          'Island': "Basic Land",
          'Aven Sentry': 'Common',
          'Charge': 'Common',
          "D'Avenant Trapper": 'Common', 'Pegasus Courser': 'Common',
          'Academy Journeymage': 'Common', 'Arcane Flight': 'Common', 'Befuddle': 'Common', 'Relic Runner': 'Common',
          'Drudge Sentinel': 'Common', 'Fire Elemental': 'Common', 'Keldon Raider': 'Common',
          'Rampaging Cyclops': 'Common',
          'Aesthir Glider': 'Common', 'Juggernaut': 'Uncommon', 'Excavation Elephant': 'Common',
          'Sergeant-at-Arms': 'Common',
          'Serra Disciple': 'Common', 'Academy Drake': 'Common', 'Cloudreader Sphinx': 'Common',
          'Cold-Water Snapper': 'Common',
          'Divination': 'Common', 'Tolarian Scholar': 'Common', 'Fiery Intervention': 'Common',
          'Arbor Armament': 'Common',
          "Gaea's Protector": 'Common', 'Pierce the Sky': 'Common', 'Bloodtallow Candle': 'Common',
          'Guardians of Koilos': 'Common', 'Sparring Construct': 'Common', 'Mesa Unicorn': 'Common',
          'Sanctum Spirit': 'Uncommon', 'Tragic Poet': 'Common', 'Rescue': 'Common', 'Cabal Paladin': 'Common',
          'Stronghold Confessor': 'Common', 'Bloodstone Goblin': 'Common', 'Keldon Warcaller': 'Common',
          'Skizzik': 'Uncommon',
          'Adventurous Impulse': 'Common', 'Baloth Gorger': 'Common', 'Corrosive Ooze': 'Common',
          'Llanowar Envoy': 'Common',
          'Howling Golem': 'Uncommon', "Navigator's Compass": 'Common', 'Pardic Wanderer': 'Common',
          'Short Sword': 'Common',
          'Blessed Light': 'Common', 'Homarid Explorer': 'Common', 'Sage of Lat-Nam': 'Uncommon',
          'Sentinel of the Pearl Trident': 'Uncommon', 'Cabal Evangel': 'Common', 'Lingering Phantom': 'Uncommon',
          'Windgrace Acolyte': 'Common', 'Goblin Barrage': 'Uncommon', 'Shivan Fire': 'Common',
          'Saproling Migration': 'Common',
          'Jousting Lance': 'Common', 'Pyromantic Pilgrim': 'Common', "Gideon's Reproach": 'Common',
          'Knight of New Benalia': 'Common', 'Deep Freeze': 'Common', 'Diligent Excavator': 'Uncommon',
          'Syncopate': 'Common',
          'Vodalian Arcanist': 'Common', 'Weight of Memory': 'Uncommon', 'Caligo Skin-Witch': 'Common',
          'Dark Bargain': 'Common',
          'Deathbloom Thallid': 'Common', 'Fungal Infection': 'Common', 'Thallid Omnivore': 'Common',
          'Yargle, Glutton of Urborg': 'Uncommon', 'Firefist Adept': 'Uncommon', 'Frenzied Rage': 'Common',
          "Nature's Spiral": 'Uncommon', "Mishra's Self-Replicator": 'Rare', 'Voltaic Servant': 'Common',
          'Timber Gorge': 'Common', 'Call the Cavalry': 'Common', 'Dub': 'Common', 'Serra Angel': 'Uncommon',
          'Triumph of Gerrard': 'Uncommon', 'Fervent Strike': 'Common', 'Ghitu Journeymage': 'Common',
          'Haphazard Bombardment': 'Rare', 'Keldon Overseer': 'Common', 'Radiating Lightning': 'Common',
          'Warcry Phoenix': 'Uncommon', 'Krosan Druid': 'Common', 'Wild Onslaught': 'Uncommon',
          'Shield of the Realm': 'Uncommon', "Urza's Tome": 'Uncommon', 'Memorial to Glory': 'Uncommon',
          "Teferi's Sentinel": 'Uncommon', 'Meandering River': 'Common', 'Daring Archaeologist': 'Rare',
          'Healing Grace': 'Common', 'Time of Ice': 'Uncommon', 'Divest': 'Common', 'Eviscerate': 'Common',
          'Vicious Offering': 'Common', 'Orcish Vandal': 'Uncommon', 'Seismic Shift': 'Common',
          'Grunn, the Lonely King': 'Uncommon', 'Thorn Elemental': 'Uncommon', "Sorcerer's Wand": 'Uncommon',
          'Benalish Honor Guard': 'Common', 'Thallid Soothsayer': 'Uncommon', 'Elfhame Druid': 'Uncommon',
          "Gaea's Blessing": 'Uncommon', 'Gift of Growth': 'Common', 'Verdant Force': 'Rare',
          'Yavimaya Sapherd': 'Common',
          'Rona, Disciple of Gix': 'Uncommon', "Tiana, Ship's Caretaker": 'Uncommon', 'Icy Manipulator': 'Uncommon',
          'Powerstone Shard': 'Common', 'Memorial to Unity': 'Uncommon', 'Memorial to War': 'Uncommon',
          'Temporal Machinations': 'Common', 'Kwende, Pride of Femeref': 'Uncommon', "Curator's Ward": 'Uncommon',
          'Blessing of Belzenlok': 'Common', "Chainer's Torment": 'Uncommon', 'Champion of the Flame': 'Uncommon',
          'The First Eruption': 'Rare', 'Ghitu Chronicler': 'Common', 'Run Amok': 'Common',
          'Untamed Kavu': 'Uncommon',
          "Shanna, Sisay's Legacy": 'Uncommon', 'Adamant Will': 'Common', 'Board the Weatherlight': 'Uncommon',
          'Evra, Halcyon Witness': 'Rare', "On Serra's Wings": 'Uncommon', "In Bolas's Clutches": 'Uncommon',
          'Demonic Vigor': 'Common', 'Fight with Fire': 'Uncommon', 'Skirk Prospector': 'Common',
          'Two-Headed Giant': 'Rare',
          'Ancient Animus': 'Common', 'Llanowar Elves': 'Common', 'Hallar, the Firefletcher': 'Uncommon',
          'Karplusan Hound': 'Uncommon', 'Settle the Score': 'Uncommon', 'Ghitu Lavarunner': 'Common',
          'Grow from the Ashes': 'Common', 'Spore Swarm': 'Uncommon', 'Zhalfirin Void': 'Uncommon',
          'Baird, Steward of Argive': 'Uncommon', "Artificer's Assistant": 'Common', 'Blink of an Eye': 'Common',
          'Unwind': 'Common', 'Knight of Malice': 'Uncommon', 'Garna, the Bloodflame': 'Uncommon',
          'Amaranthine Wall': 'Uncommon', 'Skittering Surveyor': 'Common', 'Memorial to Folly': 'Uncommon',
          'Memorial to Genius': 'Uncommon', 'Slinn Voda, the Rising Deep': 'Uncommon', 'Final Parting': 'Uncommon',
          'Urgoros, the Empty One': 'Uncommon', 'Whisper, Blood Liturgist': 'Uncommon',
          'Valduk, Keeper of the Flame': 'Uncommon', 'Llanowar Scout': 'Common', 'Sporecrown Thallid': 'Uncommon',
          "Raff Capashen, Ship's Mage": 'Uncommon', 'Slimefoot, the Stowaway': 'Uncommon',
          'Knight of Grace': 'Uncommon',
          'Zahid, Djinn of the Lamp': 'Rare', "Jhoira's Familiar": 'Uncommon', 'Niambi, Faithful Healer': 'Rare',
          'Dauntless Bodyguard': 'Uncommon', 'Fall of the Thran': 'Rare', 'Precognition Field': 'Rare',
          "Warlord's Fury": 'Common', 'Fungal Plots': 'Uncommon', 'Kazarov, Sengir Pureblood': 'Rare',
          "Kamahl's Druidic Vow": 'Rare', 'Adeliz, the Cinder Wind': 'Uncommon', 'Arvad the Cursed': 'Uncommon',
          'Naban, Dean of Iteration': 'Rare', "Lich's Mastery": 'Rare', 'Rite of Belzenlok': 'Rare',
          'Torgaar, Famine Incarnate': 'Rare', 'Goblin Warchief': 'Uncommon', 'Territorial Allosaurus': 'Rare',
          'Tatyova, Benthic Druid': 'Uncommon', "Chandra's Outburst": 'Rare', 'Seal Away': 'Uncommon',
          'The Mirari Conjecture': 'Rare', 'Cast Down': 'Uncommon', 'Broken Bond': 'Common',
          'Grand Warlord Radha': 'Rare',
          'Danitha Capashen, Paragon': 'Uncommon', 'Dread Shade': 'Rare', "Jaya's Immolating Inferno": 'Rare',
          "Wizard's Lightning": 'Uncommon', 'Jodah, Archmage Eternal': 'Rare', "Forebear's Blade": 'Rare',
          "Teshar, Ancestor's Apostle": 'Rare', 'Tetsuko Umezawa, Fugitive': 'Uncommon',
          "Yawgmoth's Vile Offering": 'Rare',
          'The Flame of Keld': 'Uncommon', 'Aryel, Knight of Windgrace': 'Rare',
          "Primevals' Glorious Rebirth": 'Rare',
          'Rat Colony': 'Common', 'Squee, the Immortal': 'Rare', 'Traxos, Scourge of Kroog': 'Rare',
          'The Antiquities War': 'Rare', 'Song of Freyalise': 'Uncommon', 'Benalish Marshal': 'Rare',
          "Karn's Temporal Sundering": 'Rare', 'The Eldest Reborn': 'Uncommon', 'Marwyn, the Nurturer': 'Rare',
          'Josu Vess, Lich Knight': 'Rare', "Wizard's Retort": 'Uncommon', 'Sylvan Awakening': 'Rare',
          "Urza's Ruinous Blast": 'Rare', 'Thran Temporal Gateway': 'Rare', 'Siege-Gang Commander': 'Rare',
          'Blackblade Reforged': 'Rare', 'Oath of Teferi': 'Rare', 'Goblin Chainwhirler': 'Rare',
          'Naru Meha, Master Wizard': 'Mythic', 'Darigaaz Reincarnated': 'Mythic', 'Tempest Djinn': 'Rare',
          'Weatherlight': 'Mythic', 'Merfolk Trickster': 'Uncommon', 'Demonlord Belzenlok': 'Mythic',
          'Cabal Stronghold': 'Rare',
          'Verix Bladewing': 'Mythic', 'Steel Leaf Champion': 'Rare', 'Phyrexian Scriptures': 'Mythic',
          'Jaya Ballard': 'Mythic',
          'Jhoira, Weatherlight Captain': 'Mythic', 'Damping Sphere': 'Uncommon',
          "Multani, Yavimaya's Avatar": 'Mythic',
          'Shalai, Voice of Plenty': 'Rare', 'Gilded Lotus': 'Rare', 'Woodland Cemetery': 'Rare',
          'History of Benalia': 'Mythic',
          'Sulfur Falls': 'Rare', 'Clifftop Retreat': 'Rare', 'Isolated Chapel': 'Rare',
          'Teferi, Timebender': 'Mythic',
          'Muldrotha, the Gravetide': 'Mythic', 'Helm of the Host': 'Rare', 'Chandra, Bold Pyromancer': 'Mythic',
          'Hinterland Harbor': 'Rare', 'Lyra Dawnbringer': 'Mythic', 'Karn, Scion of Urza': 'Mythic',
          'Mox Amber': 'Mythic',
          'Teferi, Hero of (DAR)': 'Mythic', 'The Mending of (DAR)': 'Rare', 'Firesong and Sunspeaker': 'Rare',
          'Acclaimed Contender': 'Rare', 'All That Glitters': 'Uncommon', 'Archon of Absolution': 'Uncommon',
          'Ardenvale Paladin': 'Common', 'Ardenvale Tactician': 'Common', 'Dizzying Swoop': 'Common',
          'Bartered Cow': 'Common',
          'Beloved Princess': 'Common', 'Charming Prince': 'Rare', 'The Circle of Loyalty': 'Mythic',
          'Deafening Silence': 'Uncommon', 'Faerie Guidemother': 'Common', 'Gift of the Fae': 'Common',
          'Flutterfox': 'Common',
          'Fortifying Provisions': 'Common', 'Giant Killer': 'Rare', 'Chop Down': 'Rare', 'Glass Casket': 'Uncommon',
          'Happily Ever After': 'Rare', 'Harmonious Archon': 'Mythic', 'Hushbringer': 'Rare',
          'Knight of the Keep': 'Common',
          'Linden, the Steadfast Queen': 'Rare', 'Lonesome Unicorn': 'Common', 'Rider in Need': 'Common',
          'Mysterious Pathlighter': 'Uncommon', 'Outflank': 'Common', 'Prized Griffin': 'Common',
          'Rally for the Throne': 'Uncommon', 'Realm-Cloaked Giant': 'Mythic', 'Cast Off': 'Mythic',
          'Righteousness': 'Uncommon',
          'Shepherd of the Flock': 'Uncommon', 'Usher to Safety': 'Uncommon', 'Shining Armor': 'Common',
          'Silverflame Ritual': 'Common', 'Silverflame Squire': 'Common', 'On Alert': 'Common',
          "Syr Alin, the Lion's Claw": 'Uncommon', 'Trapped in the Tower': 'Common', "True Love's Kiss": 'Common',
          'Venerable Knight': 'Uncommon', 'Worthy Knight': 'Rare', 'Youthful Knight': 'Common',
          'Animating Faerie': 'Uncommon',
          'Bring to Life': 'Uncommon', 'Brazen Borrower': 'Mythic', 'Brazen Borrower // Petty Theft': 'Mythic',
          'Charmed Sleep': 'Common',
          'Corridor Monitor': 'Common', "Didn't Say Please": 'Common', 'Emry, Lurker of the Loch': 'Rare',
          'Fae of Wishes': 'Rare', 'Granted': 'Rare', 'Faerie Vandal': 'Uncommon', 'Folio of Fancies': 'Rare',
          'Frogify': 'Uncommon', 'Gadwick, the Wizened': 'Rare', 'Hypnotic Sprite': 'Uncommon',
          'Mesmeric Glare': 'Uncommon',
          'Into the Story': 'Uncommon', 'The Magic Mirror': 'Mythic', 'Mantle of Tides': 'Common',
          'Merfolk Secretkeeper': 'Common', 'Venture Deeper': 'Common', 'Midnight Clock': 'Rare',
          'Mirrormade': 'Rare',
          'Mistford River Turtle': 'Common', 'Moonlit Scavengers': 'Common', 'Mystical Dispute': 'Uncommon',
          'Opt': 'Common',
          'Overwhelmed Apprentice': 'Uncommon', 'Queen of Ice': 'Common', 'Rage of Winter': 'Common',
          'Run Away Together': 'Common', 'Sage of the Falls': 'Uncommon', 'So Tiny': 'Common',
          'Steelgaze Griffin': 'Common',
          'Stolen by the Fae': 'Rare', 'Syr Elenora, the Discerning': 'Uncommon', 'Tome Raider': 'Common',
          'Turn into a Pumpkin': 'Uncommon', 'Unexplained Vision': 'Common', 'Vantress Gargoyle': 'Rare',
          'Vantress Paladin': 'Common', 'Wishful Merfolk': 'Common', 'Witching Well': 'Common',
          'Ayara, First of Locthwain': 'Rare', 'Bake into a Pie': 'Common', 'Barrow Witches': 'Common',
          'Belle of the Brawl': 'Uncommon', 'Blacklance Paragon': 'Rare', 'Bog Naughty': 'Uncommon',
          'Cauldron Familiar': 'Uncommon', 'The Cauldron of Eternity': 'Mythic', "Cauldron's Gift": 'Uncommon',
          'Clackbridge Troll': 'Rare', 'Epic Downfall': 'Uncommon', 'Eye Collector': 'Common',
          'Festive Funeral': 'Common',
          'Foreboding Fruit': 'Common', 'Forever Young': 'Common', 'Foulmire Knight': 'Uncommon',
          'Profane Insight': 'Uncommon',
          "Giant's Skewer": 'Common', 'Lash of Thorns': 'Common', 'Locthwain Paladin': 'Common',
          'Lost Legion': 'Common',
          'Malevolent Noble': 'Common', 'Memory Theft': 'Common', 'Murderous Rider': 'Rare',
          'Murderous Rider // Swift End': 'Rare',
          'Oathsworn Knight': 'Rare', 'Order of Midnight': 'Uncommon', 'Alter Fate': 'Uncommon',
          'Piper of the Swarm': 'Rare',
          'Rankle, Master of Pranks': 'Mythic', 'Reaper of Night': 'Common', 'Harvest Fear': 'Common',
          'Reave Soul': 'Common',
          'Revenge of Ravens': 'Uncommon', 'Smitten Swordmaster': 'Common', 'Curry Favor': 'Common',
          "Specter's Shriek": 'Uncommon', 'Syr Konrad, the Grim': 'Uncommon', 'Tempting Witch': 'Common',
          'Wicked Guardian': 'Common', 'Wishclaw Talisman': 'Rare', "Witch's Vengeance": 'Rare', 'Barge In': 'Common',
          'Bloodhaze Wolverine': 'Common', 'Blow Your House Down': 'Common', 'Bonecrusher Giant': 'Rare',
          'Stomp': 'Rare',
          'Brimstone Trebuchet': 'Common', 'Burning-Yard Trainer': 'Uncommon', 'Claim the Firstborn': 'Uncommon',
          'Crystal Slipper': 'Common', 'Embercleave': 'Mythic', 'Embereth Paladin': 'Common',
          'Embereth Shieldbreaker': 'Uncommon', 'Battle Display': 'Uncommon', 'Ferocity of the Wilds': 'Uncommon',
          'Fervent Champion': 'Rare', 'Fires of Invention': 'Rare', 'Fling': 'Common', 'Irencrag Feat': 'Rare',
          'Irencrag Pyromancer': 'Rare', 'Joust': 'Uncommon', 'Mad Ratter': 'Uncommon',
          'Merchant of the Vale': 'Common',
          'Haggle': 'Common', 'Ogre Errant': 'Common', 'Opportunistic Dragon': 'Rare', 'Raging Redcap': 'Common',
          'Redcap Melee': 'Uncommon', 'Redcap Raiders': 'Common', 'Rimrock Knight': 'Common',
          'Boulder Rush': 'Common',
          'Robber of the Rich': 'Mythic', 'Scorching Dragonfire': 'Common', 'Searing Barrage': 'Common',
          'Seven Dwarves': 'Common', 'Skullknocker Ogre': 'Uncommon', 'Slaying Fire': 'Uncommon',
          'Sundering Stroke': 'Rare',
          'Syr Carah, the Bold': 'Uncommon', 'Thrill of Possibility': 'Common', 'Torbran, Thane of Red Fell': 'Rare',
          'Weaselback Redcap': 'Common', 'Beanstalk Giant': 'Uncommon', 'Fertile Footsteps': 'Uncommon',
          'Curious Pair': 'Common', 'Treats to Share': 'Common', 'Edgewall Innkeeper': 'Uncommon',
          'Feasting Troll King': 'Rare',
          'Fell the Pheasant': 'Common', 'Fierce Witchstalker': 'Common', 'Flaxen Intruder': 'Uncommon',
          'Welcome Home': 'Uncommon', 'Garenbrig Carver': 'Common', "Shield's Might": 'Common',
          'Garenbrig Paladin': 'Common',
          'Garenbrig Squire': 'Common', 'Giant Opportunity': 'Uncommon', 'Gilded Goose': 'Rare',
          'The Great Henge': 'Mythic',
          'Insatiable Appetite': 'Common', 'Keeper of Fables': 'Uncommon', "Kenrith's Transformation": 'Uncommon',
          'Lovestruck Beast': 'Rare', "Lovestruck Beast // Heart's Desire": 'Rare', 'Maraleaf Rider': 'Common',
          'Oakhame Adversary': 'Uncommon',
          'Once and Future': 'Uncommon', 'Once Upon a Time': 'Rare', 'Outmuscle': 'Common',
          'Questing Beast': 'Mythic',
          'Return of the Wildspeaker': 'Rare', 'Return to Nature': 'Common', 'Rosethorn Acolyte': 'Common',
          'Seasonal Ritual': 'Common', 'Rosethorn Halberd': 'Common', 'Sporecap Spider': 'Common',
          'Syr Faren, the Hengehammer': 'Uncommon', 'Tall as a Beanstalk': 'Common', 'Trail of Crumbs': 'Uncommon',
          'Tuinvale Treefolk': 'Common', 'Oaken Boon': 'Common', 'Wicked Wolf': 'Rare', 'Wildborn Preserver': 'Rare',
          'Wildwood Tracker': 'Common', "Wolf's Quarry": 'Common', 'Yorvo, Lord of Garenbrig': 'Rare',
          'Dance of the Manse': 'Rare', 'Doom Foretold': 'Rare', 'Drown in the Loch': 'Uncommon',
          'Escape to the Wilds': 'Rare',
          'Faeburrow Elder': 'Rare', 'Garruk, Cursed Huntsman': 'Mythic', 'Grumgully, the Generous': 'Uncommon',
          'Improbable Alliance': 'Uncommon', 'Inspiring Veteran': 'Uncommon', 'Lochmere Serpent': 'Rare',
          'Maraleaf Pixie': 'Uncommon', 'Oko, Thief of Crowns': 'Mythic', "Outlaws' Merriment": 'Mythic',
          'The Royal Scions': 'Mythic', 'Savvy Hunter': 'Uncommon', 'Shinechaser': 'Uncommon',
          'Steelclaw Lance': 'Uncommon',
          'Stormfist Crusader': 'Rare', 'Wandermare': 'Uncommon', 'Wintermoor Commander': 'Uncommon',
          "Arcanist's Owl": 'Uncommon', 'Covetous Urge': 'Uncommon', 'Deathless Knight': 'Uncommon',
          'Elite Headhunter': 'Uncommon', 'Fireborn Knight': 'Uncommon', 'Loch Dragon': 'Uncommon',
          'Oakhame Ranger': 'Uncommon',
          'Bring Back': 'Uncommon', 'Rampart Smasher': 'Uncommon', 'Resolute Rider': 'Uncommon',
          'Thunderous Snapper': 'Uncommon', 'Clockwork Servant': 'Uncommon', 'Crashing Drawbridge': 'Common',
          'Enchanted Carriage': 'Uncommon', 'Gingerbrute': 'Common', 'Golden Egg': 'Common', 'Henge Walker': 'Common',
          'Heraldic Banner': 'Uncommon', 'Inquisitive Puppet': 'Uncommon', 'Jousting Dummy': 'Common',
          'Locthwain Gargoyle': 'Common', 'Lucky Clover': 'Uncommon', 'Prophet of the Peak': 'Common',
          'Roving Keep': 'Common',
          'Scalding Cauldron': 'Common', 'Shambling Suit': 'Uncommon', 'Signpost Scarecrow': 'Common',
          "Sorcerer's Broom": 'Uncommon', 'Sorcerous Spyglass': 'Rare', 'Spinning Wheel': 'Uncommon',
          'Stonecoil Serpent': 'Rare', 'Weapon Rack': 'Common', "Witch's Oven": 'Uncommon',
          'Castle Ardenvale': 'Rare',
          'Castle Embereth': 'Rare', 'Castle Garenbrig': 'Rare', 'Castle Locthwain': 'Rare',
          'Castle Vantress': 'Rare',
          'Dwarven Mine': 'Common', 'Fabled Passage': 'Rare', 'Gingerbread Cabin': 'Common',
          'Idyllic Grange': 'Common',
          'Mystic Sanctuary': 'Common', 'Tournament Grounds': 'Uncommon', "Witch's Cottage": 'Common',
          'Kenrith, the Returned King': 'Mythic', 'Rowan, Fearless Sparkmage': 'Mythic', 'Garrison Griffin': 'Common',
          "Rowan's Battleguard": 'Uncommon', "Rowan's Stalwarts": 'Rare', 'Oko, the Trickster': 'Mythic',
          "Oko's Accomplices": 'Common', 'Bramblefort Fink': 'Uncommon', "Oko's Hospitality": 'Rare',
          'Mace of the Valiant': 'Rare', 'Silverwing Squadron': 'Rare', 'Faerie Formation': 'Rare',
          'Shimmer Dragon': 'Rare',
          'Workshop Elders': 'Rare', 'Chittering Witch': 'Rare', 'Taste of Death': 'Rare',
          'Embereth Skyblazer': 'Rare',
          'Steelbane Hydra': 'Rare', 'Thorn Mammoth': 'Rare', 'Alela, Artful Provocateur': 'Mythic',
          'Banish into Fable': 'Rare',
          'Chulane, Teller of Tales': 'Mythic', 'Gluttonous Troll': 'Rare', "Knights' Charge": 'Rare',
          'Korvold, Fae-Cursed King': 'Mythic', 'Syr Gwyn, Hero of Ashvale': 'Mythic', 'Arcane Signet': 'Common',
          'Tome of Legends': 'Rare', 'Command Tower': 'Common', 'Collar the Culprit': 'Common',
          'Intrusive Packbeast': 'Common',
          'Dazzling Lights': 'Common', 'Wishcoin Crab': 'Common', 'Rubblebelt Boar': 'Common',
          'Sure Strike': 'Common',
          'Devkarin Dissident': 'Common', 'Prey Upon': 'Common', 'Wild Ceratok': 'Common',
          'Garrison Sergeant': 'Common',
          'Fresh-Faced Recruit': 'Common', 'Piston-Fist Cyclops': 'Common', 'Blade Instructor': 'Common',
          'Parhelion Patrol': 'Common', 'Roc Charger': 'Uncommon', 'Skyline Scout': 'Common',
          'Child of Night': 'Common',
          'Douser of Lights': 'Common', 'Never Happened': 'Common', 'Barging Sergeant': 'Common',
          "Pack's Favor": 'Common',
          'Wary Okapi': 'Common', 'Hammer Dropper': 'Common', 'Rosemane Centaur': 'Common',
          'Sumala Woodshaper': 'Common',
          'Inspiring Unicorn': 'Uncommon', 'Ledev Guardian': 'Common', 'Luminous Bonds': 'Common',
          'Tenth District Guard': 'Common', 'Leapfrog': 'Common', 'Vedalken Mesmerist': 'Common',
          'Wall of Mist': 'Common',
          'Watcher in the Mist': 'Common', 'Spinal Centipede': 'Common', 'Command the Storm': 'Common',
          'Goblin Locksmith': 'Common', 'Ornery Goblin': 'Common', 'Wojek Bodyguard': 'Common',
          'Portcullis Vine': 'Common',
          'Siege Wurm': 'Common', 'Vigorspore Wurm': 'Common', 'Centaur Peacemaker': 'Common',
          'Vernadi Shieldmate': 'Common',
          'Flight of Equenauts': 'Uncommon', 'Loxodon Restorer': 'Common', 'Righteous Blow': 'Common',
          'Capture Sphere': 'Common', 'Selective Snare': 'Uncommon', 'Deadly Visit': 'Common',
          'Undercity Necrolisk': 'Uncommon',
          'Whispering Snitch': 'Uncommon', 'Cosmotronic Wave': 'Common', 'Fearless Halberdier': 'Common',
          'Hellkite Whelp': 'Uncommon', 'Ironshell Beetle': 'Common', 'Artful Takedown': 'Common',
          'Undercity Uprising': 'Common', 'Pitiless Gorgon': 'Common', 'Rampaging Monument': 'Uncommon',
          'Gateway Plaza': 'Common', 'Golgari Guildgate': 'Common', 'Candlelight Vigil': 'Common',
          'Hunted Witness': 'Common',
          'Dimir Informant': 'Common', 'Disdainful Stroke': 'Common', 'Bartizan Bats': 'Common',
          'Severed Strands': 'Common',
          'Fire Urchin': 'Common', 'Gravitic Punch': 'Common', 'Torch Courier': 'Common',
          'Hitchclaw Recluse': 'Common',
          'Join Shields': 'Uncommon', 'Skyknight Legionnaire': 'Common', 'Wee Dragonauts': 'Uncommon',
          'Worldsoul Colossus': 'Uncommon', 'Invert': 'Uncommon', 'Invent': 'Uncommon', 'Selesnya Locket': 'Common',
          'Boros Guildgate': 'Common', 'Dimir Guildgate': 'Common', 'Selesnya Guildgate': 'Common',
          'Sunhome Stalwart': 'Uncommon', 'Muse Drake': 'Common', 'Passwall Adept': 'Common',
          'Radical Idea': 'Common',
          'Unexplained Disappearance': 'Common', 'Kraul Swarm': 'Uncommon', 'Veiled Shade': 'Common',
          'Vicious Rumors': 'Common',
          'Direct Current': 'Common', 'Maximize Velocity': 'Common', 'Arboretum Elemental': 'Uncommon',
          'Pause for Reflection': 'Common', 'Sprouting Renewal': 'Uncommon', 'Beacon Bolt': 'Uncommon',
          'Conclave Cavalier': 'Uncommon', 'Conclave Guildmage': 'Uncommon', 'Darkblade Agent': 'Common',
          'Erstwhile Trooper': 'Common', 'Goblin Electromancer': 'Common', 'Hypothesizzle': 'Common',
          'Nightveil Predator': 'Uncommon', 'Swarm Guildmage': 'Uncommon', 'Gatekeeper Gargoyle': 'Uncommon',
          'Izzet Guildgate': 'Common', 'Sworn Companions': 'Common', 'Take Heart': 'Common',
          'Citywatch Sphinx': 'Uncommon',
          'Maximize Altitude': 'Common', 'Hired Poisoner': 'Common', 'Book Devourer': 'Uncommon',
          'Inescapable Blaze': 'Uncommon', 'Smelt-Ward Minotaur': 'Uncommon', 'Affectionate Indrik': 'Uncommon',
          'Generous Stray': 'Common', 'Golgari Raiders': 'Uncommon', 'Kraul Foragers': 'Common',
          'Kraul Harpooner': 'Uncommon',
          'House Guildmage': 'Uncommon', 'Whisper Agent': 'Common', 'Dimir Locket': 'Common',
          'Glaive of the Guildpact': 'Uncommon', 'Golgari Locket': 'Common', 'Demotion': 'Uncommon',
          "Healer's Hawk": 'Common',
          'Barrier of Bones': 'Common', 'Burglar Rat': 'Common', 'Dead Weight': 'Common', 'Mephitic Vapors': 'Common',
          'Moodmark Painter': 'Common', 'Goblin Banneret': 'Uncommon', 'Bounty of Might': 'Rare',
          'District Guide': 'Uncommon',
          'Beamsplitter Mage': 'Uncommon', 'League Guildmage': 'Uncommon', 'Ledev Champion': 'Uncommon',
          'Legion Guildmage': 'Uncommon', 'Ochran Assassin': 'Uncommon', 'Sonic Assault': 'Common',
          'Izzet Locket': 'Common',
          'Gird for Battle': 'Uncommon', 'Enhanced Surveillance': 'Uncommon', 'Nightveil Sprite': 'Uncommon',
          'Vivid Revival': 'Rare', 'Molderhulk': 'Uncommon', 'Boros Locket': 'Common', 'Chamber Sentry': 'Rare',
          'Silent Dart': 'Uncommon', 'Haazda Marshal': 'Uncommon', 'Devious Cover-Up': 'Common',
          'Street Riot': 'Uncommon',
          'Hatchery Spider': 'Rare', 'Camaraderie': 'Rare', 'Dimir Spybug': 'Uncommon', 'Rhizome Lurcher': 'Common',
          'Swathcutter Giant': 'Uncommon', 'Flower // Flourish': 'Uncommon', 'Flourish': 'Uncommon',
          'Wand of Vertebrae': 'Uncommon', 'Blood Operative': 'Rare', 'Lotleth Giant': 'Uncommon',
          'Glowspore Shaman': 'Uncommon', 'Truefire Captain': 'Uncommon', 'Integrity': 'Uncommon',
          'Integrity // Intervention': 'Uncommon',
          'Intervention': 'Uncommon', 'Crush Contraband': 'Uncommon', 'Murmuring Mystic': 'Uncommon',
          'Omnispell Adept': 'Rare',
          'Thoughtbound Phantasm': 'Uncommon', 'Necrotic Wound': 'Uncommon', 'Pilfering Imp': 'Uncommon',
          'Erratic Cyclops': 'Rare', 'Grappling Sundew': 'Uncommon', 'Urban Utopia': 'Common',
          'Boros Challenger': 'Uncommon',
          'Golgari Findbroker': 'Uncommon', 'Light of the Legion': 'Rare', 'Price of Fame': 'Uncommon',
          'Crackling Drake': 'Uncommon', 'Notion Rain': 'Common', 'Bounty Agent': 'Rare',
          'Conclave Tribunal': 'Uncommon',
          'Disinformation Campaign': 'Uncommon', 'Justice Strike': 'Uncommon', 'Electrostatic Field': 'Uncommon',
          'Status': 'Uncommon', 'Status // Statue': 'Uncommon', "Firemind's Research": 'Rare', 'Assure': 'Rare',
          'Assure // Assemble': 'Rare', 'Citywide Bust': 'Rare', 'Guild Summit': 'Uncommon', 'Charnel Troll': 'Rare',
          'Gruesome Menagerie': 'Rare', 'Response': 'Rare', 'Response // Resurgence': 'Rare',
          "Chemister's Insight": 'Uncommon',
          'Goblin Cratermaker': 'Uncommon', 'Connive': 'Rare', 'Connive // Concoct': 'Rare',
          "Guildmages' Forum": 'Rare',
          'Find': 'Rare', 'Find // Finality': 'Rare', 'Drowned Secrets': 'Rare', 'Plaguecrafter': 'Uncommon',
          'Creeping Chill': 'Uncommon', 'Etrata, the Silencer': 'Rare', 'Circuitous Route': 'Uncommon',
          'Emmara, Soul of the Accord': 'Rare', 'Narcomoeba': 'Rare', 'Sinister Sabotage': 'Uncommon',
          'Quasiduplicate': 'Rare',
          'Lava Coil': 'Uncommon', 'Izoni, Thousand-Eyed': 'Rare', 'Swiftblade Vindicator': 'Rare',
          'Mausoleum Secrets': 'Rare',
          'Thought Erasure': 'Uncommon', 'Discovery': 'Uncommon', 'Discovery // Dispersal': 'Uncommon',
          "Tajic, Legion's Edge": 'Rare', 'Venerated Loxodon': 'Rare', 'Dawn of Hope': 'Rare',
          'Mnemonic Betrayal': 'Mythic',
          'Ritual of Soot': 'Rare', 'Runaway Steam-Kin': 'Rare', 'Ionize': 'Rare', 'Chance for Glory': 'Mythic',
          'Deafening Clarion': 'Rare', 'Unmoored Ego': 'Rare', 'Mission Briefing': 'Rare', 'Dream Eater': 'Mythic',
          'Niv-Mizzet, Parun': 'Rare', 'Experimental Frenzy': 'Rare', 'Pelt Collector': 'Rare',
          'Lazav, the Multifarious': 'Mythic', 'Expansion': 'Rare', 'Expansion // Explosion': 'Rare',
          'Trostani Discordant': 'Mythic', 'Underrealm Lich': 'Mythic', 'Midnight Reaper': 'Rare',
          'Beast Whisperer': 'Rare',
          'Nullhide Ferox': 'Mythic', 'Thousand-Year Storm': 'Mythic', 'Risk Factor': 'Rare',
          'Thief of Sanity': 'Rare',
          'March of the Multitudes': 'Mythic', 'Ral, Izzet Viceroy': 'Mythic',
          'Aurelia, Exemplar of Justice': 'Mythic',
          'Knight of Autumn': 'Rare', 'Legion Warboss': 'Rare', 'Chromatic Lantern': 'Rare',
          'Doom Whisperer': 'Mythic',
          'Divine Visitation': 'Mythic', 'Vraska, Golgari Queen': 'Mythic', 'Overgrown Tomb': 'Rare',
          'Temple Garden': 'Rare',
          'Sacred Foundry': 'Rare', 'Arclight Phoenix': 'Mythic', 'Steam Vents': 'Rare', 'Watery Grave': 'Rare',
          "Assassin's Trophy": 'Rare', 'Ral, Caller of Storms': 'Mythic', "Ral's Dispersal": 'Rare',
          'Precision Bolt': 'Common',
          "Ral's Staticaster": 'Uncommon', 'Vraska, Regal Gorgon': 'Mythic', 'Kraul Raider': 'Common',
          'Attendant of Vraska': 'Uncommon', "Vraska's Stoneglare": 'Rare', 'Impervious Greatwurm': 'Mythic',
          'Loxodon Line Breaker': 'Common', 'Star-Crowned Stag': 'Common', 'Bone to Ash': 'Uncommon',
          'Dwindle': 'Common',
          'Uncomfortable Chill': 'Common', 'Mind Rot': 'Common', 'Boggart Brute': 'Common',
          'Hostile Minotaur': 'Common',
          'Lava Axe': 'Common', 'Tectonic Rift': 'Uncommon', 'Daggerback Basilisk': 'Common', 'Oakenform': 'Common',
          'Herald of Faith': 'Uncommon', 'Knightly Valor': 'Uncommon', 'Trusty Packbeast': 'Common',
          'Gearsmith Prodigy': 'Common', 'Scholar of Stars': 'Common', 'Bogstomper': 'Common',
          'Gravedigger': 'Uncommon',
          'Hired Blade': 'Common', "Lich's Caress": 'Common', 'Bristling Boar': 'Common',
          'Declare Dominance': 'Uncommon',
          'Ghirapur Guide': 'Uncommon', 'Giant Spider': 'Common', 'Plummet': 'Common', 'Wall of Vines': 'Common',
          'Psychic Symbiont': 'Uncommon', 'Gallant Cavalry': 'Common', 'Invoke the Divine': 'Common',
          'Knight of the Tusk': 'Common', 'Cancel': 'Common', 'Skilled Animator': 'Uncommon',
          'Snapping Drake': 'Common',
          'Switcheroo': 'Uncommon', 'Infernal Scarring': 'Common', 'Skymarch Bloodletter': 'Common',
          'Two-Headed Zombie': 'Common', 'Walking Corpse': 'Common', 'Onakke Ogre': 'Common',
          'Siegebreaker Giant': 'Uncommon',
          'Trumpet Blast': 'Common', 'Rhox Oracle': 'Common', 'Aerial Engineer': 'Uncommon',
          'Explosive Apparatus': 'Common',
          'Gargoyle Sentinel': 'Uncommon', 'Gearsmith Guardian': 'Common', 'Angel of the Dawn': 'Common',
          'Cavalry Drillmaster': 'Common', "Knight's Pledge": 'Common', 'Mighty Leap': 'Common',
          'Oreskos Swiftclaw': 'Common',
          'Revitalize': 'Common', 'Mystic Archaeologist': 'Rare', 'Sift': 'Uncommon', 'Plague Mare': 'Uncommon',
          'Rise from the Grave': 'Uncommon', 'Strangling Spores': 'Common', 'Electrify': 'Common',
          'Fiery Finish': 'Uncommon',
          'Havoc Devils': 'Common', 'Inferno Hellion': 'Uncommon', 'Sparktongue Dragon': 'Common',
          'Highland Game': 'Common',
          'Naturalize': 'Common', 'Recollect': 'Uncommon', 'Thornhide Wolves': 'Common',
          'Skyrider Patrol': 'Uncommon',
          'Dwarven Priest': 'Common', 'Rustwing Falcon': 'Common', 'Aviation Pioneer': 'Common',
          'Horizon Scholar': 'Uncommon',
          'Omenspeaker': 'Common', 'Doomed Dissenter': 'Common', 'Ravenous Harpy': 'Uncommon',
          'Skeleton Archer': 'Common',
          "Sovereign's Bite": 'Common', 'Dragon Egg': 'Uncommon', 'Druid of Horns': 'Uncommon',
          'Titanic Growth': 'Common',
          'Brawl-Bash Ogre': 'Uncommon', 'Manalith': 'Common', 'Isolate': 'Rare', 'Take Vengeance': 'Common',
          'Ghostform': 'Common', 'Infectious Horror': 'Common', 'Vampire Sovereign': 'Uncommon',
          'Lightning Mare': 'Uncommon',
          'Smelt': 'Common', 'Viashino Pyromancer': 'Common', 'Volcanic Dragon': 'Uncommon',
          'Blanchwood Armor': 'Uncommon',
          'Vigilant Baloth': 'Uncommon', 'Arcane Encyclopedia': 'Uncommon', 'Field Creeper': 'Common',
          'Millstone': 'Uncommon',
          'Foul Orchard': 'Common', 'Tranquil Expanse': 'Common', 'Shield Mare': 'Uncommon',
          'Abnormal Endurance': 'Common',
          'Catalyst Elemental': 'Common', 'Goblin Motivator': 'Common', 'Gift of Paradise': 'Uncommon',
          'Prodigious Growth': 'Rare', 'Rupture Spire': 'Uncommon', 'Gravewaker': 'Rare', 'Novice Knight': 'Uncommon',
          'Aven Wind Mage': 'Common', 'Disperse': 'Common', 'Essence Scatter': 'Common',
          'Salvager of Secrets': 'Common',
          'Blood Divination': 'Uncommon', 'Vampire Neonate': 'Common', 'Druid of the Cowl': 'Common',
          'Ghastbark Twins': 'Uncommon', "Vivien's Invocation": 'Rare', 'Meteor Golem': 'Uncommon',
          'Suspicious Bookcase': 'Uncommon', 'Submerged Boneyard': 'Common', 'Aethershield Artificer': 'Uncommon',
          "Ajani's Last Stand": 'Rare', "Hieromancer's Cage": 'Uncommon', 'Make a Stand': 'Uncommon',
          'Aether Tunnel': 'Uncommon', 'Diregraf Ghoul': 'Uncommon', 'Macabre Waltz': 'Common',
          'Crash Through': 'Common',
          'Dryad Greenseeker': 'Uncommon', 'Elvish Rejuvenator': 'Common', 'Talons of Wildwood': 'Common',
          'Regal Bloodlord': 'Uncommon', 'Djinn of Wishes': 'Rare', 'Volley Veteran': 'Uncommon',
          'Draconic Disciple': 'Uncommon', "Rogue's Gloves": 'Uncommon', 'Skyscanner': 'Common',
          'Transmogrifying Wand': 'Rare',
          'Departed Deckhand': 'Uncommon', 'Surge Mare': 'Uncommon', 'Fell Specter': 'Uncommon',
          "Nightmare's Thirst": 'Uncommon', 'Reassembling Skeleton': 'Uncommon', 'Colossal Majesty': 'Uncommon',
          'Pelakka Wurm': 'Rare', 'Diamond Mare': 'Uncommon', 'Pendulum of Patterns': 'Common',
          'Ursine Champion': 'Common',
          'Goblin Instigator': 'Common', 'Heroic Reinforcements': 'Uncommon', 'Suncleanser': 'Rare',
          'Windreader Sphinx': 'Rare',
          'Dismissive Pyromancer': 'Rare', 'Tormenting Voice': 'Common', 'Lena, Selfless Champion': 'Rare',
          'Leonin Vanguard': 'Uncommon', 'Doublecast': 'Uncommon', 'Vine Mare': 'Uncommon',
          'Enigma Drake': 'Uncommon',
          "Vivien's Jaguar": 'Uncommon', 'Mirror Image': 'Uncommon', 'Sleep': 'Uncommon',
          'Fraying Omnipotence': 'Rare',
          'Guttersnipe': 'Uncommon', 'Thud': 'Uncommon', 'Amulet of Safekeeping': 'Rare',
          'Aegis of the Heavens': 'Uncommon',
          'Phylactery Lich': 'Rare', 'Militia Bugler': 'Uncommon', 'One with the Machine': 'Rare',
          'Exclusion Mage': 'Uncommon',
          'Metamorphic Alteration': 'Rare', 'Satyr Enchanter': 'Uncommon', 'Silverbeak Griffin': 'Common',
          'Arisen Gorgon': 'Uncommon', 'Shivan Dragon': 'Rare', 'Mistcaller': 'Rare', 'Infernal Reckoning': 'Rare',
          'Court Cleric': 'Uncommon', 'Riddlemaster Sphinx': 'Rare', "Tezzeret's Strider": 'Uncommon',
          "Liliana's Contract": 'Rare', 'Poison-Tip Archer': 'Uncommon', 'Spit Flame': 'Rare',
          "Magistrate's Scepter": 'Rare',
          'Sigiled Sword of Valeron': 'Rare', 'Patient Rebuilding': 'Rare', 'Demon of Catastrophes': 'Rare',
          "Serra's Guardian": 'Rare', 'Chaos Wand': 'Rare', 'Desecrated Tomb': 'Rare', "Liliana's Spoils": 'Rare',
          'Reclamation Sage': 'Uncommon', "Sarkhan's Dragonfire": 'Rare', 'Valiant Knight': 'Rare',
          'Dark-Dweller Oracle': 'Rare', 'Isareth the Awakener': 'Rare', 'Demanding Dragon': 'Rare',
          "Sarkhan's Whelp": 'Uncommon', 'Mentor of the Meek': 'Rare', 'Graveyard Marshal': 'Rare',
          'Kargan Dragonrider': 'Common', 'Tattered Mummy': 'Common', "Sarkhan's Unsealing": 'Rare',
          "Ajani's Influence": 'Rare',
          'Open the Graves': 'Rare', 'Thorn Lieutenant': 'Rare', "Tezzeret's Gatebreaker": 'Rare',
          'Skalla Wolf': 'Rare',
          'Hungering Hydra': 'Rare', 'Aggressive Mammoth': 'Rare', 'Remorseful Cleric': 'Rare',
          'Apex of Power': 'Mythic',
          'Fountain of Renewal': 'Uncommon', 'Detection Tower': 'Rare', 'Bone Dragon': 'Mythic',
          'Runic Armasaur': 'Rare',
          'Gigantosaurus': 'Rare', "Dragon's Hoard": 'Rare', 'Psychic Corrosion': 'Uncommon',
          'Goblin Trashmaster': 'Rare',
          'Palladia-Mors, the Ruiner': 'Mythic', 'Banefire': 'Rare', 'Chromium, the Mutable': 'Mythic',
          'Goreclaw, Terror of Qal Sisma': 'Rare', "Ajani's Welcome": 'Uncommon',
          'Vaevictis Asmadi, the Dire': 'Mythic',
          'Lathliss, Dragon Queen': 'Rare', 'Supreme Phantom': 'Rare', 'Cleansing Nova': 'Rare',
          'Leonin Warleader': 'Rare',
          'Reliquary Tower': 'Uncommon', 'Alpine Moon': 'Rare', "Stitcher's Supplier": 'Uncommon',
          'Elvish Clancaller': 'Rare',
          'Sai, Master Thopterist': 'Rare', 'Death Baron': 'Rare', 'Tezzeret, Cruel Machinist': 'Mythic',
          'Ajani, Adversary of Tyrants': 'Mythic', 'Liliana, Untouched by Death': 'Mythic', 'Vivien Reid': 'Mythic',
          'Sarkhan, Fireblood': 'Mythic', 'Arcades, the Strategist': 'Mythic', 'Tezzeret, Artifice Master': 'Mythic',
          'Omniscience': 'Mythic', 'Liliana, the Necromancer': 'Mythic', 'Ajani, Wise Counselor': 'Mythic',
          'Vivien of the Arkbow': 'Mythic', 'Resplendent Angel': 'Mythic', 'Sarkhan, Dragonsoul': 'Mythic',
          'Nicol Bolas, the Ravager': 'Mythic', 'Nicol Bolas, the Arisen': 'Mythic', 'Scapeshift': 'Mythic',
          'Crucible of Worlds': 'Mythic', 'Nexus of Fate': 'Mythic', 'Angelic Gift': 'Common',
          'Daybreak Chaplain': 'Common',
          'Glaring Aegis': 'Common', 'Inspired Charge': 'Common', 'Boreal Elemental': 'Common',
          'Fortress Crab': 'Common',
          'Frilled Sea Serpent': 'Common', 'Sleep Paralysis': 'Common', "Yarok's Wavecrasher": 'Uncommon',
          'Thought Distortion': 'Uncommon', 'Maniacal Rage': 'Common', 'Centaur Courser': 'Common',
          'Greenwood Sentinel': 'Common', 'Wolfkin Bond': 'Common', "Diviner's Lockbox": 'Uncommon',
          "Marauder's Axe": 'Common',
          'Retributive Wand': 'Uncommon', 'Stone Golem': 'Common', 'Master Splicer': 'Uncommon',
          'Moorland Inquisitor': 'Common',
          'Air Elemental': 'Uncommon', 'Frost Lynx': 'Common', 'Metropolis Sprite': 'Common',
          'Agonizing Syphon': 'Common',
          'Feral Abomination': 'Common', 'Undead Servant': 'Common', 'Uncaged Fury': 'Uncommon',
          'Feral Invocation': 'Common',
          'Growth Cycle': 'Common', 'Netcaster Spider': 'Common', 'Vorstclaw': 'Common',
          'Ogre Siegebreaker': 'Uncommon',
          'Pattern Matcher': 'Uncommon', 'Eternal Isolation': 'Uncommon', 'Griffin Sentinel': 'Common',
          'Moment of Heroism': 'Common', 'Soulmender': 'Common', 'Captivating Gyre': 'Uncommon',
          'Hard Cover': 'Uncommon',
          'Moat Piranhas': 'Common', 'Audacious Thief': 'Common', 'Boneclad Necromancer': 'Common',
          'Vengeful Warchief': 'Uncommon', "Chandra's Outrage": 'Common', 'Goblin Smuggler': 'Common',
          'Infuriate': 'Common',
          'Pack Mastiff': 'Common', 'Reduce to Ashes': 'Common', 'Unchained Berserker': 'Uncommon',
          'Natural End': 'Common',
          'Rabid Bite': 'Common', 'Sedge Scorpion': 'Common', 'Ironroot Warlord': 'Uncommon',
          'Diamond Knight': 'Uncommon',
          'Swiftwater Cliffs': 'Common', 'Aerial Assault': 'Common', 'Squad Captain': 'Common',
          'Steadfast Sentry': 'Common',
          'Convolute': 'Common', 'Portal of Sanctuary': 'Uncommon', 'Warden of Evos Isle': 'Uncommon',
          'Barony Vampire': 'Common', 'Bladebrand': 'Common', 'Blood Burglar': 'Common', 'Bone Splinters': 'Common',
          'Gorging Vulture': 'Common', 'Soul Salvage': 'Common', "Chandra's Embercat": 'Common',
          'Destructive Digger': 'Common',
          'Reckless Air Strike': 'Common', 'Scorch Spitter': 'Common', 'Brightwood Tracker': 'Common',
          'Heart-Piercer Bow': 'Common', 'Vial of Dragonfire': 'Common', 'Bloodfell Caves': 'Common',
          'Fencing Ace': 'Uncommon',
          'Gauntlets of Light': 'Uncommon', 'Octoprophet': 'Common', 'Zephyr Charge': 'Common',
          'Bloodsoaked Altar': 'Uncommon',
          'Duress': 'Common', 'Epicure of Blood': 'Common', 'Gruesome Scourger': 'Uncommon',
          'Sanitarium Skeleton': 'Common',
          'Daggersail Aeronaut': 'Common', 'Dragon Mage': 'Uncommon', 'Goblin Bird-Grabber': 'Common',
          'Rapacious Dragon': 'Uncommon', 'Ferocious Pup': 'Common', 'Healer of the Glade': 'Common',
          'Thicket Crasher': 'Common', 'Salvager of Ruin': 'Uncommon', 'Blossoming Sands': 'Common',
          'Wind-Scarred Crag': 'Common', 'Ancestral Blade': 'Uncommon', 'Battalion Foot Soldier': 'Common',
          'Griffin Protector': 'Common', 'Inspiring Captain': 'Common', 'Loyal Pegasus': 'Uncommon',
          'Pacifism': 'Common',
          'Yoked Ox': 'Common', 'Anticipate': 'Common', 'Cloudkin Seer': 'Common', 'Renowned Weaponsmith': 'Uncommon',
          "Sage's Row Denizen": 'Common', 'Winged Words': 'Common', 'Blightbeetle': 'Uncommon',
          'Disfigure': 'Uncommon',
          'Sorcerer of the Fang': 'Common', 'Unholy Indenture': 'Common', 'Ember Hauler': 'Uncommon',
          'Lavakin Brawler': 'Common', 'Howling Giant': 'Uncommon', 'Might of the Masses': 'Uncommon',
          'Overcome': 'Uncommon',
          'Anvilwrought Raptor': 'Common', 'Jungle Hollow': 'Common', 'Rugged Highlands': 'Common',
          'Thornwood Falls': 'Common',
          'Tranquil Cove': 'Common', 'Apostle of Purifying Light': 'Uncommon', 'Dawning Angel': 'Common',
          'Disenchant': 'Common',
          'Herald of the Sun': 'Uncommon', 'Raise the Alarm': 'Common', 'Rule of Law': 'Uncommon',
          'Scholar of the Ages': 'Uncommon', 'Unsummon': 'Common', 'Murder': 'Common',
          'Mask of Immolation': 'Uncommon',
          'Shock': 'Common', 'Leafkin Druid': 'Common', 'Silverback Shaman': 'Common',
          "Wolfrider's Saddle": 'Uncommon',
          'Dismal Backwater': 'Common', 'Faerie Miscreant': 'Common', 'Overgrowth Elemental': 'Uncommon',
          'Pulse of Murasa': 'Uncommon', 'Woodland Champion': 'Uncommon', 'Scuttlemutt': 'Uncommon',
          'Scoured Barrens': 'Common',
          'Negate': 'Common', "Chandra's Spitfire": 'Uncommon', 'Scampering Scorcher': 'Uncommon',
          'Loaming Shaman': 'Uncommon',
          'Moldervine Reclamation': 'Uncommon', 'Gods Willing': 'Uncommon', 'Aether Gust': 'Uncommon',
          'Bloodthirsty Aerialist': 'Uncommon', "Yarok's Fenlurker": 'Uncommon', 'Flame Sweep': 'Uncommon',
          'Ripscale Predator': 'Common', 'Barkhide Troll': 'Uncommon', 'Thrashing Brontodon': 'Uncommon',
          'Creeping Trailblazer': 'Uncommon', 'Skyknight Vanguard': 'Uncommon', 'Devout Decree': 'Uncommon',
          'Loxodon Lifechanter': 'Rare', 'Cerulean Drake': 'Uncommon', 'Dungeon Geists': 'Rare',
          'Wakeroot Elemental': 'Rare',
          'Angel of Vitality': 'Uncommon', 'Atemsis, All-Seeing': 'Rare', 'Season of Growth': 'Uncommon',
          'Lightning Stormkin': 'Uncommon', 'Tomebound Lich': 'Uncommon', 'Blood for Bones': 'Uncommon',
          'Noxious Grasp': 'Uncommon', 'Corpse Knight': 'Uncommon', 'Masterful Replication': 'Rare',
          'Brineborn Cutthroat': 'Uncommon', 'Chandra, Novice Pyromancer': 'Uncommon',
          'Goblin Ringleader': 'Uncommon',
          'Empyrean Eagle': 'Uncommon', 'Colossus Hammer': 'Uncommon', 'Manifold Key': 'Uncommon',
          'Vampire of the Dire Moon': 'Uncommon', 'Repeated Reverberation': 'Rare', 'Planar Cleansing': 'Rare',
          'Glint-Horn Buccaneer': 'Rare', 'Cryptic Caves': 'Uncommon', "Chandra's Regulator": 'Rare',
          'Bag of Holding': 'Rare',
          'Hanged Executioner': 'Rare', 'Shared Summons': 'Rare', 'Starfield Mystic': 'Rare',
          'Gargos, Vicious Watcher': 'Rare',
          'Fry': 'Uncommon', 'Leyline of Combustion': 'Rare', 'Bishop of Wings': 'Rare',
          'Spectral Sailor': 'Uncommon',
          'Embodiment of Agonies': 'Rare', 'Flood of Tears': 'Rare', "Tale's End": 'Rare',
          'Drakuseth, Maw of Flames': 'Rare',
          'Agent of Treachery': 'Rare', 'Drawn from Dreams': 'Rare', 'Risen Reef': 'Uncommon',
          'Marauding Raptor': 'Rare',
          'Brought Back': 'Rare', 'Golos, Tireless Pilgrim': 'Rare', "Legion's End": 'Rare', 'Dread Presence': 'Rare',
          'Leyline of Abundance': 'Rare', 'Thunderkin Awakener': 'Rare', 'Voracious Hydra': 'Rare',
          "Sephara, Sky's Blade": 'Rare', 'Icon of Ancestry': 'Rare', 'Temple of Triumph': 'Rare',
          "Grafdigger's Cage": 'Rare',
          'Steel Overseer': 'Rare', 'Temple of Silence': 'Rare', 'Temple of Malady': 'Rare',
          'Temple of Epiphany': 'Rare',
          'Kaalia, Zenith Seeker': 'Mythic', 'Temple of Mystery': 'Rare', 'Cavalier of Dawn': 'Mythic',
          'Scheming Symmetry': 'Rare', 'Cavalier of Flame': 'Mythic', 'Elvish Reclaimer': 'Rare',
          'Kethis, the Hidden Hand': 'Mythic', 'Cavalier of Gales': 'Mythic', 'Vilis, Broker of Blood': 'Rare',
          'Rotting Regisaur': 'Rare', "Kykar, Wind's Fury": 'Mythic', 'Field of the Dead': 'Rare',
          'Shifting Ceratops': 'Rare',
          'Veil of Summer': 'Uncommon', 'Vivien, Arkbow Ranger': 'Mythic', 'Mystic Forge': 'Rare',
          'Nightpack Ambusher': 'Rare',
          'Leyline of Anticipation': 'Rare', 'Leyline of Sanctity': 'Rare', 'Cavalier of Night': 'Mythic',
          'Ajani, Strength of the Pride': 'Mythic', 'Knight of the Ebon Legion': 'Rare', 'Lotus Field': 'Rare',
          'Chandra, Acolyte of Flame': 'Rare', 'Cavalier of Thorns': 'Mythic', 'Mu Yanling, Sky Dancer': 'Mythic',
          'Leyline of the Void': 'Rare', 'Yarok, the Desecrated': 'Mythic', 'Omnath, Locus of the Roil': 'Mythic',
          'Sorin, Imperious Bloodlord': 'Mythic', 'Chandra, Awakened Inferno': 'Mythic',
          'Rienne, Angel of Rebirth': 'Mythic',
          'Ajani, Inspiring Leader': 'Mythic', 'Goldmane Griffin': 'Rare', 'Savannah Sage': 'Common',
          'Twinblade Paladin': 'Uncommon', 'Mu Yanling, Celestial Wind': 'Mythic', 'Celestial Messenger': 'Common',
          'Waterkin Shaman': 'Uncommon', "Yanling's Harbinger": 'Rare', 'Sorin, Vampire Lord': 'Mythic',
          'Savage Gorger': 'Common', "Sorin's Guide": 'Rare', 'Thirsting Bloodlord': 'Uncommon',
          "Chandra, Flame's Fury": 'Mythic', "Chandra's Flame Wave": 'Rare', 'Pyroclastic Elemental': 'Uncommon',
          'Wildfire Elemental': 'Common', "Vivien, Nature's Avenger": 'Mythic', 'Ethereal Elk': 'Rare',
          'Gnarlback Rhino': 'Uncommon', "Vivien's Crocodile": 'Common', 'Angelic Guardian': 'Rare',
          'Bastion Enforcer': 'Common', 'Imperial Outrider': 'Common', 'Show of Valor': 'Common',
          'Siege Mastodon': 'Common',
          'Coral Merfolk': 'Common', 'Phantom Warrior': 'Common', 'Dark Remedy': 'Common', 'Disentomb': 'Common',
          'Engulfing Eruption': 'Common', 'Immortal Phoenix': 'Rare', 'Nimble Birdsticker': 'Common',
          'Canopy Spider': 'Common',
          'Frilled Sandwalla': 'Common', 'Prized Unicorn': 'Common', 'Woodland Mystic': 'Common',
          'Exultant Skymarcher': 'Common', 'Sanguine Glorifier': 'Common', 'Snubhorn Sentry': 'Common',
          'Kitesail Corsair': 'Common', 'River Darter': 'Common', 'Shatter': 'Common',
          'Pride of Conquerors': 'Uncommon',
          "Squire's Devotion": 'Common', 'Sun Sentinel': 'Common', 'Sun-Crested Pterodon': 'Common',
          'Sworn Guardian': 'Common',
          'Canal Monitor': 'Common', 'Dark Inquiry': 'Common', 'Mausoleum Harpy': 'Uncommon', 'Bombard': 'Common',
          'Orazca Frillback': 'Common', 'Cleansing Ray': 'Common', 'Soul of the Rapids': 'Common',
          'Fathom Fleet Boarder': 'Common', 'Grasping Scoundrel': 'Common', 'Reaver Ambush': 'Uncommon',
          'Recover': 'Common',
          'Vampire Revenant': 'Common', 'Voracious Vampire': 'Common', 'Goblin Trailblazer': 'Common',
          'Orazca Raptor': 'Common',
          'Sun-Collared Raptor': 'Common', 'Swaggering Corsair': 'Common', 'Hunt the Weak': 'Common',
          'Jungle Creeper': 'Uncommon', 'Divine Verdict': 'Common', 'Crashing Tide': 'Common',
          'Sailor of Means': 'Common',
          'Spire Winder': 'Common', 'Waterknot': 'Common', 'Dinosaur Hunter': 'Common', 'Dusk Charger': 'Common',
          "Buccaneer's Bravado": 'Common', 'Stampeding Horncrest': 'Common', 'Jadecraft Artisan': 'Common',
          'Overgrown Armasaur': 'Common', 'Blazing Hope': 'Uncommon', 'Martyr of Dusk': 'Common',
          'Deadeye Rig-Hauler': 'Common',
          'Siren Reaver': 'Uncommon', 'Gruesome Fate': 'Common', 'Impale': 'Common', 'Brazen Freebooter': 'Common',
          'See Red': 'Uncommon', 'Giltgrove Stalker': 'Common', 'Hardy Veteran': 'Common',
          'Strider Harness': 'Common',
          'Highland Lake': 'Uncommon', 'Baffling End': 'Uncommon', 'Oathsworn Vampire': 'Uncommon',
          'Mutiny': 'Common',
          'Aggressive Urge': 'Common', 'Strength of the Pack': 'Uncommon', 'Resplendent Griffin': 'Uncommon',
          "Captain's Hook": 'Rare', 'Orazca Relic': 'Common',
          'Evolving Wilds': 'Common',
          'Everdawn Champion': 'Uncommon', 'Moment of Triumph': 'Common', 'Hornswoggle': 'Uncommon',
          'Secrets of the Golden City': 'Common', 'Slippery Scoundrel': 'Uncommon',
          'Storm Fleet Swashbuckler': 'Uncommon',
          "Tilonalli's Crown": 'Common', 'Cacophodon': 'Uncommon', 'Cherished Hatchling': 'Uncommon',
          'Jade Bearer': 'Common',
          'Gleaming Barrier': 'Common', 'Forsaken Sanctuary': 'Uncommon', 'Stone Quarry': 'Uncommon',
          'Vampire Champion': 'Common', 'Swab Goblin': 'Common', 'Imperial Ceratops': 'Uncommon',
          'Aquatic Incursion': 'Uncommon', 'Expel from Orazca': 'Uncommon', 'Moment of Craving': 'Common',
          'Frilled Deathspitter': 'Common', "Pirate's Pillage": 'Uncommon', 'Shake the Foundations': 'Uncommon',
          'Forerunner of the Heralds': 'Uncommon', 'Woodland Stream': 'Uncommon', 'Cinder Barrens': 'Common',
          'Riverwise Augur': 'Uncommon', 'Dusk Legion Zealot': 'Common', 'Forerunner of the Coalition': 'Uncommon',
          'Tomb Robber': 'Rare', 'Daring Buccaneer': 'Uncommon', 'Fanatical Firebrand': 'Common',
          'Form of the Dinosaur': 'Rare',
          'Jungleborn Pioneer': 'Common', 'Relentless Raptor': 'Uncommon', 'Bishop of Binding': 'Rare',
          'Induced Amnesia': 'Rare', 'Sea Legs': 'Common', 'Sadistic Skymarcher': 'Uncommon',
          'Crested Herdcaller': 'Uncommon',
          'Knight of the Stampede': 'Common', 'Storm Fleet Sprinter': 'Uncommon', "Vraska's Scorn": 'Rare',
          "Angrath's Ambusher": 'Uncommon', 'Famished Paladin': 'Uncommon', 'Majestic Heliopterus': 'Uncommon',
          'Arterial Flow': 'Uncommon', 'Deadeye Brawler': 'Uncommon', 'Dire Fleet Neckbreaker': 'Uncommon',
          'Forerunner of the Legion': 'Uncommon', "Sphinx's Decree": 'Rare', 'Swift Warden': 'Uncommon',
          'Flood of Recollection': 'Uncommon', "Dead Man's Chest": 'Rare', 'Charging Tuskodon': 'Uncommon',
          'Enter the Unknown': 'Uncommon', 'Raging Regisaur': 'Uncommon', 'Golden Demise': 'Uncommon',
          'Protean Raider': 'Rare',
          'Paladin of Atonement': 'Rare', 'Crafty Cutpurse': 'Rare', 'Mist-Cloaked Herald': 'Common',
          'Needletooth Raptor': 'Uncommon', 'Atzocan Seer': 'Uncommon', 'Awakened Amalgam': 'Rare',
          'Forerunner of the Empire': 'Uncommon', "Angrath's Fury": 'Rare', 'Skymarcher Aspirant': 'Uncommon',
          "Vraska's Conquistador": 'Uncommon', 'Thunderherd Migration': 'Uncommon', "Brass's Bounty": 'Rare',
          'Silvergill Adept': 'Uncommon', "Tilonalli's Summoner": 'Rare', 'Temple Altisaur': 'Rare',
          "Admiral's Order": 'Rare',
          'Pitiless Plunderer': 'Uncommon', 'Release to the Wind': 'Rare', "Kumena's Awakening": 'Rare',
          'Seafloor Oracle': 'Rare', 'Reckless Rage': 'Uncommon', 'Tetzimoc, Primal Death': 'Rare',
          'Silverclad Ferocidons': 'Rare', 'Golden Guardian': 'Rare', 'Gold-Forge Garrison': 'Rare',
          'Warkite Marauder': 'Rare',
          "Vona's Hunger": 'Rare', 'Path of Mettle': 'Rare', 'Metzali, Tower of Triumph': 'Rare',
          'Silent Gravestone': 'Rare',
          'Dire Fleet Poisoner': 'Rare', 'Siegehorn Ceratops': 'Rare', 'Champion of Dusk': 'Rare',
          'Ravenous Chupacabra': 'Uncommon', 'Slaughter the Strong': 'Rare', 'Merfolk Mistbinder': 'Uncommon',
          'Deeproot Elite': 'Rare', 'Profane Procession': 'Rare', 'Tomb of the Dusk Rose': 'Rare',
          'Radiant Destiny': 'Rare',
          'Legion Lieutenant': 'Uncommon', "Mastermind's Acquisition": 'Rare', 'Zetalpa, Primal Dawn': 'Rare',
          'Arch of Orazca': 'Rare', 'Storm the Vault': 'Rare', 'Vault of Catlacan': 'Rare', 'Blood Sun': 'Rare',
          'Jadelight Ranger': 'Rare', 'Nezahal, Primal Tide': 'Rare', 'Curious Obsession': 'Uncommon',
          'World Shaper': 'Rare',
          'Trapjaw Tyrant': 'Mythic', 'Dire Fleet Daredevil': 'Rare', "Hadana's Climb": 'Rare',
          'Winged Temple of Orazca': 'Rare', 'Timestream Navigator': 'Mythic', 'Path of Discovery': 'Rare',
          'Azor, the Lawbringer': 'Mythic', "Azor's Gateway": 'Mythic', 'Sanctum of the Sun': 'Mythic',
          'Rekindling Phoenix': 'Mythic', 'Ghalta, Primal Hunger': 'Rare', 'Angrath, the Flame-Chained': 'Mythic',
          'Journey to Eternity': 'Rare', 'Atzal, Cave of Eternity': 'Rare', 'Tendershoot Dryad': 'Rare',
          'Angrath, Minotaur Pirate': 'Mythic', 'Kumena, Tyrant of Orazca': 'Mythic',
          'Huatli, Radiant Champion': 'Mythic',
          'Etali, Primal Storm': 'Rare', 'Wayward Swordtooth': 'Rare', 'Polyraptor': 'Mythic',
          'Vraska, Scheming Gorgon': 'Mythic', 'Elenda, the Dusk Rose': 'Mythic', 'Twilight Prophet': 'Mythic',
          'Zacama, Primal Calamity': 'Mythic', 'The Immortal Sun': 'Mythic', 'Civic Stalwart': 'Common',
          'Haazda Officer': 'Common', 'Prowling Caracal': 'Common', 'Syndicate Messenger': 'Common',
          'Senate Courier': 'Common',
          'Slimebind': 'Common', 'Consign to the Pit': 'Common', 'Noxious Groodion': 'Common',
          'Plague Wight': 'Common',
          'Undercity Scavenger': 'Common', 'Act of Treason': 'Common', 'Burning-Tree Vandal': 'Common',
          'Scorchmark': 'Common',
          'Territorial Boar': 'Common', 'Azorius Knight-Arbiter': 'Common', 'Rakdos Firewheeler': 'Uncommon',
          'Rakdos Roustabout': 'Common', 'Vizkopa Vampire': 'Common', 'Bring to Trial': 'Common',
          'Expose to Daylight': 'Common',
          'Summary Judgment': 'Common', 'Tenth District Veteran': 'Common', 'Watchful Giant': 'Common',
          'Skitter Eel': 'Common',
          'Catacomb Crocodile': 'Common', 'Dead Revels': 'Common', 'Grotesque Demise': 'Common',
          'Rakdos Trumpeter': 'Common',
          'Thirsting Shade': 'Common', "Undercity's Embrace": 'Common', 'Burn Bright': 'Common',
          'Feral Maaka': 'Common',
          'Flames of the Raze-Boar': 'Uncommon', 'Ghor-Clan Wrecker': 'Common', 'Rubblebelt Recluse': 'Common',
          'Rumbling Ruin': 'Uncommon', 'Storm Strike': 'Common', 'Mammoth Spider': 'Common',
          "Sagittars' Volley": 'Common',
          'Sauroform Hybrid': 'Common', 'Aeromunculus': 'Common', 'Applied Biomancy': 'Common',
          'Final Payment': 'Common',
          'Frenzied Arynx': 'Common', "Sphinx's Insight": 'Common', 'Senate Griffin': 'Common',
          'Concordia Pegasus': 'Common',
          'Forbidding Spirit': 'Uncommon', 'Sky Tether': 'Uncommon', 'Twilight Panther': 'Common',
          "Debtors' Transport": 'Common', 'Gravel-Hide Goblin': 'Common', 'Spikewheel Acrobat': 'Common',
          'Axebane Beast': 'Common', 'Rampaging Rendhorn': 'Common', 'Steeple Creeper': 'Common',
          'Sylvan Brushstrider': 'Common', 'Get the Point': 'Common', 'Rubblebelt Runner': 'Common',
          'Sphinx of New Prahv': 'Uncommon', 'Rubble Slinger': 'Common', 'Screaming Shield': 'Uncommon',
          'Simic Locket': 'Common', 'Simic Guildgate': 'Common', 'Knight of Sorrows': 'Common',
          "Arrester's Admonition": 'Common', 'Chillbringer': 'Common', 'Clear the Mind': 'Common',
          'Code of Constraint': 'Uncommon', 'Gateway Sneak': 'Uncommon', "Sage's Row Savant": 'Common',
          'Blade Juggler': 'Common', 'Spire Mangler': 'Uncommon', 'Amplifire': 'Rare', 'Dagger Caster': 'Uncommon',
          'Deface': 'Common', 'Gift of Strength': 'Common', 'Root Snare': 'Common', 'Wrecking Beast': 'Common',
          'Bolrac-Clan Crusher': 'Uncommon', "Dovin's Acuity": 'Uncommon', 'Grasping Thrull': 'Common',
          'Hackrobat': 'Uncommon',
          'Imperious Oligarch': 'Common', 'Rafter Demon': 'Common', 'Gruul Locket': 'Common',
          'Azorius Guildgate': 'Common',
          'Orzhov Guildgate': 'Common', 'Ministrant of Obligation': 'Uncommon', 'Rally to Battle': 'Uncommon',
          'Humongulus': 'Common', 'Clamor Shaman': 'Uncommon', 'Rubble Reading': 'Common', 'Savage Smash': 'Common',
          'Footlight Fiend': 'Common', 'Scuttlegator': 'Common', 'Gruul Guildgate': 'Common',
          'Rakdos Guildgate': 'Common',
          "Arrester's Zeal": 'Common', 'Impassioned Orator': 'Common', "Sentinel's Mark": 'Uncommon',
          'Coral Commando': 'Common',
          'Eyes Everywhere': 'Uncommon', 'Shimmer of Possibility': 'Common', 'Bankrupt in Blood': 'Uncommon',
          'Carrion Imp': 'Common', 'Clear the Stage': 'Uncommon', 'Ill-Gotten Inheritance': 'Common',
          'Goblin Gathering': 'Common', 'Enraged Ceratok': 'Uncommon', 'Regenesis': 'Uncommon',
          'Titanic Brawl': 'Common',
          'Trollbred Guardian': 'Uncommon', 'Azorius Skyguard': 'Uncommon', 'Galloping Lizrog': 'Uncommon',
          "Lawmage's Binding": 'Common', 'Syndicate Guildmage': 'Uncommon', 'Scrabbling Claws': 'Uncommon',
          'Sphinx of the Guildpact': 'Uncommon', 'Faerie Duelist': 'Common', 'Smelt-Ward Ignus': 'Uncommon',
          'Spear Spewer': 'Common', 'Saruli Caretaker': 'Common', 'Silhana Wayfinder': 'Uncommon',
          'Stony Strength': 'Common',
          'Senate Guildmage': 'Uncommon', 'Consecrate': 'Uncommon', 'Consecrate // Consume': 'Uncommon',
          'Depose': 'Uncommon',
          'Depose // Deploy': 'Uncommon', 'Azorius Locket': 'Common', 'Gate Colossus': 'Uncommon',
          'Junktroller': 'Uncommon',
          'Orzhov Locket': 'Common', 'Angelic Exaltation': 'Uncommon', 'Archway Angel': 'Uncommon',
          "Justiciar's Portal": 'Common', 'Spirit of the Spires': 'Uncommon', 'Prying Eyes': 'Common',
          'Swirling Torrent': 'Uncommon', 'Orzhov Racketeers': 'Uncommon', 'Tin Street Dodger': 'Uncommon',
          'Biogenic Upgrade': 'Uncommon', 'Open the Gates': 'Common', 'Cult Guildmage': 'Uncommon',
          'Knight of the Last Breath': 'Uncommon', 'Macabre Mockery': 'Uncommon', 'Sunder Shaman': 'Uncommon',
          'Quench': 'Common', 'Thought Collapse': 'Common', 'Wall of Lost Thoughts': 'Uncommon',
          'Vindictive Vampire': 'Uncommon', 'Gruul Beastmaster': 'Uncommon', 'Rampage of the Clans': 'Rare',
          'Tower Defense': 'Uncommon', 'Clan Guildmage': 'Uncommon', 'Zhur-Taa Goblin': 'Uncommon',
          'Carnival': 'Uncommon',
          'Carnival // Carnage': 'Uncommon', 'Rakdos Locket': 'Common', 'Awaken the Erstwhile': 'Rare',
          'Bloodmist Infiltrator': 'Uncommon', 'Fireblade Artist': 'Uncommon', 'Gyre Engineer': 'Uncommon',
          'Pitiless Pontiff': 'Uncommon', 'Sharktocrab': 'Uncommon', 'Resolute Watchdog': 'Uncommon',
          'Orzhov Enforcer': 'Uncommon', 'Cavalcade of Calamity': 'Uncommon', 'Gatebreaker Ram': 'Uncommon',
          'Basilica Bell-Haunt': 'Uncommon', 'Nikya of the Old Ways': 'Rare', 'Combine Guildmage': 'Uncommon',
          'Skatewing Spy': 'Uncommon', 'Cry of the Carnarium': 'Uncommon', 'Drill Bit': 'Uncommon',
          'Gates Ablaze': 'Uncommon',
          'Immolation Shaman': 'Rare', 'Windstorm Drake': 'Uncommon', 'Mirror March': 'Rare', 'Warrant': 'Rare',
          'Warrant // Warden': 'Rare', 'Glass of the Guildpact': 'Rare', 'Growth Spiral': 'Common',
          'Mortify': 'Uncommon',
          'Tome of the Guildpact': 'Rare', 'Lumbering Battlement': 'Rare', 'Essence Capture': 'Uncommon',
          'Precognitive Perception': 'Rare', 'Bedeck': 'Rare', 'Bedeck // Bedazzle': 'Rare',
          'Collision // Colossus': 'Uncommon', 'Collision': 'Uncommon',
          'Colossus': 'Uncommon', 'Verity Circle': 'Rare', 'High Alert': 'Uncommon', 'Thrash': 'Rare',
          'Thrash // Threat': 'Rare', 'Font of Agonies': 'Rare', 'Frilled Mystic': 'Uncommon',
          'Zegana, Utopian Speaker': 'Rare',
          'End-Raze Forerunners': 'Rare', 'Ethereal Absolution': 'Rare', 'Persistent Petitioners': 'Common',
          'Pestilent Spirit': 'Rare', 'Skewer the Critics': 'Common', 'Sphinx of Foresight': 'Rare',
          'Repudiate': 'Rare',
          'Repudiate // Replicate': 'Rare', 'Simic Ascendancy': 'Rare', "Biomancer's Familiar": 'Rare',
          'Benthic Biomancer': 'Rare', 'Theater of Horrors': 'Rare', 'Lavinia, Azorius Renegade': 'Rare',
          'Revival': 'Rare',
          'Revival // Revenge': 'Rare', 'Rix Maadi Reveler': 'Rare', 'Emergency Powers': 'Mythic',
          'Mesmerizing Benthid': 'Mythic', 'Plaza of Harmony': 'Rare', 'Mass Manipulation': 'Rare',
          'Teysa Karlov': 'Rare',
          'Unbreakable Formation': 'Rare', 'Ravager Wurm': 'Mythic', 'Rakdos, the Showstopper': 'Mythic',
          'Rhythm of the Wild': 'Uncommon', 'Absorb': 'Rare', 'Wilderness Reclamation': 'Uncommon',
          'Captive Audience': 'Mythic',
          'Pteramander': 'Uncommon', 'Hero of Precinct One': 'Rare', 'Gutterbones': 'Rare', 'Tithe Taker': 'Rare',
          'Cindervines': 'Rare', 'Growth-Chamber Guardian': 'Rare', 'Judith, the Scourge Diva': 'Rare',
          'Angel of Grace': 'Mythic', 'Guardian Project': 'Rare', 'Electrodominance': 'Rare',
          'Gruul Spellbreaker': 'Rare',
          "Kaya's Wrath": 'Rare', 'Priest of Forgotten Gods': 'Rare', 'Dovin, Grand Arbiter': 'Mythic',
          'Light Up the Stage': 'Uncommon', 'Domri, Chaos Bringer': 'Mythic', 'Skarrgan Hellkite': 'Mythic',
          'Incubation Druid': 'Rare', 'Incubation': 'Uncommon', 'Incubation // Incongruity': 'Uncommon',
          'Bedevil': 'Rare',
          'Biogenic Ooze': 'Mythic', 'Prime Speaker Vannifar': 'Mythic', 'Spawn of Mayhem': 'Mythic',
          'Seraph of the Scales': 'Mythic', 'Deputy of Detention': 'Rare', 'Smothering Tithe': 'Rare',
          'Kaya, Orzhov Usurper': 'Mythic', 'Hallowed Fountain': 'Rare', 'Godless Shrine': 'Rare',
          'Stomping Ground': 'Rare',
          'Blood Crypt': 'Rare', 'Breeding Pool': 'Rare', 'Hydroid Krasis': 'Mythic',
          'Dovin, Architect of Law': 'Mythic',
          'Elite Arrester': 'Common', "Dovin's Dismissal": 'Rare', "Dovin's Automaton": 'Uncommon',
          'Domri, City Smasher': 'Mythic', 'Ragefire': 'Common', 'Charging War Boar': 'Uncommon',
          "Domri's Nodorog": 'Rare',
          'The Haunt of Hightower': 'Mythic', 'Thunder Drake': 'Common', 'Charity Extractor': 'Common',
          'Lazotep Behemoth': 'Common', 'Chainwhip Cyclops': 'Common', 'Honor the God-Pharaoh': 'Common',
          'Invading Manticore': 'Common', 'Turret Ogre': 'Common', 'Kraul Stinger': 'Common',
          'Primordial Wurm': 'Common',
          'Thundering Ceratok': 'Common', 'Wardscale Crocodile': 'Common', 'Charmed Stray': 'Common',
          'Law-Rune Enforcer': 'Common', 'Trusted Pegasus': 'Common', 'War Screecher': 'Common',
          'Relentless Advance': 'Common',
          'Spellkeeper Weird': 'Common', 'Dreadmalkin': 'Uncommon', 'Duskmantle Operative': 'Common',
          "Vraska's Finisher": 'Common', 'Ahn-Crop Invader': 'Common', 'Goblin Assailant': 'Common',
          'Goblin Assault Team': 'Common', "Nahiri's Stoneblades": 'Common', "Sarkhan's Catharsis": 'Common',
          'Snarespinner': 'Common', "Saheeli's Silverwing": 'Common', 'Battlefield Promotion': 'Common',
          'Bulwark Giant': 'Common', "Gideon's Triumph": 'Uncommon', "Teyo's Lightshield": 'Common',
          "Ashiok's Skulker": 'Common', 'Callous Dismissal': 'Common', 'Crush Dissent': 'Common',
          'Erratic Visionary': 'Common',
          'Sky Theater Strix': 'Common', 'Stealth Mission': 'Common', "Davriel's Shadowfugue": 'Common',
          "Sorin's Thirst": 'Common', 'Spark Reaper': 'Common', 'Toll of the Invasion': 'Common',
          'Forced Landing': 'Common',
          'Prismite': 'Common', 'Divine Arrow': 'Common', 'Ironclad Krovod': 'Common', "Kiora's Dambreaker": 'Common',
          'Naga Eternal': 'Common', 'No Escape': 'Common', 'Totally Lost': 'Common', 'Aid the Fallen': 'Common',
          'Bleeding Edge': 'Uncommon', 'Blindblast': 'Common', 'Bond of Passion': 'Uncommon',
          "Chandra's Pyrohelix": 'Common',
          'Raging Kronch': 'Common', "Arlinn's Wolf": 'Common', 'Kronch Wrangler': 'Common',
          "Ugin's Conjurant": 'Uncommon',
          'Enforcer Griffin': 'Common', 'Loxodon Sergeant': 'Common', 'Makeshift Battalion': 'Common',
          'Rising Populace': 'Common', 'Topple the Statue': 'Common', 'Aven Eternal': 'Common', 'Banehound': 'Common',
          'Eternal Taskmaster': 'Uncommon', 'Herald of the Dreadhorde': 'Common', 'Vampire Opportunist': 'Common',
          'Devouring Hellion': 'Uncommon', 'Grim Initiate': 'Common', 'Heartfire': 'Common',
          'Centaur Nurturer': 'Common',
          'Mowu, Loyal Companion': 'Uncommon', 'Pollenbright Druid': 'Common', 'Steady Aim': 'Common',
          'Heartwarming Redemption': 'Uncommon', 'Invade the City': 'Uncommon', 'Kaya, Bane of the Dead': 'Uncommon',
          'Guild Globe': 'Common', "Ajani's Pridemate": 'Uncommon', 'Bond of Discipline': 'Uncommon',
          'Defiant Strike': 'Common',
          "Gideon's Sacrifice": 'Common', 'Pouncing Lynx': 'Common', 'Sunblade Angel': 'Uncommon',
          "Kasmina's Transmutation": 'Common', 'Shriekdiver': 'Common', 'Spark Harvest': 'Common',
          'Vizier of the Scorpion': 'Uncommon', 'Burning Prophet': 'Common', 'Cyclops Electromancer': 'Uncommon',
          "Tibalt's Rager": 'Uncommon', 'Arboreal Grazer': 'Common', 'Bond of Flourishing': 'Uncommon',
          'Storm the Citadel': 'Uncommon', "Vivien's Grizzly": 'Common', "Huatli's Raptor": 'Uncommon',
          "Ral's Outburst": 'Uncommon', 'Iron Bully': 'Common', 'Grateful Apparition': 'Uncommon',
          'Martyr for the Cause': 'Common', 'Rally of Wings': 'Uncommon', "Jace's Triumph": 'Uncommon',
          'Rescuer Sphinx': 'Uncommon', "Teferi's Time Twist": 'Common', 'Wall of Runes': 'Common',
          "Chandra's Triumph": 'Uncommon', 'Dreadhorde Twins': 'Uncommon', "Samut's Sprint": 'Common',
          'Arlinn, Voice of the Pack': 'Uncommon', 'Giant Growth': 'Common', 'Merfolk Skydiver': 'Uncommon',
          'Pledge of Unity': 'Uncommon', 'Rubblebelt Rioters': 'Uncommon', 'Nahiri, Storm of Stone': 'Uncommon',
          'Bond of Revival': 'Uncommon', 'Lazotep Reaver': 'Common', 'Ob Nixilis, the Hate-Twisted': 'Uncommon',
          'Bolt Bend': 'Uncommon', 'Spellgorger Weird': 'Common', 'Band Together': 'Common',
          'Courage in Crisis': 'Common',
          "Huatli, the Sun's Heart": 'Uncommon', 'Prison Realm': 'Uncommon', 'Bond of Insight': 'Uncommon',
          'Contentious Plan': 'Common', 'Eternal Skylord': 'Uncommon', 'Lazotep Plating': 'Uncommon',
          'Silent Submersible': 'Rare', 'Tithebearer Giant': 'Common', 'Bloom Hulk': 'Common',
          "Domri's Ambush": 'Uncommon',
          'Mayhem Devil': 'Uncommon', 'Angrath, Captain of Chaos': 'Uncommon', 'Samut, Tyrant Smasher': 'Uncommon',
          'Ignite the Beacon': 'Rare', 'Ravnica at War': 'Rare', "Wanderer's Strike": 'Common',
          'Unlikely Aid': 'Common',
          'Jaya, Venerated Firemage': 'Uncommon', "Jaya's Greeting": 'Common', 'Challenger Troll': 'Uncommon',
          "Nissa's Triumph": 'Uncommon', 'Bioessence Hydra': 'Rare', 'Gleaming Overseer': 'Uncommon',
          'Tenth District Legionnaire': 'Uncommon', 'Deliver Unto Evil': 'Rare', "Ob Nixilis's Cruelty": 'Common',
          'Price of Betrayal': 'Uncommon', 'Elite Guardmage': 'Uncommon', "God-Pharaoh's Statue": 'Uncommon',
          'Augur of Bolas': 'Uncommon', "Tamiyo's Epiphany": 'Common', 'Mizzium Tank': 'Rare',
          'Jiang Yanggu, Wildcrafter': 'Uncommon', 'Dovin, Hand of Control': 'Uncommon',
          "Vraska, Swarm's Eminence": 'Uncommon',
          'Firemind Vessel': 'Uncommon', 'Mana Geode': 'Common', 'Teyo, the Shieldmage': 'Uncommon',
          'The Wanderer': 'Uncommon',
          'Flux Channeler': 'Uncommon', 'Cruel Celebrant': 'Uncommon', 'Leyline Prowler': 'Uncommon',
          'Role Reversal': 'Rare',
          'Soul Diviner': 'Rare', 'Kiora, Behemoth Beckoner': 'Uncommon', 'Interplanar Beacon': 'Uncommon',
          'Single Combat': 'Rare', 'Kasmina, Enigmatic Mentor': 'Uncommon', 'Tibalt, Rakish Instigator': 'Uncommon',
          'Deathsprout': 'Uncommon', 'Awakening of Vitu-Ghazi': 'Rare', 'Planewide Celebration': 'Rare',
          'Parhelion II': 'Rare',
          'Paradise Druid': 'Uncommon', "Angrath's Rampage": 'Uncommon', 'Solar Blaze': 'Rare',
          "Tyrant's Scorn": 'Uncommon',
          'Davriel, Rogue Shadowmage': 'Uncommon', 'Tolsimir, Friend to Wolves': 'Rare', 'Living Twister': 'Rare',
          'Widespread Brutality': 'Rare', 'Emergence Zone': 'Uncommon', "Kaya's Ghostform": 'Common',
          'Neoform': 'Uncommon',
          'Commence the Endgame': 'Rare', 'Storrev, Devkarin Lich': 'Rare', 'Mobilized District': 'Rare',
          'Neheb, Dreadhorde Champion': 'Rare', 'Evolution Sage': 'Uncommon', 'Despark': 'Uncommon',
          "Liliana's Triumph": 'Uncommon', "Vivien's Arkbow": 'Rare', 'Tomik, Distinguished Advokist': 'Rare',
          'Casualties of War': 'Rare', 'Time Wipe': 'Rare', 'Fblthp, the Lost': 'Rare', 'Oath of Kaya': 'Rare',
          'Massacre Girl': 'Rare', 'Command the Dreadhorde': 'Rare', "Dovin's Veto": 'Uncommon',
          'Ajani, the Greathearted': 'Rare', 'Dreadhorde Butcher': 'Rare', 'Saheeli, Sublime Artificer': 'Uncommon',
          'Enter the God-Eternals': 'Rare', 'Spark Double': 'Rare', "Bolas's Citadel": 'Rare',
          "Narset's Reversal": 'Rare',
          'Krenko, Tin Street Kingpin': 'Rare', 'Ashiok, Dream Render': 'Uncommon', 'Domri, Anarch of Bolas': 'Rare',
          'Sarkhan the Masterless': 'Rare', 'Ral, Storm Conduit': 'Rare', "Karn's Bastion": 'Rare',
          'Dreadhorde Invasion': 'Rare', 'Finale of Eternity': 'Mythic', 'Finale of Revelation': 'Mythic',
          'Jace, Wielder of Mysteries': 'Rare', 'The Elderspell': 'Rare', 'Tamiyo, Collector of Tales': 'Rare',
          'Feather, the Redeemed': 'Rare', 'Finale of Glory': 'Mythic', 'Chandra, Fire Artisan': 'Rare',
          'Roalesk, Apex Hybrid': 'Mythic', 'Sorin, Vengeful Bloodlord': 'Rare',
          'Vivien, Champion of the Wilds': 'Rare',
          'Niv-Mizzet Reborn': 'Mythic', 'God-Eternal Bontu': 'Mythic', 'God-Eternal Rhonas': 'Mythic',
          'Narset, Parter of Veils': 'Uncommon', 'Nissa, Who Shakes the World': 'Rare', 'Ugin, the Ineffable': 'Rare',
          'Ilharg, the Raze-Boar': 'Mythic', 'God-Eternal Oketra': 'Mythic', 'Blast Zone': 'Rare',
          'Finale of Promise': 'Mythic',
          'God-Eternal Kefnet': 'Mythic', 'Gideon Blackblade': 'Mythic', 'Dreadhorde Arcanist': 'Rare',
          'Finale of Devastation': 'Mythic', 'Nicol Bolas, Dragon-God': 'Mythic', 'Karn, the Great Creator': 'Rare',
          'Liliana, Dreadhorde General': 'Mythic', 'Teferi, Time Raveler': 'Rare', 'Gideon, the Oathsworn': 'Mythic',
          'Desperate Lunge': 'Common', "Gideon's Battle Cry": 'Rare', "Gideon's Company": 'Uncommon',
          'Jace, Arcane Strategist': 'Mythic', 'Guildpact Informant': 'Common', "Jace's Projection": 'Uncommon',
          "Jace's Ruse": 'Rare', 'Tezzeret, Master of the Bridge': 'Mythic', 'Ritual of Rejuvenation': 'Common',
          'Shining Aerosaur': 'Common', 'Skyblade of the Legion': 'Common', 'Headwater Sentries': 'Common',
          'Storm Sculptor': 'Common', "Queen's Agent": 'Common', "Queen's Bay Soldier": 'Common',
          'Storm Fleet Pyromancer': 'Common', 'Crash the Ramparts': 'Common', 'Crushing Canopy': 'Common',
          "Ixalli's Diviner": 'Common', "Ixalli's Keeper": 'Common', "Bishop's Soldier": 'Common',
          'Encampment Keeper': 'Common',
          'Pious Interdiction': 'Common', 'Shipwreck Looter': 'Common', 'Desperate Castaways': 'Common',
          'Fathom Fleet Cutthroat': 'Common', 'Mark of the Vampire': 'Common', 'Fathom Fleet Firebrand': 'Common',
          'Nest Robber': 'Common', "Tilonalli's Knight": 'Common', 'Unfriendly Fire': 'Common',
          'Colossal Dreadmaw': 'Common',
          'Jungle Delver': 'Common', 'Raptor Companion': 'Common', 'Sunrise Seeker': 'Common',
          'One With the Wind': 'Common',
          'Run Aground': 'Common', 'Shore Keeper': 'Common', 'Siren Lookout': 'Common', 'Anointed Deacon': 'Common',
          'Dire Fleet Interloper': 'Common', 'Skulduggery': 'Common', 'Brazen Buccaneers': 'Common',
          'Demolish': 'Common',
          'Headstrong Brute': 'Common', 'Blossom Dryad': 'Common', 'Deeproot Warrior': 'Common',
          'Emergent Growth': 'Uncommon',
          'Grazing Whiptail': 'Common', 'Pounce': 'Common', 'Spike-Tailed Ceratops': 'Common',
          'Belligerent Brontodon': 'Uncommon', 'Marauding Looter': 'Uncommon', 'Elaborate Firecannon': 'Uncommon',
          'Unknown Shores': 'Common', 'Legion Conquistador': 'Common', 'Pterodon Knight': 'Common',
          'Slash of Talons': 'Common',
          'Depths of Desire': 'Common', 'Watertrap Weaver': 'Common', 'Contract Killing': 'Common',
          'Dark Nourishment': 'Uncommon', 'Heartless Pillage': 'Uncommon', 'Spreading Rot': 'Common',
          'Vanquish the Weak': 'Common', 'Dual Shot': 'Common', 'Frenzied Raptor': 'Common',
          'Rummaging Goblin': 'Common',
          'Jade Guardian': 'Common', 'Ravenous Daggertooth': 'Common', 'Gilded Sentinel': 'Common',
          "Pirate's Cutlass": 'Common',
          'Bright Reprisal': 'Uncommon', 'Demystify': 'Common', 'Emissary of Sunrise': 'Uncommon',
          'Imperial Lancer': 'Uncommon',
          "Queen's Commission": 'Common', 'Rallying Roar': 'Uncommon', "Navigator's Ruin": 'Uncommon',
          'Perilous Voyage': 'Uncommon', "Pirate's Prize": 'Common', 'Storm Fleet Spy': 'Uncommon',
          'Blight Keeper': 'Common',
          'Deadeye Tormentor': 'Common', 'Fire Shrine Keeper': 'Common', 'Firecannon Blast': 'Common',
          'Swashbuckling': 'Common',
          'New Horizons': 'Common', 'Verdant Rebirth': 'Uncommon', 'Cobbled Wings': 'Common',
          'Inspiring Cleric': 'Uncommon',
          "Legion's Judgment": 'Common', 'Paladin of the Bloodstained': 'Common', 'Storm Fleet Aerialist': 'Uncommon',
          'Tempest Caller': 'Uncommon', 'Dire Fleet Hoarder': 'Common', 'Hijack': 'Common',
          'Repeating Barrage': 'Rare',
          'Trove of Temptation': 'Uncommon', 'Atzocan Archer': 'Uncommon', 'Blinding Fog': 'Common',
          'Slice in Twain': 'Uncommon', "Vampire's Zeal": 'Common', 'Prosperous Pirates': 'Common',
          'River Sneak': 'Uncommon',
          'Bishop of the Bloodstained': 'Uncommon', 'Ruthless Knave': 'Uncommon', 'Wanted Scoundrels': 'Uncommon',
          'Lightning Strike': 'Uncommon', 'Commune with Dinosaurs': 'Common', "Tishana's Wayfinder": 'Common',
          'Waker of the Wilds': 'Rare', "Hierophant's Chalice": 'Common', 'Prying Blade': 'Common',
          "Huatli's Spurring": 'Uncommon', 'Duskborne Skymarcher': 'Uncommon', 'Looming Altisaur': 'Common',
          'Steadfast Armasaur': 'Uncommon', 'Shaper Apprentice': 'Common', 'Deathless Ancient': 'Uncommon',
          'March of the Drowned': 'Common', "Seekers' Squire": 'Uncommon', 'Skittering Heartstopper': 'Common',
          'Bonded Horncrest': 'Uncommon', 'Makeshift Munitions': 'Uncommon', 'Sun-Crowned Hunters': 'Common',
          "River Heralds' Boon": 'Common', 'Deadeye Plunderers': 'Uncommon', "Huatli's Snubhorn": 'Common',
          'Glorifier of Dusk': 'Uncommon', 'Wind Strider': 'Common', 'Costly Plunder': 'Common',
          'Lurking Chupacabra': 'Uncommon', 'Walk the Plank': 'Uncommon', 'Thundering Spineback': 'Uncommon',
          'Shapers of Nature': 'Uncommon', 'Dusk Legion Dreadnought': 'Uncommon', 'Shadowed Caravel': 'Rare',
          "Kinjalli's Caller": 'Common', 'Daring Saboteur': 'Rare', 'Deadeye Quartermaster': 'Uncommon',
          'Dreamcaller Siren': 'Rare', "Siren's Ruse": 'Common', 'Dinosaur Stampede': 'Uncommon',
          'Lightning-Rig Crew': 'Uncommon', 'Storm Fleet Arsonist': 'Uncommon', "Kumena's Speaker": 'Uncommon',
          'Old-Growth Dryads': 'Rare', 'Savage Stomp': 'Uncommon', 'Sentinel Totem': 'Uncommon',
          'Favorable Winds': 'Uncommon',
          "Grim Captain's Call": 'Uncommon', 'Charging Monstrosaur': 'Uncommon', 'Rigging Runner': 'Uncommon',
          'Thrash of Raptors': 'Common', "Tilonalli's Skinshifter": 'Rare', 'Wily Goblin': 'Uncommon',
          'Ancient Brontodon': 'Common', 'Vineshaper Mystic': 'Uncommon', 'Dire Fleet Captain': 'Uncommon',
          'Bellowing Aegisaur': 'Uncommon', 'Sanguine Sacrament': 'Rare', "Emperor's Vanguard": 'Rare',
          'Sleek Schooner': 'Uncommon', 'Goring Ceratops': 'Rare', 'Priest of the Wakening Sun': 'Rare',
          'Deeproot Waters': 'Uncommon', 'Spell Pierce': 'Common', 'Pillar of Origins': 'Uncommon',
          "Castaway's Despair": 'Common', "Jace's Sentinel": 'Uncommon', 'Territorial Hammerskull': 'Common',
          'Dive Down': 'Common', "Angrath's Marauders": 'Rare', "Burning Sun's Avatar": 'Rare',
          'Raptor Hatchling': 'Uncommon',
          'Snapping Sailback': 'Uncommon', 'Grasping Current': 'Rare', 'Imperial Aerosaur': 'Uncommon',
          'Fleet Swallower': 'Rare', 'Captivating Crew': 'Rare', 'Deeproot Champion': 'Rare',
          'Raging Swordtooth': 'Uncommon',
          'Sky Terror': 'Uncommon', "Lookout's Dispersal": 'Uncommon', "Raiders' Wake": 'Uncommon',
          'Vicious Conquistador': 'Uncommon', 'Fiery Cannonade': 'Uncommon', 'Sword-Point Diplomacy': 'Rare',
          'Call to the Feast': 'Uncommon', 'Fell Flagship': 'Rare', 'Deadeye Tracker': 'Rare', 'Ruin Raider': 'Rare',
          'Sheltering Light': 'Uncommon', 'Drover of the Mighty': 'Uncommon', 'Wildgrowth Walker': 'Uncommon',
          'Ashes of the Abhorrent': 'Rare', 'Kitesail Freebooter': 'Uncommon', 'Captain Lannery Storm': 'Rare',
          'Ranging Raptors': 'Uncommon', 'Adanto Vanguard': 'Uncommon', 'Fathom Fleet Captain': 'Rare',
          'Merfolk Branchwalker': 'Uncommon', "(XLN)'s Binding": 'Uncommon', "Arguel's Blood Fast": 'Rare',
          'Temple of Aclazotz': 'Rare', 'Deathgorge Scavenger': 'Rare', "Conqueror's Galleon": 'Rare',
          "Conqueror's Foothold": 'Rare', 'Bishop of Rebirth': 'Rare', 'Entrancing Melody': 'Rare',
          'Otepec Huntmaster': 'Uncommon', 'Rowdy Crew': 'Mythic', 'Kopala, Warden of Waves': 'Rare',
          'Rile': 'Common',
          'Bloodcrazed Paladin': 'Rare', "Vance's Blasting Cannons": 'Rare', 'Spitfire Bastion': 'Rare',
          'Boneyard Parley': 'Mythic', "Verdant Sun's Avatar": 'Rare', 'Tocatli Honor Guard': 'Rare',
          'Chart a Course': 'Uncommon', 'Overflowing Insight': 'Mythic', 'Arcane Adaptation': 'Rare',
          "River's Rebuke": 'Rare',
          'Axis of Mortality': 'Mythic', 'Sun-Blessed Mount': 'Rare', "Kinjalli's Sunwing": 'Rare',
          'Spell Swindle': 'Rare',
          'Herald of Secret Streams': 'Rare', 'Dowsing Dagger': 'Rare', 'Lost Vale': 'Rare',
          "Sunbird's Invocation": 'Rare',
          'Admiral Beckett Brass': 'Mythic', 'Dire Fleet Ravager': 'Mythic', 'Mavren Fein, Dusk Apostle': 'Rare',
          'Revel in Riches': 'Rare', 'Regisaur Alpha': 'Rare', "Shapers' Sanctuary": 'Rare',
          'Rampaging Ferocidon': 'Rare',
          'Sanctum Seeker': 'Rare', 'Tishana, Voice of Thunder': 'Mythic', "Wakening Sun's Avatar": 'Mythic',
          "Vraska's Contempt": 'Rare', 'Siren Stormtamer': 'Uncommon', 'Ripjaw Raptor': 'Rare',
          'Settle the Wreckage': 'Rare',
          'Vraska, Relic Seeker': 'Mythic', 'Jace, Cunning Castaway': 'Mythic', 'Thaumatic Compass': 'Rare',
          'Spires of Orazca': 'Rare', "Legion's Landing": 'Rare', 'Adanto, the First Fort': 'Rare',
          'Star of Extinction': 'Mythic', 'Unclaimed Territory': 'Uncommon', 'Treasure Map': 'Rare',
          'Treasure Cove': 'Rare',
          'Huatli, Warrior Poet': 'Mythic', 'Hostage Taker': 'Rare', "Gishath, Sun's Avatar": 'Mythic',
          'Vona, Butcher of Magan': 'Mythic', 'Sunpetal Grove': 'Rare', 'Dragonskull Summit': 'Rare',
          'Primal Amulet': 'Rare',
          'Primal Wellspring': 'Rare', 'Rootbound Crag': 'Rare', "Vanquisher's Banner": 'Rare',
          'Glacial Fortress': 'Rare', 'Jace, Ingenious Mind-Mage': 'Mythic', 'Huatli, Dinosaur Knight': 'Mythic',
          'Drowned Catacomb': 'Rare', 'Growing Rites of Itlimoc': 'Rare', 'Itlimoc, Cradle of the Sun': 'Rare',
          'Carnage Tyrant': 'Mythic', 'Search for Azcanta': 'Rare', 'Azcanta, the Sunken Ruin': 'Rare',
          "Alseid of Life's Bounty": 'Uncommon', 'Archon of Falling Stars': 'Uncommon', "Archon of Sun's Grace": 'Rare',
          'Banishing Light': 'Uncommon', 'The Birth of Meletis': 'Uncommon', 'Captivating Unicorn': 'Common',
          'Commanding Presence': 'Uncommon', 'Dawn Evangel': 'Uncommon', 'Daxos, Blessed by the Sun': 'Uncommon',
          'Daybreak Chimera': 'Common', 'Dreadful Apathy': 'Common', 'Eidolon of Obstruction': 'Rare',
          'Elspeth Conquers Death': 'Rare', "Elspeth, Sun's Nemesis": 'Mythic', 'Favored of Iroas': 'Uncommon',
          'Flicker of Fate': 'Common', 'Glory Bearers': 'Common', 'Heliod, Sun-Crowned': 'Mythic',
          "Heliod's Intervention": 'Rare', "Heliod's Pilgrim": 'Common', "Heliod's Punishment": 'Uncommon',
          'Hero of the Pride': 'Common', 'Hero of the Winds': 'Uncommon', 'Idyllic Tutor': 'Rare',
          'Indomitable Will': 'Common', "Karametra's Blessing": 'Common', 'Lagonna-Band Storyteller': 'Uncommon',
          'Leonin of the Lost Pride': 'Common', 'Nyxborn Courser': 'Common', 'Omen of the Sun': 'Common',
          'Phalanx Tactics': 'Uncommon', 'Pious Wayfarer': 'Common', 'Reverent Hoplite': 'Uncommon',
          'Revoke Existence': 'Common', 'Rumbling Sentry': 'Common', "Sentinel's Eyes": 'Common',
          'Shatter the Sky': 'Rare', 'Sunmane Pegasus': 'Common', 'Taranika, Akroan Veteran': 'Rare',
          'Transcendent Envoy': 'Common', 'Triumphant Surge': 'Common', 'Alirios, Enraptured': 'Uncommon',
          "Ashiok's Erasure": 'Rare', 'Brine Giant': 'Common', 'Callaphe, Beloved of the Sea': 'Uncommon',
          'Chain to Memory': 'Common', 'Deny the Divine': 'Common', 'Eidolon of Philosophy': 'Common',
          'Elite Instructor': 'Common', 'Glimpse of Freedom': 'Uncommon', 'Ichthyomorphosis': 'Common',
          'Kiora Bests the Sea God': 'Mythic', "Medomai's Prophecy": 'Uncommon', 'Memory Drain': 'Common',
          'Nadir Kraken': 'Rare', 'Naiad of Hidden Coves': 'Common', 'Nyxborn Seaguard': 'Common',
          'Omen of the Sea': 'Common', 'One with the Stars': 'Uncommon', 'Protean Thaumaturge': 'Rare',
          'Riptide Turtle': 'Common', 'Sage of Mysteries': 'Uncommon', "Sea God's Scorn": 'Uncommon',
          'Shimmerwing Chimera': 'Uncommon', 'Shoal Kraken': 'Uncommon', 'Sleep of the Dead': 'Common',
          'Starlit Mantle': 'Common', 'Stern Dismissal': 'Common', 'Stinging Lionfish': 'Uncommon',
          'Sweet Oblivion': 'Uncommon', 'Thassa, Deep-Dwelling': 'Mythic', "Thassa's Intervention": 'Rare',
          "Thassa's Oracle": 'Rare', 'Thirst for Meaning': 'Common', 'Threnody Singer': 'Uncommon',
          'Thryx, the Sudden Storm': 'Rare', 'Towering-Wave Mystic': 'Common', 'Triton Waverider': 'Common',
          'Vexing Gull': 'Common', 'Wavebreak Hippocamp': 'Rare', 'Whirlwind Denial': 'Uncommon',
          'Witness of Tomorrows': 'Common', 'Agonizing Remorse': 'Uncommon', 'Aphemia, the Cacophony': 'Rare',
          'Aspect of Lamprey': 'Common', 'Blight-Breath Catoblepas': 'Common', 'Cling to Dust': 'Uncommon',
          'Discordant Piper': 'Common', 'Drag to the Underworld': 'Uncommon', 'Eat to Extinction': 'Rare',
          "Elspeth's Nightmare": 'Uncommon', 'Enemy of Enlightenment': 'Uncommon', 'Erebos, Bleak-Hearted': 'Mythic',
          "Erebos's Intervention": 'Rare', 'Final Death': 'Common', 'Fruit of Tizerus': 'Common',
          'Funeral Rites': 'Common', 'Gravebreaker Lamia': 'Rare', 'Gray Merchant of Asphodel': 'Uncommon',
          'Grim Physician': 'Common', 'Hateful Eidolon': 'Uncommon', 'Inevitable End': 'Uncommon',
          "Lampad of Death's Vigil": 'Common', "Minion's Return": 'Uncommon', 'Mire Triton': 'Uncommon',
          "Mire's Grasp": 'Common', "Mogis's Favor": 'Common', 'Nightmare Shepherd': 'Rare',
          'Nyxborn Marauder': 'Common', 'Omen of the Dead': 'Common', "Pharika's Libation": 'Common',
          "Pharika's Spawn": 'Uncommon', 'Rage-Scarred Berserker': 'Common', 'Scavenging Harpy': 'Common',
          'Soulreaper of Mogis': 'Common', 'Temple Thief': 'Common', 'Treacherous Blessing': 'Rare',
          'Tymaret Calls the Dead': 'Rare', 'Tymaret, Chosen from Death': 'Uncommon', 'Underworld Charger': 'Common',
          'Underworld Dreams': 'Uncommon', 'Venomous Hierophant': 'Common', 'Woe Strider': 'Rare',
          'The Akroan War': 'Rare', 'Anax, Hardened in the Forge': 'Uncommon', 'Arena Trickster': 'Common',
          'Aspect of Manticore': 'Common', 'Blood Aspirant': 'Uncommon', 'Careless Celebrant': 'Uncommon',
          'Dreamshaper Shaman': 'Uncommon', 'Dreamstalker Manticore': 'Uncommon', 'Escape Velocity': 'Uncommon',
          'Fateful End': 'Uncommon', 'Final Flare': 'Common', 'Flummoxed Cyclops': 'Common', 'Furious Rise': 'Uncommon',
          'Hero of the Games': 'Common', 'Heroes of the Revel': 'Uncommon', 'Impending Doom': 'Uncommon',
          'Incendiary Oracle': 'Common', "Iroas's Blessing": 'Common',
          'Irreverent Revelers': 'Common', 'Nyxborn Brute': 'Common', 'Omen of the Forge': 'Common',
          "Oread of Mountain's Blaze": 'Common', 'Ox of Agonas': 'Mythic', 'Phoenix of Ash': 'Rare',
          'Portent of Betrayal': 'Common', 'Purphoros, Bronze-Blooded': 'Mythic', "Purphoros's Intervention": 'Rare',
          "Satyr's Cunning": 'Common', 'Skophos Maze-Warden': 'Uncommon', 'Skophos Warleader': 'Common',
          'Stampede Rider': 'Common', 'Storm Herald': 'Rare', "Storm's Wrath": 'Rare', 'Tectonic Giant': 'Rare',
          'The Triumph of Anax': 'Uncommon', 'Underworld Breach': 'Rare',
          'Underworld Fires': 'Uncommon', 'Underworld Rage-Hound': 'Common', 'Wrap in Flames': 'Common',
          'Arasta of the Endless Web': 'Rare', 'The Binding of the Titans': 'Uncommon', 'Chainweb Aracnir': 'Uncommon',
          'Destiny Spinner': 'Uncommon', 'Dryad of the Ilysian Grove': 'Rare', 'The First Iroan Games': 'Rare',
          "Hydra's Growth": 'Uncommon', 'Hyrax Tower Scout': 'Common',
          'Ilysian Caryatid': 'Common', 'Inspire Awe': 'Common', "Klothys's Design": 'Uncommon',
          'Loathsome Chimera': 'Common', 'Mantle of the Wolf': 'Rare', 'Moss Viper': 'Common',
          'Mystic Repeal': 'Uncommon', 'Nessian Boar': 'Rare', 'Nessian Hornbeetle': 'Uncommon',
          'Nessian Wanderer': 'Uncommon', 'Nexus Wardens': 'Common', 'Nylea, Keen-Eyed': 'Mythic',
          "Nylea's Forerunner": 'Common', "Nylea's Huntmaster": 'Common', "Nylea's Intervention": 'Rare',
          'Nyx Herald': 'Uncommon', 'Nyxbloom Ancient': 'Mythic', 'Nyxborn Colossus': 'Common',
          'Omen of the Hunt': 'Common', 'Pheres-Band Brawler': 'Uncommon',
          'Relentless Pursuit': 'Common', 'Renata, Called to the Hunt': 'Uncommon',
          'Setessan Champion': 'Rare', 'Setessan Petitioner': 'Uncommon', 'Setessan Skirmisher': 'Common',
          'Setessan Training': 'Common', 'Skola Grovedancer': 'Common', 'Voracious Typhon': 'Common',
          'Warbriar Blessing': 'Common', 'Wolfwillow Haven': 'Uncommon', 'Acolyte of Affliction': 'Uncommon',
          'Allure of the Unknown': 'Rare', 'Ashiok, Nightmare Muse': 'Mythic', 'Atris, Oracle of Half-Truths': 'Rare',
          'Bronzehide Lion': 'Rare', "Calix, Destiny's Hand": 'Mythic', 'Dalakos, Crafter of Wonders': 'Rare',
          'Devourer of Memory': 'Uncommon', 'Dream Trawler': 'Rare', 'Enigmatic Incarnation': 'Rare',
          'Eutropia the Twice-Favored': 'Uncommon', 'Gallia of the Endless Dance': 'Rare',
          'Haktos the Unscarred': 'Rare', 'Hero of the Nyxborn': 'Uncommon', 'Klothys, God of Destiny': 'Mythic',
          "Kroxa, Titan of Death's Hunger": 'Mythic', 'Kunoros, Hound of Athreos': 'Rare',
          'Mischievous Chimera': 'Uncommon', 'Polukranos, Unchained': 'Mythic', 'Rise to Glory': 'Uncommon',
          'Siona, Captain of the Pyleas': 'Uncommon', 'Slaughter-Priest of Mogis': 'Uncommon',
          'Staggering Insight': 'Uncommon', "Uro, Titan of Nature's Wrath": 'Mythic',
          'Warden of the Chained': 'Uncommon', 'Altar of the Pantheon': 'Common', 'Bronze Sword': 'Common',
          'Entrancing Lyre': 'Uncommon', 'Mirror Shield': 'Uncommon', 'Nyx Lotus': 'Rare', 'Shadowspear': 'Rare',
          'Soul-Guide Lantern': 'Uncommon', "Thaumaturge's Familiar": 'Common', 'Thundering Chariot': 'Uncommon',
          "Traveler's Amulet": 'Common', 'Wings of Hubris': 'Common', 'Field of Ruin': 'Uncommon',
          'Labyrinth of Skophos': 'Rare', 'Temple of Abandon': 'Rare', 'Temple of Deceit': 'Rare',
          'Temple of Enlightenment': 'Rare', 'Temple of Malice': 'Rare', 'Temple of Plenty': 'Rare',
          'Athreos, Shroud-Veiled': 'Mythic',
          'Elspeth, Undaunted Hero': 'Mythic', 'Eidolon of Inspiration': 'Uncommon', "Elspeth's Devotee": 'Rare',
          'Sunlit Hoplite': 'Common', 'Ashiok, Sculptor of Fears': 'Mythic', 'Swimmer in Nightmares': 'Uncommon',
          'Mindwrack Harpy': 'Common', "Ashiok's Forerunner": 'Rare', 'Plains (v. 2)': 'Common',
          'Island (v. 2)': 'Common', 'Swamp (v. 2)': 'Common', 'Mountain (v. 2)': 'Common', 'Forest (v. 2)': 'Common',
          'Grasping Giant': 'Rare', "Victory's Envoy": 'Rare', 'Sphinx Mindbreaker': 'Rare',
          'Serpent of Yawning Depths': 'Rare', 'Demon of Loathing': 'Rare', 'Underworld Sentinel': 'Rare',
          'Deathbellow War Cry': 'Rare', 'Terror of Mount Velus': 'Rare', 'Ironscale Hydra': 'Rare',
          'Treeshaker Chimera': 'Rare', 'Mind Stone': 'Common', 'Phyrexian Arena': 'Rare',
          'Goblin Ruinblaster': 'Uncommon', 'Goblin Matron': 'Uncommon', 'Burning-Tree Emissary': 'Uncommon',
          'Ranger of Eos': 'Rare', 'Thalia, Guardian of Thraben': 'Rare', 'Meddling Mage': 'Rare',
          'Ornithopter': 'Uncommon', 'Teferi, Hero of Dominaria': 'Mythic', 'Waste Not': 'Rare',
          "Ixalan's Binding": 'Uncommon', 'Ghost Quarter': 'Uncommon', 'Kinsbaile Cavalier': 'Rare'}
